### ISSUE TITLE
Is IPv6 disabled in latest docker image?

### ISSUE THREAD

**Issue by bmcclareifs** [Shippable/support#3796] opened 2017-08-25 14:46 UTC
### Description of your issue:
We recently moved from the "stable" CI docker image the latest "5.8.2". 

It looks like this change caused our component to be unable to open it's http listener:
`2017-08-24 21:08:27,062 ERROR [stderr] (main) Caused by: org.jboss.msc.service.StartException in service jboss.undertow.listener.default: WFLYUT0082: Could not start 'default' listener.
2017-08-24 21:08:27,062 ERROR [stderr] (main) 	at org.wildfly.extension.undertow.ListenerService.start(ListenerService.java:153)
2017-08-24 21:08:27,069 ERROR [stderr] (main) 	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
2017-08-24 21:08:27,069 ERROR [stderr] (main) 	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
2017-08-24 21:08:27,069 ERROR [stderr] (main) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2017-08-24 21:08:27,069 ERROR [stderr] (main) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2017-08-24 21:08:27,069 ERROR [stderr] (main) 	at java.lang.Thread.run(Thread.java:748)
2017-08-24 21:08:27,069 ERROR [stderr] (main) Caused by: java.net.SocketException: Protocol family unavailable`

From within the docker image it looks like IPv6 is disabled?
`/# ip -6 a` (no results)

We found a potential fix for this by setting the java options to prefer IPv4 when starting our component: adding `-Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Addresses` 

This is the whole command from our script which is invoked from our .yml script:
`nohup java -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Addresses -jar forecast-service/target/forecast-service-swarm.jar > server.log 2>&1&`

Does our fix seem appropriate? Maybe there's a better approach? Re-enable IPv6? I suspect we require IPv6 in this context.

- Link to the build failure
https://app.shippable.com/bitbucket/mxitechnologies/lrp-forecast/runs/846/1/console

Related ticket:
https://github.com/Shippable/support/issues/3795

Thanks.

**Comment by bmcclareifs** [comment] 2017-08-29 16:11
I should correct my mistake above: I suspect we **don't** require IPv6 in this context.

**Comment by ambarish2012** [comment] 2017-08-29 16:42
ok thanks. I will close this issue for now. Please feel free to open a new issue if you need any further assistance.

**Comment by Zingoer** [comment] 2017-08-29 18:51
@ambarish2012 Hello, we still have problem with this issue. My colleague just wants to change the typo. I think there somewhere the IPv6 module is not installed or is not enabled for the instance level or docker level so that we got this error. And I double check, the main cause is because:
ERROR [stderr] (main) Caused by: java.net.SocketException: Protocol family unavailable
which means that the ipv6 is not enabled

**Comment by ambarish2012** [comment] 2017-08-29 19:59
@Zingoer we will have an update soon.

**Comment by trriplejay** [comment] 2017-08-29 20:22
looks like this is handled differently in newer versions of docker, which is causing your issue.  the "stable" machine image was using docker 1.9

One work-around option would be to switch to custom hosts, where you could select a docker version, and further tweak the installation if necessary. The docs on ipv6 with docker are here: https://docs.docker.com/engine/userguide/networking/default_network/ipv6/

You could also try switching to an older machine image, like v5.3.2, though i'm not sure if this will actually help or not. (this uses docker 1.13.0)

I'll tag this as a feature request so that we can look into what it would take to get this supported in our latest machine images.

**Comment by Zingoer** [comment] 2017-08-30 16:07
@ambarish2012, @trriplejay Thank you for your help! I think we will park this issue and keep tracking this potential feature update. And right now, we will use the work around to solve it.

**Comment by ambarish2012** [comment] 2017-08-30 16:19
Thanks @Zingoer. I will keep update you once the feature is live in production.

**Closed** 2018-01-31 03:27 UTC
Labels: feature request, investigate
