### ISSUE TITLE
Frequent timeouts

### ISSUE THREAD

**Issue by 9dev** [Shippable/support#2939] opened 2016-09-04 09:59 UTC
Hi there,

My build keeps timing out, despite really small number of tests. Sometimes it works (and takes about 10 minutes) and sometimes it hangs for an hour and times out. Note I'm talking about the same code - the same commit.

The error in logs looks like this:

> echo Container c.exec.tc.65.1 exited with 137
> Container c.exec.tc.65.1 exited with 137
> 
> sudo docker rm -fv $CONTAINER_NAME
> Error response from daemon: no such id: c.exec.tc.65.1
> Error: failed to remove containers: [c.exec.tc.65.1]

Link to passed: https://app.shippable.com/runs/57bc532b503ad81000c7833a/1/console
Link to timeout: https://app.shippable.com/runs/57bc58283d3c340e00032511/1/console
(same commit)

Thanks!

**Comment by a-murphy** [comment] 2016-09-12 20:29
Since the builds that time out all end with the same line in the logs, this is most likely something about your tests. Is there an asynchronous operation that could sometimes, but not always, complete before the part of your tests that gets stuck?  Another possibility is that the build could be running out of memory, but those don't usually all occur on the same line.  Increasing the logs in your tests, if possible, may help find the cause.

**Comment by manishas** [comment] 2016-11-14 21:20
Closing this since there was no follow up. @9dev are you still running into this issue?

**Closed by manishas** 2016-11-14 21:20 UTC
Labels: need info from customer, question
