### ISSUE TITLE
Request: pull requests for bitbucket

### ISSUE THREAD

**Issue by bbradbury** [Shippable/support#992] opened 2015-01-21 18:21 UTC
Would be great to support pull requests for bitbucket in addition to the current github support.

**Comment by manishas** [comment] 2015-01-23 08:37
@bbradbury thanks for the suggestion! We would very much like to support PRs for bitbucket, but there were some limitations in their API. We will check in to see if anything has changed and add support as soon as we can. 

I am closing this issue since this is a duplicate of https://github.com/Shippable/support/issues/237.

**Closed by manishas** 2015-01-23 08:37 UTC
Labels: duplicate, feature request

**Comment by ttrahan** [comment] 2016-04-06 20:55
@bbradbury: This is now available. Please take a look at the [docs](http://docs.shippable.com/ci_configure/#pull-requests) for more details. Let us know if you have any questions.

**Comment by bbradbury** [comment] 2016-04-06 21:02
Awesome thanks @ttrahan ! We'll put it to use immediately.
