### ISSUE TITLE
Transfer payment details to an organization

### ISSUE THREAD

**Issue by JustAdam** [Shippable/support#1286] opened 2015-04-08 06:33 UTC
Hello,
How can I transfer payment details & extra features to an organisation?  Currently they are under the user we login into shippable with (along with the extra minions), but we need them on the organisation account.

Regards.

**Comment by manishas** [comment] 2015-04-08 23:59
@JustAdam you can upgrade the org and we will issue a refund for the user who was upgraded. Let me know the org name and github username of the user who needs a refund.

**Comment by JustAdam** [comment] 2015-04-09 08:42
The problem was there is no possibility to add a payment option for the org, so I added it against the user in the hope it would be available against the org :)  Not so!

In any case, the username is `bitbucket/noadmai` and the details need to transfer over to the org `bitbucket/allermedia`.

**Comment by JustAdam** [comment] 2015-04-14 06:04
Hey, Any update here @manishas ?

**Comment by manishas** [comment] 2015-04-14 07:18
@JustAdam are you an owner of the org you're trying to upgrade?

**Comment by JustAdam** [comment] 2015-04-14 07:25
@manishas I am the owner of the org.  The account is setup through the user `bitbucket/noadmai` which then provides access to the org `bitbucket/allermedia`.

We need the payment details/account extras that are on the account `bitbucket/noadmai` to be available and usable on the org.

**Comment by JustAdam** [comment] 2015-04-20 09:14
Hey @manishas any further updates as to what is happening here?

**Comment by manishas** [comment] 2015-04-20 14:14
@JustAdam we'll address this today. Sorry for the delay!

**Comment by JustAdam** [comment] 2015-04-23 05:37
How did this go @manishas ?  I am still seeing the info in the wrong place.

**Comment by rageshkrishna** [comment] 2015-04-23 06:20
Hi @JustAdam. We're looking in to this. The problem is that our database does not indicate that you are an owner on `bitbucket/allermedia`. This seems like an issue with how we're synchronizing the permissions from BitBucket.

I'll update this issue as soon as I know more.

**Comment by JustAdam** [comment] 2015-04-23 06:40
Hi @rageshkrishna The owner of the org should be `bitbucket/noadmai` (that is at least the username we log into Shippable with and set the org up from).

Another note which actually caused this issue, is that there is no way to add payment details to an org account in the ui.

**Comment by rageshkrishna** [comment] 2015-04-23 06:55
Yup, I understand what you're saying. The UI for adding payment details shows up only if the system believes you're an owner of the org. Once we resolve this issue, you'll be able to set up your credit card on the org and upgrade it directly.

**Comment by JustAdam** [comment] 2015-04-23 06:58
Ok cool, let me know if you require any more info from our end.

**Comment by rageshkrishna** [comment] 2015-04-23 07:00
It looks like `bitbucket/JustAdam` is showing up as an owner of the `bitbucket/allermedia` organization. Can you log in to Shippable with that BitBucket account and check if you are able to set up a payment method?

**Comment by JustAdam** [comment] 2015-04-23 07:03
Yes I can.  Ideally we need `bitbucket/noadmai` to be the owner (not sure how my personal account became the owner, as everything was setup via noadmai).  I can have a look in bitbucket to see if there is some settings to change.

**Comment by JustAdam** [comment] 2015-04-23 07:08
I have given the `noadmai` user full access to our organisation at bitbucket, and now I have the payment option available.

So all that remains now is if it is possible to transfer the credit from `noadmai` over to the org.

**Comment by rageshkrishna** [comment] 2015-04-23 07:13
We synchronize all permissions directly from BitBucket. Now that `noadmai` is an owner in BitBucket, you can set up the payment method on the organization in Shippable, too.

Unfortunately, there's no easy way to transfer credits across different orgs at the moment. It would be quicker for you to go ahead and upgrade `allermedia` to the paid plan now and I will issue a refund for the charge that was made against `noadmai` once you confirm.

**Comment by JustAdam** [comment] 2015-04-23 07:41
Ok, I have set up the plan on the org now.  Thanks for you help.

**Comment by rageshkrishna** [comment] 2015-04-23 07:55
Alright, I will now downgrade `noadmai` to a free plan and refund that transaction.

**Comment by rageshkrishna** [comment] 2015-04-23 08:05
The downgrade on `noadmai` and refund of the transaction are done. You should see a refund on your credit card in a few days.

I'm closing this issue now. Let me know if you need any more help with this!

**Closed by rageshkrishna** 2015-04-23 08:05 UTC
Labels: question, triaged
