### ISSUE TITLE
Exclude Tag / Branch names with wildcards

### ISSUE THREAD

**Issue by TheEadie** [Shippable/support#1536] opened 2015-06-10 18:35 UTC
Is it possible to exclude tags for building via wildcards eg. To not build anything beginning "bulid/" or "release/"

I've tried using the travis style regex in the excludes section of the shippable.yml but this doesn't seem to prevent the tag triggering a build.

```
branches:
  except:
    - /^build.*$/
```

**Comment by TheEadie** [comment] 2015-07-01 13:11
Any thoughts on this guys?

**Comment by mbrodala** [comment] 2015-11-18 22:08
I'd say this is a duplicate of #693

**Comment by manishas** [comment] 2016-03-03 00:15
closing since this is a duplicate. i will leave the other one open.

**Closed by manishas** 2016-03-03 00:15 UTC
