### ISSUE TITLE
Difference between Shippable test report and junit report

### ISSUE THREAD

**Issue by JarmBlueOak** [Shippable/support#3575] opened 2017-05-09 12:34 UTC
Hi Shippable team,

We are currently migrating our current CI system to your platform and we are experiencing a difference in the test case results being reported in the Shippable test results vs our junit reporting artifacts.

The results from our [Build 80](https://app.shippable.com/github/attiam-blueoak/BlueBilling/runs/80/1/tests) tests tab show 142 tests passed and 12 skipped. Our [junit-noframes.html.txt](https://github.com/Shippable/support/files/986557/junit-noframes.html.txt) report output from the same build which we aws sync on_success shows 128 passed 51 errors and 6 skipped. Why is there a difference? The junit html report and Shippable are using the same junit test output xml's.

Thanks, Jamie Armstrong
Blue Oak Development Team

**Comment by ambarish2012** [comment] 2017-05-10 01:23
@JarmBlueOak we are investigating, thanks for reporting this issue.

**Comment by ambarish2012** [comment] 2017-05-10 01:50
@JarmBlueOak this is a bug that we will investigate. After I looked at your logs and counted the number of failed tests, I do see 51 tests failing.

In fact we do even indicate clearly in the logs that tests have failed -

/root/src/github.com/attiam-blueoak/BlueBilling/build/build.xml:326: JUnits have failed, check the logs in /root/src/github.com/attiam-blueoak/BlueBilling/build/../shippable/testresults

**Comment by JarmBlueOak** [comment] 2017-05-10 11:04
After extensive research and troubleshooting we have been able to get our complete build to run with all test cases. The issue was related to lower_case_table_names being set to 0 and we have some older system tables that are in all capitals. Once this variable was set to 1 by adding our own .cnf file in /etc/mysql/conf.d/ with the this variable value added everything is running fine. However we do want to know why the initial errors were not counted by the shippable test reports. Cheers.

**Comment by ambarish2012** [comment] 2017-05-10 16:20
@JarmBlueOak we are investigating, a bug has been created and I will update this issue as soon as we root cause.

**Comment by manishas** [comment] 2017-10-27 22:47
This was fixed a long time ago.... I apologize for not updating this earlier.

Closing now... let us know if you still see this problem.

**Closed by manishas** 2017-10-27 22:47 UTC
Labels: bug
