### ISSUE TITLE
gitRepo does not trigger anymore

### ISSUE THREAD

**Issue by BotellaA** [Shippable/support#4537] opened 2018-09-03 10:26 UTC
My gitRepo georep_start [(link)](https://app.shippable.com/subs/bitbucket/ArnaudBotella/resources/georep_start/versions) does not get triggered anymore but the ciRepo still works [(link)](https://app.shippable.com/subs/bitbucket/ArnaudBotella/resources/georep_ciRepo/versions). I do not understand why. I did not change anything in the yml files.

Thanks for your help

**Comment by ankul-shippable** [comment] 2018-09-04 06:12
@BotellaA I see that a version for ciRepo was created for pull request. For gitRepo resource(i.e. `georep_start`) no new version was created because it ignores pull request webhooks by default. To create versions for gitRepo resources on pull requests, add the `buildOnPullRequest` flag:
```
resources:
  - name: georep_start
    type: gitRepo
    integration:  <integration_name>
    versionTemplate:
      sourceName: <source_name>
      buildOnPullRequest: true
```

Please let us know if you need any help with configuring your pipelines.

**Comment by BotellaA** [comment] 2018-09-04 07:32
My links mislead you. I just pushed another commit (without PR) on a new branch called `flann` and both gitRepo and ciRepo did not get updated.

I checked the webhook from bitbucket and the request was sent and the status is `200`.

Do you need more data to understand the situation?

**Comment by ankul-shippable** [comment] 2018-09-04 07:58
okay, could you reset your the project and check again?
To reset a project goto projects/settings tab and click on `Reset all keys`.

![docs_link](http://docs.shippable.com/images/platform/visibility/project-settings-3.jpg)

**Comment by BotellaA** [comment] 2018-09-04 08:28
I reset the keys but same behavior. It looks like 2 PR builds are created for the same commit and no classic build (see https://app.shippable.com/bitbucket/ArnaudBotella/georep/dashboard and job 1012 and 1013). BTW, the commit referenced in theses builds is 8a28cba847 and it is not my latest commit.

Maybe something is wrong on bitbucket side...

**Comment by nikaspran** [comment] 2018-09-04 10:26
We also have the same issue, see https://app.shippable.com/github/hostmakerco/hostmaker-website/runs?branchName=production

Builds are not getting auto-triggered by github commits as of at least 14hrs ago.

We also did not change anything in our configuration.

Github is also reporting Shippable webhooks as successfully triggering and returning `200 OK`. Seems like an issue on Shippable's side.

**EDIT:** seems to have been unrelated, apologies

**Comment by ankul-shippable** [comment] 2018-09-04 11:45
@nikaspran we see that your builds are getting triggered. Are you still facing the issue?

If so, could you please send me the webhook payload at ankul@shippable.com for which the builds did not trigger on shippable?

Also, we see that you have disabled builds on `commits`. was this change done recently?
![image](https://user-images.githubusercontent.com/16793274/45030106-6c02a480-b068-11e8-982b-cc9e030c11ef.png)

**Comment by ankul-shippable** [comment] 2018-09-04 12:04
@BotellaA Could you please check if your project has more than one webhooks added from Shippable.

If so, could you please send me the webhook URLs at ankul@shippable.com?

**Comment by trriplejay** [comment] 2018-09-05 17:49
@BotellaA It looks like a "branch" field of "master" is now in your gitRepo resource. This will mean that only commits to "master" trigger your repo.  I see that this repo version was added at about 7:08am 8/31 (UTC).  It looks like this version was created by you, and not by a webhook (the "triggeredBy" field has your bitbucket display name, and no webhook information in the payload).  Do you remember taking any particular action at this time? like maybe using shippable API to manually POST a version? or some other manual action in the UI? we're trying to investigate how this field could have been added. 

If this is the case, we can correct it by posting another new version that removes the branch field, but we wanted to figure out how this happened in the first place.

**Comment by BotellaA** [comment] 2018-09-05 21:11
I do not really know how to manually trigger a gitRepo. All the versions of this gitRepo are auto-triggered from a push.

**Comment by trriplejay** [comment] 2018-09-05 21:36
We're still investigating the root cause, but I've updated your repo version so a commit to any branch should properly update it. You can try re-sending old webhooks via the bitbucket UI, or just make a new commit to verify.

**Comment by BotellaA** [comment] 2018-09-06 06:23
I pushed another commit and it seems to work. Thanks
Good luck for your investigation.

You can close the issue, unless you want me to try something else.

**Comment by trriplejay** [comment] 2018-09-13 16:27
We've uncovered the root cause, and this will be fixed in our next release. I'll close this issue once the fix is deployed.

**Comment by trriplejay** [comment] 2018-09-14 19:23
This fix has been released. please let me know if you encounter this issue again.

**Closed as completed by trriplejay** 2018-09-14 19:23 UTC
