### ISSUE TITLE
C / C++ support?

### ISSUE THREAD

**Issue by jupe** [Shippable/support#1019] opened 2015-02-01 09:02 UTC
I would like to see C / C++ support as well. Is it possible ? 
* gcc
* make

**Comment by manishas** [comment] 2015-02-03 00:59
this is a duplicate of https://github.com/Shippable/support/issues/312 so closing as duplicate. @jupe there are some suggestions of how to make c/c++ projects work with Shippable even though it is not officially supported.

**Closed by manishas** 2015-02-03 00:59 UTC
Labels: feature request, triaged
