### ISSUE TITLE
"apt-get update" returns a "signatures couldn't be verified" error

### ISSUE THREAD

**Issue by jerbia** [Shippable/support#1423] opened 2015-05-08 07:31 UTC
I am using a Python image for my build. In my "before_install" section there is a call to:
sudo apt-get update -qq -y

The build fails with following message:

W: GPG error: http://ppa.launchpad.net precise Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B70731143DD9F856
W: Failed to fetch http://debian.neo4j.org/repo/stable/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead. 

Can you please advice?

**Comment by timanyvan** [comment] 2015-05-08 08:52
We are having the same issue.

On a side note: the readme for this repo still indicates a problem from 9 days ago!

**Comment by Backenkoehler** [comment] 2015-05-08 11:56
:+1:  we have the same problem with the minv2 image.

**Comment by normseth** [comment] 2015-05-08 17:55
The issue here is with neo4j (see error output from original post).   I can see it affecting other ubuntu containers/boxes, so this isn't specific to Shippable.   

Because I'm not using neo4j, I was able to work around the problem by removing it from the apt-get source list.  Try adding the following immediately before your apt-get update line in shippable.yml:    

- sudo rm /etc/apt/sources.list.d/neo4j.list

**Comment by jerbia** [comment] 2015-05-08 19:28
Thanks!
Adding "sudo rm /etc/apt/sources.list.d/neo4j.list" before "apt-get update"
seems to resolve the error,
which caused Shippable to exit from the build.

I still have the below issue when running "apt-get update" but at least it
is a warning which does not stop the build:
W: GPG error: http://ppa.launchpad.net precise Release: The following
signatures couldn't be verified because the public key is not available:
NO_PUBKEY B70731143DD9F856

So again - the failed neo4j update caused build to stop. Removing neo4j
from the apt source list supplies
a workaround for the problem.

**Comment by vkuusk** [comment] 2015-05-11 23:31
alternatively 
before running "apt-get update"
you can add the neo4j repository key

sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com B70731143DD9F856

**Comment by manishas** [comment] 2015-05-12 16:05
@vkuusk @jerbia @normseth thanks for helping each other out! It looks like the problem is resolved... can we help further?

**Comment by jerbia** [comment] 2015-05-12 16:11
Thanks. I am good from my side.

**Comment by manishas** [comment] 2015-05-21 00:35
Closing. Thanks!

**Closed by manishas** 2015-05-21 00:35 UTC
Labels: bug, triaged
