### ISSUE TITLE
IMAGE_NAME and TAG do not get replaced on EBS Docker deployment

### ISSUE THREAD

**Issue by pbouillet** [Shippable/support#2992] opened 2016-09-23 09:41 UTC
I am trying to set up a CI build but I don't know how to get the EBS Docker deployment to work:
https://app.shippable.com/runs/57e4f3d78afa9e0e00c8b77a/1/console

It seems like the whole EBS integration works as expected (as the artifact does get uploaded into the S3 bucket), but the IMAGE_NAME and TAG variables do not get replaced. Am I missing here something?

Thanks

**Comment by trriplejay** [comment] 2016-09-23 18:45
it looks like you're doing the right thing. We're checking on this.

**Comment by trriplejay** [comment] 2016-09-23 20:40
I can't seem to reproduce this. can you try a couple things?

1. take `target` out of your yml, it's not required
2. take 'bucket_name' out of your yml, it's not required
3. can you check your s3 bucket, download the zip file, and open the Dockerrun.aws.json file? does it still have the placeholders?

**Comment by pbouillet** [comment] 2016-09-26 06:39
Thanks @trriplejay for the fast reply!

Just tried out your suggestions, but the result is the same (look at https://app.shippable.com/runs/57e8bef28970d90f00148ef6/1/console) . In the uploaded zip, the Dockerrun.aws.json still contains the non replaced values. And is it correct that this zip file contains all of my application files? Shouldn't it just contain this file?

**Comment by trriplejay** [comment] 2016-09-26 18:03
if you want it to only contain the Dockerrun file, you'll have to add an `.ebignore` file to your repo that looks something like this:

```
*
!Dockerrun.aws.json
```

by default, the eb cli packages everything. The above file will tell it to ignore everything except the Dockerrun.aws.json

Still investigating why your tags aren't being replaced...

**Comment by trriplejay** [comment] 2016-09-26 21:00
@pbouillet did your zip file have a `Dockerrun.tmp` file in it?

**Comment by pbouillet** [comment] 2016-09-27 06:13
No `Dockerrun.tmp` can be found in the zip file.

**Comment by trriplejay** [comment] 2016-09-27 19:51
alright, I think we've managed to reproduce. For some reason in this specific case, eb deploy is not packaging the changes made to the repo, and so the original files are being deployed instead of the modified files. We're continuing to investigate why, and we'll work on a fix.

**Comment by trriplejay** [comment] 2016-09-28 05:24
we've released a fix for this. can you give it another try and let me know if it works?

**Comment by pbouillet** [comment] 2016-09-28 07:02
It works! Awesome! Thank you very much @trriplejay

**Comment by trriplejay** [comment] 2016-09-28 17:15
great! closing as resolved.

**Closed by trriplejay** 2016-09-28 17:15 UTC
Labels: resolved
