### ISSUE TITLE
Golang build step failed, but travis working as well

### ISSUE THREAD

**Issue by netroby** [Shippable/support#1990] opened 2015-11-03 01:54 UTC
```
  script
  go get github.com/tools/godep
  godep go build -v
/home/shippable/5e2fb2aa-409a-4166-bec0-b5e92abdd23e.sh: line 88: godep: command not found
```

Here is the origin git source repo
https://github.com/netroby/gosense

and the travis.yml
```
language: go

go:
  - 1.3
  - 1.4


script:
     - go get github.com/tools/godep
     - godep go build -v
     - ls -l
```

**Comment by rageshkrishna** [comment] 2015-11-09 09:27
@netroby We've figured out what the problem is. A fix will be available in the next hour or so. Sorry about taking so long on this.

**Comment by netroby** [comment] 2015-11-09 10:06
Oh， glad to hear that. i am not willing using shippable anymore. thanks for let me know.

**Comment by rageshkrishna** [comment] 2015-11-09 10:13
@netroby This has now been fixed. I hope you do give it a shot again some time soon. Thanks!

**Comment by manishas** [comment] 2015-11-09 23:39
closing this issue. please  let us know if this is not working for you.

**Closed by manishas** 2015-11-09 23:39 UTC
Labels: bug, resolved
