### ISSUE TITLE
Email invites sent to long gone team members

### ISSUE THREAD

**Issue by sdlarsen** [Shippable/support#1824] opened 2015-08-28 10:08 UTC
Hi. We're using shippable with bitbucket integration. For some reason we keep getting email invites sent to team members that are no longer with us, and not present in our company bitbucket account. Why is that and how do we stop it?

Br.
Søren
ÜberResearch

**Comment by lekhab** [comment] 2015-08-31 18:16
@sdlarsen: It is possible that the users who are getting the invites have not synced their account - so we haven't gotten their updated permissions yet. Please let me know the names of the users who no longer have access and I can confirm the details for you. You can send me an email at lekha@shippable.com.

**Comment by lekhab** [comment] 2015-09-10 00:45
Closing this, since the issue is now resolved and email has been sent.

**Closed by lekhab** 2015-09-10 00:45 UTC
Labels: question, resolved, triaged
