### ISSUE TITLE
Not able to log in to shippable app

### ISSUE THREAD

**Issue by paulcornwell** [Shippable/support#3134] opened 2016-11-07 17:03 UTC
### Description of your issue:
I'm using the same bitbucket account I always use.  I received the following error:
Error
 An error occured, please choose an action.

getSystemIntegrationById for :id 58153295203fb3100060dca2 returned an error

**Comment by a-murphy** [comment] 2016-11-07 17:05
Could you clicking the "logout" button and trying again?  It should be working now,

Duplicate of #3133

**Comment by manishas** [comment] 2016-11-07 19:41
Closing this since it's resolved.

**Closed by manishas** 2016-11-07 19:41 UTC

**Comment by fabiusks** [comment] 2017-06-05 16:26
Hello! Having the same problem here! Any suggestions? 

Thanks!

**Comment by manishas** [comment] 2017-06-05 16:28
@fabiusks we're looking into this as we speak.

**Comment by fabiusks** [comment] 2017-06-05 16:29
Thank you :) I'll try again soon! Good luck hehe

**Comment by ambarish2012** [comment] 2017-06-05 16:32
@fabiusks we will keep posting updates here - http://status.shippable.com/

**Comment by fabiusks** [comment] 2017-06-05 16:41
Ok Thanks @ambarish2012

**Comment by ambarish2012** [comment] 2017-06-05 16:49
@fabiusks issue has been resolved.

**Comment by fabiusks** [comment] 2017-06-05 16:50
Thank you guys!
