### ISSUE TITLE
Error gcr login : gcloud command not found

### ISSUE THREAD

**Issue by phagunbaya** [Shippable/support#2288] opened 2016-03-01 07:26 UTC
Build failing because of following reason :
```
cd /tmp && gcloud -q auth activate-service-account --key-file key.json
  //92a51faa-e6b4-4d2a-ab28-aac9dba854d3.sh: line 58: gcloud: command not found
```
<img width="735" alt="screen shot 2016-02-29 at 11 23 37 pm" src="https://cloud.githubusercontent.com/assets/1146297/13420521/cde1e180-df3b-11e5-9c4e-247de0b0d6fc.png">

**Comment by pmezard** [comment] 2016-03-01 08:24
Duplicate of https://github.com/Shippable/support/issues/2272 , related to https://github.com/Shippable/support/issues/2276 .

**Comment by manishas** [comment] 2016-03-02 05:16
this has been resolved. closing.

**Closed by manishas** 2016-03-02 05:16 UTC
