### ISSUE TITLE
Is the Bitbucket integration currently down?

### ISSUE THREAD

**Issue by Azuka** [Shippable/support#4561] opened 2018-09-20 06:41 UTC
### Description of your issue:
I noticed my builds for Bitbucket were failing and also that when I try to sign in using Bitbucket (after signing out), I get the error below:

```
InternalOAuthError: Failed to obtain request token
    at Strategy.OAuthStrategy._createOAuthError (/home/shippable/www/node_modules/passport-oauth1/lib/strategy.js:396:17)
    at /home/shippable/www/node_modules/passport-oauth1/lib/strategy.js:244:41
    at /home/shippable/www/node_modules/oauth/lib/oauth.js:543:17
    at passBackControl (/home/shippable/www/node_modules/oauth/lib/oauth.js:397:13)
    at IncomingMessage.<anonymous> (/home/shippable/www/node_modules/oauth/lib/oauth.js:409:9)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```
NOTE: If you are experiencing a build failure, please include:

- Link to the build failure
- Scripts called from the yml (optional)

**Comment by psoders** [comment] 2018-09-20 06:54
experiencing same issue

**Comment by rageshkrishna** [comment] 2018-09-20 06:56
We're investigating this issue.

**Comment by nmarjanovic** [comment] 2018-09-20 07:54
Same here and it's more then blocking issue for our team. Any updates?

**Comment by rageshkrishna** [comment] 2018-09-20 07:56
We are currently seeing API calls to BitBucket being rejected with a `401` status code.

I can confirm that we have not made any changes to the Shippable service today that would have triggered this. We are continuing to investigate why our calls are being rejected by BitBucket.

**Comment by rageshkrishna** [comment] 2018-09-20 08:05
It looks like our IP was blocked by Atlassian. We have worked around this by updating our NAT to use a new public IP address. Login with BitBucket is now working as expected.

**Comment by nmarjanovic** [comment] 2018-09-20 08:11
Nice, but all configuration and build history can't be seen any more.

**Comment by rageshkrishna** [comment] 2018-09-20 08:13
Please head over to your account profile page and sync your account.

**Comment by nmarjanovic** [comment] 2018-09-20 08:14
Did that already and got "No projects found for projectId(s): ", will try to run again.

Edit: Took some time ...but looking better, will run new build and see how things will go. Thanks.

**Comment by ramstm** [comment] 2018-09-20 08:24
I can login now...Thankyou!

**Comment by Azuka** [comment] 2018-09-20 08:25
That solved it. Thanks for the quick resolution! Do you want me to close this?

**Comment by ramstm** [comment] 2018-09-20 08:27
I think you can close it if others in thread are not seeing any issues.

**Comment by rageshkrishna** [comment] 2018-09-20 08:28
@Azuka Thank you for the confirmation. Feel free to close this issue if you are not experiencing any other problems.

@nmarjanovic I hope your sync issue is resolved. If not, please open another support issue and we'll help you out. Thanks!

**Closed as completed** 2018-09-20 08:59 UTC
