### ISSUE TITLE
Dedicated host initialization stuck in "queued" state

### ISSUE THREAD

**Issue by crania** [Shippable/support#1073] opened 2015-02-23 02:13 UTC
I've tried to get 2 dedicated hosts going but they have both been stuck in queued state for perhaps 40 minutes.  Is this common or is something stuck somewhere?  Trying to work around the space on the host filling up.

Thanks.

**Comment by manishas** [comment] 2015-02-24 00:25
We're taking a look at this... will update you when we know what's going on.

**Comment by rageshkrishna** [comment] 2015-02-24 05:51
@crania It looks like your container starts running but I see some errors around virtualenv initialization. It seems to me like your container might be missing some dependencies that we need to launch the build. Can you share your Dockerfile with me at ragesh@shippable.com? This will help me to debug the issue further. Thanks.

**Comment by crania** [comment] 2015-02-24 07:17
Just sent it over - thanks.  I'm using an AWS micro ubuntu 14.04 as the dedicated host.

**Comment by manishas** [comment] 2015-03-05 05:03
@rageshkrishna what is the update on this issue? I see builds timing out, so can we please follow up and see what's going on?

**Comment by rageshkrishna** [comment] 2015-03-07 04:05
@crania I apologize for the delay. It looks like the problem is that we need python2.7 in the image to run the build, but phusion/baseimage doesn't have this. Please install python in your Dockerfile with `apt-get install -y python2.7`. This should get your builds running to completion.

**Comment by manishas** [comment] 2015-04-03 05:18
@crania can you please try the suggestion above and let us know if it works? I am closing this issue but please feel free to re-open if the issue isn't fixed.

**Closed by manishas** 2015-04-03 05:18 UTC
Labels: bug, triaged
