### ISSUE TITLE
Build is stuck in "processing" phase without starting testing on Dedicated Host

### ISSUE THREAD

**Issue by vkuusk** [Shippable/support#1153] opened 2015-03-12 22:48 UTC
Hello, @manishas  and @avinci

this is related to ticket #1109 ( I added comment there today too)
I replaced the dedicated host and now can not run any tests. 

I just left the dedicated host in this broken state for you to take a look on your side.

Let me know if I need to delete the host and recreate the instance (currently it's Ubuntu 14.04 m3.large instance in AWS)

Thanks.

**Comment by vkuusk** [comment] 2015-03-12 22:58
Actually it took a very long time and then failed with the following message:

Downloading, [===============================>                   ] 448.3 MB/710.8 MB 47s
Downloading, [===============================>                   ] 448.9 MB/710.8 MB 47s
Downloading, [===============================>                   ] 449.4 MB/710.8 MB 47s
Downloading, [===============================>                   ] 449.9 MB/710.8 MB 47s
Downloading, [===============================>                   ] 450.5 MB/710.8 MB 47s
Downloading, [===============================>                   ]   451 MB/710.8 MB 47s
Downloading, [===============================>                   ] 451.5 MB/710.8 MB 46s
Downloading, [===============================>                   ]   452 MB/710.8 MB 46s
Downloading, [===============================>                   ] 452.6 MB/710.8 MB 46s
Downloading, [===============================>                   ] 453.1 MB/710.8 MB 46s
Downloading, [===============================>                   ] 453.6 MB/710.8 MB 46s
Downloading, [===============================>                   ] 454.2 MB/710.8 MB 46s
Downloading, [===============================>                   ] 454.7 MB/710.8 MB 46s
Downloading, [================================>                  ] 455.2 MB/710.8 MB 46s
Downloading, [================================>                  ] 455.7 MB/710.8 MB 46s
Downloading, [================================>                  ] 456.3 MB/710.8 MB 46s
Downloading, [================================>                  ] 456.8 MB/710.8 MB 45s
Downloading, [================================>                  ] 457.3 MB/710.8 MB 45s
Error downloading dependent layers, 
Error pulling image (latest) from shippable/minv2, endpoint: https://registry-1.docker.io/v1/, Untar exit status 1 write /home/shippable/.rvm/rubies/ruby-2.0.0-p598/lib/libruby.so.2.0.0: no space left on device, 
Error pulling image (latest) from shippable/minv2, Untar exit status 1 write /home/shippable/.rvm/rubies/ruby-2.0.0-p598/lib/libruby.so.2.0.0: no space left on device, 
Error pulling image (latest) from shippable/minv2, Untar exit status 1 write /home/shippable/.rvm/rubies/ruby-2.0.0-p598/lib/libruby.so.2.0.0: no space left on device: Traceback (most recent call last):
  File "/home/shippable/dpd/step_listener.py", line 99, in handle_message_callback
    self.execute_step(build_plan, current_step, False)
  File "/home/shippable/dpd/step_listener.py", line 165, in execute_step
    raise e
Exception: Error pulling image (latest) from shippable/minv2, Untar exit status 1 write /home/shippable/.rvm/rubies/ruby-2.0.0-p598/lib/libruby.so.2.0.0: no space left on device

**Comment by manishas** [comment] 2015-03-13 06:47
@vkuusk we'll take a look asap

**Comment by manishas** [comment] 2015-03-13 16:02
@vkuusk we took a look at this. Your dedicated host is running out of space because you are using our default image minv2. minv2 is a very large image (~15GB) since it contains all languages, tools, services and was designed for Travis compatibility. You should use your own custom image that is built to address your scenario.

We can help build your custom image, so please let me know if you need help.

**Comment by vkuusk** [comment] 2015-03-13 19:09
@manishas Thanks! 
I'll try a different image.

**Comment by manishas** [comment] 2015-03-29 04:49
@vkuusk did you create the custom image? let me know if you need any help with that - manisha@shippable.com

I am closing this issue but please feel free to open up another one or shoot me an email.

**Closed by manishas** 2015-03-29 04:49 UTC
Labels: bug, triaged
