### ISSUE TITLE
Build fails despite 100% test pass and console showing no errors

### ISSUE THREAD

**Issue by antonbass** [Shippable/support#1661] opened 2015-07-08 09:18 UTC
This has happened a few times now

user: max_power (via bitbucket)

<img width="1282" alt="screen shot 2015-07-08 at 11 17 03" src="https://cloud.githubusercontent.com/assets/5188810/8567105/ec10a508-2562-11e5-9a86-7c1b832be046.png">

<img width="1264" alt="screen shot 2015-07-08 at 11 18 34" src="https://cloud.githubusercontent.com/assets/5188810/8567118/09538964-2563-11e5-877c-489ff01f7481.png">

**Comment by antonbass** [comment] 2015-07-08 09:19
<img width="1264" alt="screen shot 2015-07-08 at 11 18 34" src="https://cloud.githubusercontent.com/assets/5188810/8567141/2d511606-2563-11e5-99e8-ae8e5d5d6daa.png">
<img width="1282" alt="screen shot 2015-07-08 at 11 17 03" src="https://cloud.githubusercontent.com/assets/5188810/8567142/2d6c2ca2-2563-11e5-8124-da894030bb9f.png">

**Comment by pschrammel** [comment] 2015-07-08 12:12
duplicate of #1660

**Comment by manishas** [comment] 2015-07-08 16:46
we're looking into this now, thanks!

**Comment by tekram** [comment] 2015-07-20 22:02
1+ on this. https://app.shippable.com/builds/55ad569f696c7f0b0056ef92

**Comment by tekram** [comment] 2015-07-22 18:15
Any update on this? We are still running into this issue.

https://app.shippable.com/builds/55afc123d5f6df0c00c07cc3

**Comment by manishas** [comment] 2016-03-03 00:03
we have revamped the entire build platform and this should not happen any more. Closing.

**Closed by manishas** 2016-03-03 00:03 UTC
Labels: bug
