### ISSUE TITLE
Incorrect number of skipped tests

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#2855] opened 2016-08-05 09:19 UTC
It seems like the number of skipped tests is not properly reflected in the "Tests" section of jobs.

See for example [this build](https://app.shippable.com/runs/57a457c1a353270c008b4c90/1/console) which says:

```
bin/phpunit --colors=always --log-junit shippable/testresults/junit.xml --coverage-xml shippable/codecoverage
PHPUnit 5.4.6 by Sebastian Bergmann and contributors.

...............................................................  63 / 631 (  9%)
...........................................................SS.. 126 / 631 ( 19%)
............................................................... 189 / 631 ( 29%)
............................................................... 252 / 631 ( 39%)
............................................................... 315 / 631 ( 49%)
............................................................... 378 / 631 ( 59%)
............................................................... 441 / 631 ( 69%)
............................................................... 504 / 631 ( 79%)
............................................................... 567 / 631 ( 89%)
............................................................... 630 / 631 ( 99%)
.                                                               631 / 631 (100%)

Time: 1.76 minutes, Memory: 107.50MB

OK, but incomplete, skipped, or risky tests!
Tests: 631, Assertions: 1258, Skipped: 2.
```

Still the ["Tests" page](https://app.shippable.com/runs/57a457c1a353270c008b4c90/1/tests) shows "0 Skipped".

This is a very minor issue but maybe you should have a look. ;-)

**Comment by Jan0707** [comment] 2017-12-13 09:25
We also encounter this issue, although ours seem a bit more severe (e.g. this build : https://app.shippable.com/bitbucket/lillydoo/lep-supply-toolbox/runs/1251/1/console )

In our build, we setup a custom selenium server and run various end2end tests with behat on our application. However, if for some reason (in this case, problems with docker hub) the docker orchestration fails and beat thus skips all tests (because the selenium server is not reachable) the run is still marked as success because apparently skipped tests are being ignored.

For us, this is a blocking issue: It basically takes all trust and validity away from our shippable tests, as we always have to check to console log manually to see if really everything passed as promised. This also breaks our CI / CD workflow !

Please look into this.

**Comment by rageshkrishna** [comment] 2017-12-13 09:58
Hi @Jan0707. If I've understood this correctly, behat is skipping the tests and terminating with an exit code of 0. Please correct me if I am wrong about this.

You are correct that skipped tests do not affect build status. This is currently by design as it allows the flexibility to run a subset of tests under certain conditions.

I am not familiar with behat, but is it not possible to tell it to return a non-zero exit code when something unusual like this happens? That would fail your build immediately, which is what I think you are looking for.

**Comment by Jan0707** [comment] 2017-12-13 10:59
@rageshkrishna I am currently asking the same question here ;) https://github.com/Behat/Behat/issues/1112

**Comment by rageshkrishna** [comment] 2017-12-14 09:33
@Jan0707 If behat is creating a junit file with the test results including skipped counts, we should be able to render it. Is that not working for you?

As an aside, did the suggestion of using the `--strict` flag help with controlling the exit code?

**Comment by Jan0707** [comment] 2017-12-14 12:37
The `--strict ` flag did not help. I guess that's because the actually behat command is executed from within a bash script which then ignores it's exit code. I am currently looking into the unit reports.

**Comment by mbrodala** [comment] 2017-12-14 13:15
@Jan0707 Do you mean you yourself run Behat in a bash script? In that case `command || return` should be used to let the return status "bubble up".

**Comment by manishas** [comment] 2018-08-01 18:53
@Jan0707 not sure if this is still a problem?

**Comment by rageshkrishna** [comment] 2019-01-25 06:20
I'm closing this as we haven't heard back on this. 

This appears to be a problem of behat configuration and/or the wrapper bash script not returning an appropriate exit code for us to interpret the status of the build. Feel free to re-open if you still need help with this.

**Closed by rageshkrishna** 2019-01-25 06:20 UTC
Labels: bug, need info from customer
