### ISSUE TITLE
Question:  Coverage report not appearing in the UI

### ISSUE THREAD

**Issue by behemphi** [Shippable/support#851] opened 2014-12-06 18:24 UTC
Per the example found here:

https://github.com/shippableSamples/sample_ubuntu1204_go/blob/master/shippable.yml

I created a coverage report:

```yaml
before_install:
- sudo apt-get --assume-yes install bzr
- go get github.com/t-yuki/gocover-cobertura
- go get github.com/onsi/gomega
- go get github.com/onsi/ginkgo
- go get code.google.com/p/go.tools/cmd/cover
before_script:
- mkdir -p shippable/testresults
- mkdir -p shippable/codecoverage
script:
- go test -coverprofile=coverage.txt -covermode count ./
- $GOPATH/bin/gocover-cobertura < coverage.txt > shippable/codecoverage/coverage.xml
- cat shippable/codecoverage/coverage.xml
- cat ./coverage.txt
- echo "DONE"
```

The report was created as can be seen here:

![screen shot 2014-12-06 at 12 21 50 pm](https://cloud.githubusercontent.com/assets/522972/5328432/ac18813c-7d42-11e4-9579-b0f14bf22068.png)

The XML is there as can be seen here:

![screen shot 2014-12-06 at 12 22 15 pm](https://cloud.githubusercontent.com/assets/522972/5328434/b82a72a0-7d42-11e4-8f89-ddd297f59b4f.png)

However no coverage report exists:

![screen shot 2014-12-06 at 12 24 21 pm](https://cloud.githubusercontent.com/assets/522972/5328436/d5f53982-7d42-11e4-8c61-2d5d108dc271.png)

What am I missing?

**Comment by jraska** [comment] 2015-01-27 14:49
I have exactly the same problem as @behemphi with same "success" output, but no coverage results in UI. I have Android repository with Jacoco xml coverage reports.

**Comment by manishas** [comment] 2015-02-11 05:18
@jraska we do not support Jacoco coverage reports. You will need to output the results in cobertura xml format for our parser to pick it up.

**Comment by bdehamer** [comment] 2015-02-12 00:16
Having the same issue as @behemphi

**Comment by rageshkrishna** [comment] 2015-02-12 11:21
We've confirmed that the "No coverage reports found" message is a bug. We'll deploy a fix for it soon.

However, it looks like neither `gocover-cobertura` nor `gocov-xml` are populating the `line-rate` and `branch-rate` properties in the reports they generate. These are the values we surface in the Coverage tab, which explains why it's always showing 0%.

**Comment by manishas** [comment] 2015-02-12 16:48
@behemphi we have deployed a fix for this. Please let us know if it works.

**Comment by manishas** [comment] 2015-03-04 08:29
Closing this since it was fixed. please let us know if you run into any problems.

**Closed by manishas** 2015-03-04 08:29 UTC
Labels: bug, resolved
