### ISSUE TITLE
Create two tags for each build

### ISSUE THREAD

**Issue by kastork** [Shippable/support#1176] opened 2015-03-15 23:23 UTC
There doesn't seem to be an option to specify your own tag for a docker container that is going to get pushed to docker hub.  The system always adds the tag with git_branch.build_number

Like this

```
myname/myimage:master.6
```

But what if I want it to be something like

```
myname/myimage:latest
```
 or something?

I can't find any  documentation for the `build_image` yml label that would clear this up.  Am I missing something obvious, or is there just no way for the build-master to have control over this?

**Comment by manishas** [comment] 2015-03-16 04:34
Thanks for the suggestion. You are correct, we currently add a standard tag to the container. I will add this to our list as a feature request.

**Comment by mavarazy** [comment] 2015-03-22 19:10
+1

**Comment by mikehancock** [comment] 2015-03-30 03:20
I am also looking for this feature, I would have expected the latest image pushed to docker hub to be tagged as "latest" plus any other tags I might want to specify.

**Comment by oratthumzap** [comment] 2015-04-14 19:15
+1 to able to mark the image of the latest successful build as 'latest'

btw, thanks for all of your work so far!
we really appreciate it!!!!

**Comment by ryanbaldwin** [comment] 2015-04-25 20:13
+1

Should default to "latest" unless overridden. Tagging every push with a unique tag is a touch verbose, I think.

**Comment by manishas** [comment] 2015-04-26 00:00
Couple of quick questions to everyone -
- Is this a blocker for you? Are you looking for the 'latest' tag as a convenience or does it block a workflow you're trying to set up?
- Is the request for 'latest' or is it equally important to support custom tags? Again, a description of the workflow would be super helpful.

I am writing up a blog post on our rationale behind tagging with build number, and I'd would love to know these answers so I can either address these scenarios or figure out how we can support this.

**Comment by ryanbaldwin** [comment] 2015-04-26 00:07
Typically, I consider "latest" to be unstable, and a specific tagged
version to be stable, or at the very least, a milestone. When I think of
things like continuous deployment on a dev server (or, in our case, pulling
images amongst developers on my team), where I'm always pulling the latest,
having Shippable tag each release with an auto-incrementing digit makes
this more difficult, if not outright annoying and cumbersome. The inability
to provide my own tag, however, isn't a "blocker", but *is* annoying and I
believe an oversight on Shippable's part. I should be able to tag my
production/staging releases with something meaningful to my own project.

- ryan.

**Comment by oratthumzap** [comment] 2015-04-26 07:15
we have a similar scenario as @ryanbaldwin stated.
currently we have to manually tag the images every once in a while which is VERY annoying.
i would have thought that the default implementation of the integration with docker would be to add the 'latest' tag, and that the developer would manually tag the meaningful version (and not the other way around as was implemented) :/

**Comment by ryanbaldwin** [comment] 2015-04-26 14:47
That all being said, I'd be interested in knowing why shippable applies tag names to each build. My initial reaction, though, is it's the wrong thing to do because it forces teams into a very specific way of doing things, with no recourse. 




Imagine if git tagged every one of my commits without allowing me to specify a tag or a branch, and I had to adjust shippable to pull from a specific tag with each build instead of just pulling from master (latest). That's exactly what shippable is doing to any downstream process post Docker build. 



- ryan.

**Comment by manishas** [comment] 2015-05-01 22:08
So, here is our explanation of why we tag each commit - http://blog.shippable.com/immutable-containers-with-version-tags-on-docker-hub

Needless to say, there are some things coming down the road, pretty soon, that will make our design choice obvious....but more on that later :)

**Comment by kastork** [comment] 2015-05-02 02:02
Well, it is good to have the rationale behind the choice, so thanks very much for articulating it -- it makes good sense (for many use-cases).

However, I still think it should be up to the build author to make this decision.

It isn't that I want "latest" necessarily, or even "latest" as the default; I just want some flexibility and control regarding the tag that gets pushed into the docker repository.

- One possibility that should be available is "latest", since I might always want my test environment to run whatever was committed last without having to fuss around and figure out how to run the most recent thing that was pushed into the docker repo.  If I want to promote an image that happens to carry the "latest" tag to a release according to some tagging scheme that's based on test results or other criteria (that don't run in shippable), then that's up to me and my CD process.

- Another option should be the scheme you developed, for all the reasons you point out in the post -- because that is one good and reasonable way to think about CD (esp when all the testing can be done as part of the shippable build or some CD process that you are inventing and haven't shown us yet).

- Or, I should be able to base my image's tag on something else, like maybe a git tag, or a value in the commit log, or a properties file in the repository, or the phase of the moon.

Convention over Configuration is great as long as it doesn't become Convention is the Ultimate and Unwavering Truth.

**Comment by oratthumzap** [comment] 2015-05-02 10:25
i agree with @kastork 
i think that there should be at least an option whether to use your convention or prefer the 'old world' convention which is extremely useful when using the docker image for testing

**Comment by manonthemat** [comment] 2015-05-22 21:40
Another request for build number + 'latest'

**Comment by ryanbaldwin** [comment] 2015-05-25 18:08
If there were ever a reason for supporting "latest" I discovered it today.
Over the past 2 weeks my team has made over 100 commits to Git. Shippable
created an image with a unique tag for each one of those. This has resulted
in over 100 tags in the registry.hub.docker.com. This massive amount of
tags is resulting in me being unable to

1. View that tags on registry.hub.docker.com (request times out), and
2. Pull the image with the specific tag.

This is causing me to miss a deadline and is blocking us from testing.
Colour me extremely unhappy, as if I could specify "latest" this would not
have happened.

Please fix this.

- ryan.

**Comment by manishas** [comment] 2015-05-29 05:42
@ryanbaldwin @kastork @manonthemat @oratthumzap we're going to deploy this to prod in the next day or two. Update soon. Thanks for the discussion!

**Comment by manishas** [comment] 2015-05-29 23:10
This is now available! Docs at http://docs.shippable.com/docker/

We added a field in project settings where you can enter any custom tag. If none is entered, we will use the build number as we do today.

![screen shot 2015-05-29 at 4 09 26 pm](https://cloud.githubusercontent.com/assets/2983749/7894354/3d5254f8-061d-11e5-9051-f5e6efe0049a.png)

**Comment by ryanbaldwin** [comment] 2015-05-30 15:51
So this is interesting, however is this a classic "now you have two
problems"? I mean, I have a build being triggered by a branch, and a build
triggered as master. The project settings uses "latest". I'm guessing it's
a last-in-wins kinda thing? In other words - is there no "tag name
partitioned by branch" support?

Master -> latest
Branch A -> latest_A
etc.

- ryan.

**Comment by avinci** [comment] 2015-05-30 16:32
@ryanbaldwin yup, you are absolutely right. 

The problem is with how DockerHub handles concept of repos/branches from source control. An image breaks the grain of source control. Thats the reason we used to uniqify the tag with branch.buildNumber. This can get further get complicated if you add matrix builds....

We are Shippable, do not use static tags. The moment you use it, you cannot do continuous deployment as there will be manual step involved. The push this further, we have stopped using branches on source repositories also. I fundamentally believe that if one uses branches, they will never be able to do continuous deployment.....

**Comment by marcospedreiro** [comment] 2015-06-18 21:35
Is there any way to have shippable create two tags for each build? For example, whenever there is a commit to the project, I want to create two images that are then pushed to either gcr or docker hub, 
so that one name is "latest" and the second is "buildNumber." That way the latest gets overwritten, but there is still a history of images based off of build number that the team can reference.

**Comment by rvrignaud** [comment] 2015-06-22 19:26
Hello,
I have exactly same feature request as @marcospedreiro. I moved from Docker Hub to shippable to build my docker to get the build number / git commit as docker tag but now I miss the always available latest tag for a dev environment to auto upgrade. Is there any workarround ?

**Comment by phagunbaya** [comment] 2015-06-30 20:51
+1

**Comment by manishas** [comment] 2015-07-02 22:55
I realized I never updated this thread with the new tagging features we introduced!

Please out our new tagging options -
![screen shot 2015-07-02 at 3 54 02 pm](https://cloud.githubusercontent.com/assets/2983749/8489641/a280b278-20d2-11e5-954b-dfe428bfc8f7.png)

If you want to tag with latest, you can choose custom and enter the tag name there. Does this work?

**Comment by manishas** [comment] 2015-07-02 23:03
There is one more request here that we haven't addressed, the one where you can push with 2 tags. Closing this issue as a DUP of #824 where I'm tracking all docker registry related issues.

**Closed by manishas** 2015-07-02 23:03 UTC
Labels: feature request, resolved
