### ISSUE TITLE
Is it planned to have multi container environments?

### ISSUE THREAD

**Issue by apeiniger** [Shippable/support#937] opened 2015-01-05 07:42 UTC
We are planning to also do some functional tests (e.g. test an apache inside a container) that require us to have a multiple container environment (container are linked with each other, e.g. a mysql container, ...). Is something like this planned for the future or would you rather run docker inside docker? ;)

**Comment by pmoust** [comment] 2015-01-05 13:02
I have a similar use case.

I 'd be needing docker inside docker plus `privileged` mode (need to run Solr that requires some extra kernel capabilities).

Any ETA on such features?

**Comment by manishas** [comment] 2015-01-05 21:58
@apeiniger @pmoust yes, this is most definitely something we plan to address very soon. Watch for some announcements in the next week or two.

**Comment by manishas** [comment] 2015-01-06 19:32
Closing as a duplicate of #864 We will follow up in that thread about multi-container environments.

**Closed by manishas** 2015-01-06 19:32 UTC
Labels: feature request, triaged
