### ISSUE TITLE
Provision job node takes long time (>5min)

### ISSUE THREAD

**Issue by roman-gliffy** [Shippable/support#2738] opened 2016-06-23 16:45 UTC
Hi,

How long does it take to provision a node for an account with a subscription?

```
Provision job node
  Info  
Provisioning a node for subscriptionId: 
```

Takes >5 minutes or longer, I'm still waiting.

**Comment by abhijitkini** [comment] 2016-06-23 17:04
We are working on fixing the issue. We'll have an update soon. Check http://status.shippable.com/ for the latest status.

**Comment by roman-gliffy** [comment] 2016-06-23 18:05
The status page says it's been resolved, but nodes are still not provisioned.
Could you clarify if things are back to normal?

**Comment by abhijitkini** [comment] 2016-06-23 18:08
@roman-gliffy Yes, things are back to normal. Can you provide a link to your build?

**Comment by roman-gliffy** [comment] 2016-06-23 18:10
https://app.shippable.com/runs/576c2493c6aa160c00590077

**Comment by abhijitkini** [comment] 2016-06-23 18:18
@roman-gliffy the nodes for your build just got provisioned.

**Comment by roman-gliffy** [comment] 2016-06-23 18:25
Yes, the build run. 
But now page is not rendered :(

**Comment by abhijitkini** [comment] 2016-06-23 18:32
We know the issue is being caused by MongoDb and are working to fix it. Stay tuned.

**Comment by fedenusy** [comment] 2016-06-23 18:38
My nodes are still not getting provisioned 😢 

https://app.shippable.com/runs/576c2bcc561e0a0c007082e0

**Comment by fedenusy** [comment] 2016-06-23 18:41
There we go, just took a while 👍

**Comment by abhijitkini** [comment] 2016-06-23 20:35
The job nodes have been provisioning normally for the last 2 hours, since we have deployed the fix. Closing as resolved. Do let us know if you see any delay.

**Closed by abhijitkini** 2016-06-23 20:35 UTC
Labels: bug-SOS, resolved
