### ISSUE TITLE
Environment not updating to reflect shippable.resources.yml

### ISSUE THREAD

**Issue by npahucki** [Shippable/support#3814] opened 2017-09-05 16:55 UTC
Ref: https://app.shippable.com/subs/github/ExecThread/resources/develop-gateway-env/versions

Changing the the env vars in the `secure` section does not use the new version: 
We had added a new env var and it was not showing up in ECS TaskDef...when I looked in the SPOG at the develop-gateway-env, I could see that the env had not been updated since last Wednesday despite many CI and deploy cycles since then. I clicked the Update link for the develop-gateway-env element, and put in the text that is in the secure section of the develop-gateway-env params section and then the env var was added to the ECS task as expected. Why is this not happening automatically based on the data in the shippable.resources.yml?

Here is the relevant section of the shippable.resources.yml: 

```
 - name: develop-gateway-env
    type: params
    version:
      params:
        PORT: 3000
        REDIS_URL: redis//dev...............:6379
        secure: nvZo.......................==
 ```

**Comment by trriplejay** [comment] 2017-09-05 17:12
rSync only runs when it detects a change in one of the shippable pipeline config files.  When this ran last Wednesday, was this params change already made? or has it been made since then, and rSync never ran to perform the update?

**Comment by npahucki** [comment] 2017-09-05 19:00
We changed the shippable.resources.yml several times trying to figure out what was going on, it did not trigger on any of the changes to this file, which I believe is a pipeline config file.

**Comment by trriplejay** [comment] 2017-09-07 17:16
yes, changing that file definitely should have resulted in rSync running and detecting the changed resource. It looks like it didn't even run... 

Are there any errors shown in your github webhooks list for this syncRepo? Was the change made to the correct branch that was added as a syncRepo? other branches would be ignored.  

If you make a new commit with a change to the resources yml, does rSync run? Could you try this and let us know? it will be easier to pinpoint the logs if we know the approximate time when the ignored commit was made.

**Comment by npahucki** [comment] 2017-09-08 10:29
It was made to the correct branch for sure. 

This has also happened with an env var in another repo just today (at https://app.shippable.com/subs/github/ExecThread/dashboard). Committing changes to resources.shippable.yml does not trigger rSync (this is the whole problem).

In this repo, I added a a simple env var to the params in the resources file:
```LISTINGS_EMAIL_BATCH_SIZE: "10"```

According to github the web hook was trigger many times after that addition (assuming I am looking at the right one (`https://ExecThread:XXXXXXXXXXXX@api.shippable.com/v2/resources/1903/hook/`). Below I have listed the last several invocations with times. There was only one error of all these at `2017-09-07 18:19:48` which says the service timed out. Yet, the task definition in AWS STILL does not include the env var, and in the SPOG, examining the resource it does not include the new env var. 

The commit that SHOULD have triggered the env rebuild is `bc0f28ae19763e15a906aff58bd6a0f7c3a59abd` which happened at `2017-09-07 17:53:40 -0300` 

*** PLEASE NOTE: Times are shown in UTC -3:00!
```
  00a092e0-9432-11e7-8ca9-74f65da47cc7 … 2017-09-07 22:06:53
  72ebe13e-9431-11e7-9ff4-8f63807609bc … 2017-09-07 22:02:56
  9b4d8454-9425-11e7-887c-fe7e7c6cbbd0 … 2017-09-07 20:38:09
  9b3184de-9425-11e7-9bab-5766593b4081 … 2017-09-07 20:38:09
  5043cf3e-941d-11e7-9bfe-aa4e4f0637f6 … 2017-09-07 19:38:47
  90ee06d4-9419-11e7-8f95-bdf6f27ed7f8 … 2017-09-07 19:11:58
  333a6c12-9419-11e7-9e44-ecb64b61a431 … 2017-09-07 19:09:21
  31227000-9419-11e7-9985-255e1f4f865f … 2017-09-07 19:09:17
  3104c960-9419-11e7-8061-1174b407e8b0 … 2017-09-07 19:09:17
  475b56e0-9412-11e7-9bff-2ca275112869 … 2017-09-07 18:19:48
  46d86e06-9412-11e7-8cea-59c9901718e2 … 2017-09-07 18:19:47
  d1b40400-9411-11e7-9233-7525737b66c7 … 2017-09-07 18:16:31
  96cd0b90-940f-11e7-9ebd-51dd90d6ca19 … 2017-09-07 18:00:33
  966c1eca-940f-11e7-9dad-862474d5b03e … 2017-09-07 18:00:32
  1fd12530-940f-11e7-8465-a2a2507f0d67 … 2017-09-07 17:57:13
  17921780-940f-11e7-874d-5fa68633a24a … 2017-09-07 17:56:59
  17828720-940f-11e7-9b25-cc86a6ea4318 … 2017-09-07 17:56:59
  03b74c76-940f-11e7-80e4-1a28c9957b35 … 2017-09-07 17:56:26
  a3916fc0-940e-11e7-8a87-09c7fb1608ca … 2017-09-07 17:53:45
  a1400236-940e-11e7-8365-fd3580faa10b … 2017-09-07 17:53:41  
```

**Comment by trriplejay** [comment] 2017-09-08 22:10
thanks for all the data. We're still investigating but haven't found any root cause so far.  

Typically what happens, is that when a commit webhook comes in for a syncRepo, before triggering rSync we check to see if any of the shippable config files have changed.  we do this by using a github api call that returns a list of changed files in the commit.  If a shippable config file (resources, jobs, triggers) is found in the commit, we will trigger the rSync job associated with the repo. This way rSync only runs when pipelines are changed, instead of for every commit (which could very well be source code unrelated to pipeline config)

So, the fact that rSync doesnt even run seems to imply that we're not at all seeing that the file has changed, but that is information that we get straight from github.

Your rSync job ran as recently as this past Tuesday, so there have been no changes on shippable itself since then.. I'm struggling to think of a reason why this would suddenly stop working.

one more piece of info... could you email me the body of the github webhook that was sent as a result of the commit that modified the params resource? john@shippable.com

**Comment by npahucki** [comment] 2017-09-11 13:30
I sent you an email with the hook request/response from one I did this morning. Note this is for https://app.shippable.com/subs/github/ExecThread/resources/develop-gateway-env/versions

**Comment by stephenakcegroup** [comment] 2017-10-06 11:43
We have noticed the same issue on our end. One of our gitRepo resources was changed but this is not being reflected in the environment

**Comment by stephenakcegroup** [comment] 2017-10-06 14:53
We managed to fix this issue by removing the sync resource and re-creating it

**Comment by manishas** [comment] 2017-10-11 02:18
@trriplejay are we still looking into this? can you update with status and close if needed?

**Comment by trriplejay** [comment] 2017-10-11 07:52
via email, npahucki's issue seems resolved for now, though we were never able to figure out the root cause of his initial issue. I think we should close this for now until it comes up again and we can get more data.

**Closed by trriplejay** 2017-10-11 07:52 UTC
Labels: investigate

**Comment by yulianovdey** [comment] 2018-02-16 00:55
It looks like this issue persists for us. Changing any params, even outside of `secure`, doesn't seem to update the actual environment for the app. In addition, switching to the beta spog view removed the `Update` button that was present before and allowed us to manually update vars. If I inspect the resource [here](https://app.shippable.com/subs/github/ExecThread/resources/develop-admin-app-env/versions):

- there is a YML section at the top of the page with outdated params.
- the latest version in the breakdown below the YML section has the latest params I updated the resource to *before* switching to the beta spog view.
- the latest version in the breakdown still doesn't reflect `shippable.resources.yml`

Let us know how we can help troubleshoot this.

**Comment by a-murphy** [comment] 2018-02-16 01:11
It doesn't look like the rSync job for that resource has run since May, which would explain why none of the updates have appeared.  The rSync job is responsible for updating the resources when the YML files are updated.  Does your GitHub repository still have a webhook for rSync?  It should be `/resources/:resourceId/hook`.
