### ISSUE TITLE
requirement error

### ISSUE THREAD

**Issue by musicformellons** [Shippable/support#1282] opened 2015-04-07 10:05 UTC
I get this error below when building an exact copy of "succesful build" of this repo:
https://github.com/ninuxorg/nodeshot

The requirement is DRF 2.4.4 ; where does the DRF==3.1.1 come from which causes the conflict?

Installed /home/shippable/build_ve/python/2.7/lib/python2.7/site-packages/nodeshot-1.0.pre_alpha-py2.7.egg
Processing dependencies for nodeshot==1.0.pre-alpha
error: Installed distribution djangorestframework 2.4.4 conflicts with requirement djangorestframework==3.1.1

**Comment by rageshkrishna** [comment] 2015-04-07 11:18
Hi @musicformellons. I tried to reproduce this error by forking https://github.com/ninuxorg/nodeshot and running a build, but it seems to have gone through the installation without any issues. I did run in to another error with pip on my first try, which was resolved by adding `pip install -U pip` as a `before_install` step, but my build did not throw any conflict errors for djangorestframework in subsequent runs.

Did you add or change requirements.txt in your project? I'm guessing that some other requirement is introducing a dependency on DRF 3.1.1.

Can you share your requirements.txt file? You can paste the contents here, or email me at ragesh@shippable.com. Thanks!

**Comment by manishas** [comment] 2015-04-10 21:59
@musicformellons closing this issue due to lack of response. Please feel free to re-open if you want us to look into this.

Thanks!

**Closed by manishas** 2015-04-10 21:59 UTC
Labels: bug, triaged
