### ISSUE TITLE
Frequently hanging at "Running a job on customer's build node"

### ISSUE THREAD

**Issue by ryan-kimber** [Shippable/support#2857] opened 2016-08-05 15:16 UTC
### Frequently hanging at "Running a job on customer's build node...":

We're running a Vanilla Ubuntu 14.04 on a  Google Container Engine box.
When I go check the [Subscription Settings -> Nodes](https://app.shippable.com/subscriptions/56f007bc9d043da07bf12062/settings/nodes/57a381ded640fc0d00f88a37) panel, the node shows green and 'inactive'.

If I go to Subscription Settings -> Nodes, and reset the node, the node will work again, and our builds resume.

**Comment by ryan-kimber** [comment] 2016-08-06 16:49
![screen shot 2016-08-06 at 12 48 16 pm](https://cloud.githubusercontent.com/assets/1018189/17458006/2af5e60e-5bd4-11e6-8a8f-a17df0f4fa15.png)

**Comment by kanthchandra** [comment] 2016-08-06 16:57
Hi @ryan-kimber, sorry about this. We need some more data to debug this. Can you please email me the logs of shippable agent `mexec` running on the host? You can do `docker ps -a | grep mexec` and then `docker logs --tail=1000 -f mexec-container-id` and send us the output of the logs?

**Comment by ryan-kimber** [comment] 2016-08-06 18:35
I've sent an e-mail over to you.

It looks like, when this happens, docker is no longer running. Is there something I can run that will show why/when docker stopped?

**Comment by ryan-kimber** [comment] 2016-08-06 18:43
Argh. My user wasn't in the docker group. I'll re-run these once it fails again.

**Comment by kanthchandra** [comment] 2016-08-10 11:15
Hi @ryan-kimber I looked at the logs that you had emailed me, but I couldn't really come to any conclusion as to what the cause could me. Some more information would help us debug this better.
1. Does this happen very often and reproducible consistently?
2. Had you reset your subscription when this happened? Because if the subscription is reset we change a couple keys and it could result in the existing node becoming invalid and when you reset the node, the node will have the new keys and it'll work again.
3. Since the previous logs we inconclusive, can you please run this command `docker logs mexec-container-id >> mexec.log 2>&1` and send us the mexec.log file?

**Comment by ryan-kimber** [comment] 2016-08-18 01:41
Hi,

I'm sorry I haven't responded to this - I've been tied up with
non-technical work.
I am back working on this tomorrow and will provide an update and run the
commands you've provided.

Thanks,
Ryan.

**Comment by ryan-kimber** [comment] 2016-08-23 22:42
Hi there,

I'm finally back working on this and still having the builds timeout pretty
regularly. It's certainly not every time, but maybe a 1/3 of the time. Once
it happens, resetting the configuration for the build node seems to be the
only thing that fixes it.

We had not reset our subscription.

It's currently sitting waiting to build one of our images: "Running job on
customer's build node for subscriptionId: 56f007bc9d043da07bf12062"

We have two build nodes, so I'm not sure which one this is happening on, so
I'll give you the outputs from both.

For the command docker ps -a | grep mexec on node 1:

1d8514c59451 shipimg/mexec:master.152 "/home/shippable/mexe" 2 weeks ago Up
31 minutes shippable-mexec-57a381ded640fc0d00f88a37


For the command docker ps -a | grep mexec on node 2:

7e3d00cc2897 shipimg/mexec:master.152 "/home/shippable/mexe" 2 weeks ago Up
25 minutes shippable-mexec-57a60cddd640fc0d00f93ff7



I've attached the mexec.log file for each node.

I hope that provides more detail.

I'm going re-install (again) the Shippable components on the nodes so my
builds will resume.

**Comment by ryan-kimber** [comment] 2016-08-25 20:54
Still happening today after the latest shippable release.

**Comment by ryan-kimber** [comment] 2016-09-10 23:09
We're still having this problem.

Can we set something of so that you can take a look while the problem is actively occurring. It seems to be something that can be reproduced with just a few tries.

**Comment by ryan-kimber** [comment] 2016-09-10 23:15
It also looks like it may say 'no consoles found' when I first start a reset when the node gets stuck. Interestingly, even when it does say 'no consoles found', the reset will proceed and re-install the shippable components.

**Comment by ryan-kimber** [comment] 2016-09-10 23:49
![screen shot 2016-09-10 at 7 48 16 pm](https://cloud.githubusercontent.com/assets/1018189/18414276/b7a01f94-778f-11e6-814a-0c22407f1138.png)
![screen shot 2016-09-10 at 7 48 51 pm](https://cloud.githubusercontent.com/assets/1018189/18414277/ba1ce824-778f-11e6-882c-57600736b3b1.png)

**Comment by kanthchandra** [comment] 2016-09-12 05:15
Hi @ryan-kimber I'm sorry that there was a delay in addressing your concern here. I looked at your email with the logs but I couldn't find anything in the logs which could have caused this and also since there was no communication for some time I assumed the problem was resolved.

Coming to the `no consoles found` issue, we first delete the old consoles when you reset the node and then start with a fresh initialization. So you are seeing that console log and it should not cause any issues.

So can you let me know when this happens again without resetting the node and I will look into this. I will be available in the IST time zone. Thanks for your patience.

**Comment by ryan-kimber** [comment] 2016-09-12 05:18
This happens nearly every other build, probably 40% of the time, so it
should be easy to trigger whenever someone is ready to take a look.

**Comment by kanthchandra** [comment] 2016-09-12 05:22
We are ready when you are :) I should be able to look at this now, I'm not sure which time zone you are in, so please let us know a suitable time. Thanks

**Comment by ryan-kimber** [comment] 2016-09-12 11:59
Hi Chandra,

Sorry last night didn't work out, but we're on Eastern (North America)
time. I'm up and working now, and will be around for most of the next 12
hours (with a two-hour break in the middle).

Please let me know when you are back around.

Thanks,
Ryan.

**Comment by kanthchandra** [comment] 2016-09-12 12:29
Hi @ryan-kimber, 

I'll be around for the next 2 hours or so. Let me know if you run into this.

**Comment by ryan-kimber** [comment] 2016-09-12 13:52
Alright - looks like it's happening right now.

**Comment by kanthchandra** [comment] 2016-09-12 13:53
OK, I'm looking into it right now and try to communicate on this channel.

**Comment by ryan-kimber** [comment] 2016-09-12 14:13
Hi Chandra,

Have you been able to get into our node? Just checking in. Not to rush you,
but just so you are aware; on my end, I'm waiting until you're done.

Thanks,

Ryan.

**Comment by kanthchandra** [comment] 2016-09-12 14:16
There are a couple of things that I'm verifying before looking into the logs. I'll let you know my findings in some time.

**Comment by ryan-kimber** [comment] 2016-09-12 14:19
Thanks.

**Comment by ryan-kimber** [comment] 2016-09-12 14:27
Not sure if you did anything to cause it, but after a 36 minute wait, the
build started going...

**Comment by ryan-kimber** [comment] 2016-09-12 14:28
Went from "running job on customers build node for subscription Id:
56f007bc9d043da07bf12062

...to 'Job node info' and then the build went ahead normally.

**Comment by kanthchandra** [comment] 2016-09-12 14:43
Hi @ryan-kimber I'm marking this as a bug, It looks like the build agents (shipimg/mexec:master.3859) which were running on the node received the messaged but were stuck without doing anything. I manually restarted the build agents (sudo docker restart `mexec_container_id`) and they started processing the message. I'm still not sure why they were stuck yet, I'll try to repro this at my end and I'll let you know when the fix is available.

In case this happens again (only if the build is stuck at `running job on customers build node for subscription Id: 56f007bc9d043da07bf12062`) you can manually restart the build agent. You will know which agent to restart by looking at the nodes in your subscription settings. You can restart agent on the node which is not in processing start. Sorry about this, we will get back to you at the earliest on this one.

**Comment by ryan-kimber** [comment] 2016-09-12 14:52
Thanks Chandra. Hopefully you'll have an easy time reproducing it. It
happens almost half the time we do a push, but only when I have custom
nodes configured (which, of course, we've done to make things run faster).

When it works right, this cuts our build time by about two-thirds, which is
great. When it gets stuck, not so great.

You mentioned that under subscription settings, I should be able to see
which is stuck, but they always show inactive when we get into this stuck
state (see the image below).[image: Inline image 1]

What I've been doing is resetting both of the nodes under subscription
settings. Is there something that would be better/faster to do?

Thanks,
Ryan.

**Comment by ryan-kimber** [comment] 2016-09-12 15:05
Our nodes are vanilla ubuntu 14.04 using the standard Google Compute Engine
image, with 1 CPU, 3.75GB of memory and 100GB of disk.

**Comment by kanthchandra** [comment] 2016-09-12 15:22
Our standard build nodes that we use on shippable hosted are 2 cores, 3.75 GB RAM each and around 150 GB storage (because we store all the shippable images).

Our build agents use 2 threads and your machine has 1 core, could that be the problem because we haven't see this happen frequently? Anyway I will get back to you with more details on this tomorrow and I'll also try to repro this by using the same configuration as you are using.

**Comment by ryan-kimber** [comment] 2016-09-12 16:07
Thanks.

Have there been any other changes? My builds are just queueing now and not
running at all.

**Comment by ryan-kimber** [comment] 2016-09-13 00:52
If two threads can't run happily on a single core machine, I would thing that's a bug. 

To work around this, I'll try up'ing my nodes to 2 core and 7.5GB or RAM. Hopefully that will work.

It would be really great though, if we could get this working properly on a 1-core 3.75GB node (having 2 larger nodes will add $78/month to our costs).

**Comment by manishas** [comment] 2016-09-13 01:02
@ryan-kimber out of curiosity, why did you decide to continue with using your own nodes? I thought you were going to switch to Shippable nodes after our conversation.

**Comment by ryan-kimber** [comment] 2016-09-13 01:15
We're getting build times of 2-4 minutes on our own nodes, but 8-14 minutes on Shippable nodes.  
As I'm working through getting our deployment pipeline working with our different projects and environments, I'm doing a lot of config changes, deploy, test, edit config, deploy, tests cycles. The extra time has been a real drag on what I'm able to get done in a day.

**Comment by ryan-kimber** [comment] 2016-09-13 13:16
Despite moving to 2 CPUs and more memory, we are still having the same issue.  =(

**Comment by kanthchandra** [comment] 2016-09-13 16:07
Hi @ryan-kimber , Resetting the node for every single build seems like a bad experience and I'm sorry for that.

We too tried to reproduce this at our end by spinning up machines on gcp and on aws. I used ubuntu 64 bit, 1 CPU, 3.75 GB RAM with 100 GB HDD. The machine was spin up on US US-Central-1B on gcp and virginia on AWS. We had no luck in reproducing the issue.

Are you using any firewall or set some rules on TCP connections? 

Are you using these machines for some other purposes other than running CI?

**Comment by ryan-kimber** [comment] 2016-09-13 19:12
No special firewall rules - just the default SSH rule on the default
network. I'm on US-Central-1a, but was using US-West-1 and had the same
issue.

These are vanilla machines only being used for Shippable. In fact, the only
commands that have been run on them are the setup commands from the
Shippable control panel.

**Comment by kanthchandra** [comment] 2016-09-14 04:57
Hi @ryan-kimber is it ok if I trigger a few builds on your behalf to debug this and see whats going on? I can't seem to repro this at my end.

**Comment by ryan-kimber** [comment] 2016-09-14 12:02
No problem.

**Comment by kanthchandra** [comment] 2016-09-21 15:06
Hi @ryan-kimber , First of all I apologize for the delay in getting back to you on this. 

I have been able to successfully reproduce this on a GCP machine.

Our infrastructure is set in such was that the build runner on the node is listening to a message broker which is behind an ELB and the ELB has a connection timeout 1 hour. So if there is no communication between the build runner and the message broker for an hour the ELB drops the connection.

Now the message broker client in our build runner will detect that the connection has dropped and it will initiate the restart of our build runner so that it resets a few things and we are able to connect to the message broker back.

Now this is the ideal case that I have described above and that's how it's working on machines spun up on AWS and Digital Ocean, however on GCP the message broker client is unable to detect any connection drops (which I haven't yet figured out why). So the connections are being dropped silently and our build runners are not able to recognize it to take any corrective action and as a result the messages are not being delivered and the builds get stuck.

For the time being to unblock you I have patched the build runners that is running on both the nodes manually. So you should not run into this problem again. I'll open an internal issue to discuss the solution for this problem. Thanks for your patience.

Please do let me know if the patch works for you.

**Comment by ryan-kimber** [comment] 2016-09-22 15:54
Thank you. So far, so good. I'll let you know if I encounter any issues.

**Comment by kanthchandra** [comment] 2016-09-22 15:56
BTW we found the reason why this was happening only on GCP nodes and not on other providers. :) We are working on a fix for this and it should be available in a day or two.

https://cloud.google.com/compute/docs/networks-and-firewalls

> Note: All instances are configured with a "hidden" firewall rule that drops TCP connections after 10 minutes of inactivity. If this timeout causes connectivity errors to or from your instance, you should configure TCP keep-alives to prevent connections from being dropped. See the tips and troubleshooting page for details.

**Comment by kanthchandra** [comment] 2016-09-26 05:24
Hi @ryan-kimber, this has been fixed and deployed to production, If you reset your node, you should not run into this problem again.

**Comment by kanthchandra** [comment] 2016-10-03 12:49
Closing this issue since our fixes are deployed and builds are running on your nodes. Let us know if you still run into this.

**Closed by kanthchandra** 2016-10-03 12:49 UTC
Labels: bug, core, resolved
