### ISSUE TITLE
Hub login failed

### ISSUE THREAD

**Issue by LBates2000** [Shippable/support#3725] opened 2017-07-19 23:11 UTC
Our AWS shippable instances are failing to log on to our docker private registry 'docker.infospace.com' with a 401 Authentication error. 

_Hub login failed  
Docker login failed for username jet and email teamcloudops@infospace.com_

I've verified that I can log on to the docker registry using the same username and password that we have configured in our Shippable Account Integration 'InfoSpace Private Registry'.

I've also confirmed that the shippable instances can connect to docker.infospace.com on ports 443 (redirected via ELB to port 5002) and 5001.

Example of a build failure:

https://app.shippable.com/github/Openmail/cloudos.infospace.com/runs/782/summary/console

Thanks.

Lawrence Bates
Lawrence.Bates@system1.com

**Comment by rageshkrishna** [comment] 2017-07-20 03:36
@LBates2000 Do your docker credentials have any special characters (quotes, backslashes, etc.)? We have seen incidents in the past where this has caused problems. Some of those issues have been addressed in previous updates, so I'd like to double check if this might still be a problem. Thanks!

**Comment by LBates2000** [comment] 2017-07-20 16:43
No, the username and password used in the credentials do not make use of any special characters. Turns out we use https://github.com/cesanta/docker_auth for authentication, so we're looking into that.

**Comment by rageshkrishna** [comment] 2017-08-04 09:29
@LBates2000 Sorry about the late follow up on this. I see that your builds are succeeding now, so I gather you got the registry authentication working. Please let me know if this isn't the case. Thanks.

**Closed by rageshkrishna** 2017-08-04 09:29 UTC
Labels: bug, investigate, need info from customer

**Comment by kuboosoft** [comment] 2019-12-06 00:54
The issue is present again. :(

```
  hub_login
  echo 'Hub login failed'
Hub login failed
  cat /tmp/hub_login_out
  echo 'Docker login failed for username davidva and email #####@gmail.com'
Docker login failed for username davidva and email #####@gmail.com
  rm /tmp/hub_login_out
```

**Comment by a-murphy** [comment] 2019-12-06 01:04
@kuboosoft 

Docker login failures are usually caused by an incorrect password in the integration.  If an integration previously worked, the most common cause of the failure is a Docker password that was changed without updating the integration.  If you are still unable to log in to Docker Hub after updating the integration to a password confirmed to work locally, please open a new issue.
