### ISSUE TITLE
Pushing to Docker Hub failing login

### ISSUE THREAD

**Issue by asans** [Shippable/support#4747] opened 2019-02-13 16:43 UTC
### Description of your issue:
Beginning yesterday, docker login stopped working and our builds are not able to be pushed to Docker Hub.

shippable.yml hasn't changed.  credentials haven't changed (logged into docker directly without problem).  Based on the error from build 283, it looks like something changed on Shippable side.

https://app.shippable.com/github/virtualpost/vps-alice/runs/283/1/console
https://app.shippable.com/github/virtualpost/vps-alice/runs/285/1/console

Please investigate.

**Comment by a-murphy** [comment] 2019-02-13 18:21
The first error is a duplicate of #4742, which was resolved yesterday.

The second error is consistent with incorrect credentials.  Could you double-check that you are using the same Docker Hub username to connect to Docker Hub and that the password for that username has not changed?  If it still doesn't work, you may want to [update your subscription to a newer machine image](http://docs.shippable.com/platform/runtime/machine-image/ami-overview/#changing-the-node-pool-machine-image) to use newer default images for the projects in your subscription.  The image that your project is currently using has Docker 1.9 installed.  The versions of Docker available on the newer images are listed [here](http://docs.shippable.com/platform/runtime/machine-image/cli-versions/#docker).

**Comment by rageshkrishna** [comment] 2019-03-01 05:44
@asans It looks like your problem is resolved, so I'm going to close this issue. Feel free to re-open if you still need help.

**Closed as completed by rageshkrishna** 2019-03-01 05:44 UTC
