### ISSUE TITLE
bitbucket pull requests: not displaying the buid status on the PR page

### ISSUE THREAD

**Issue by piyush-kurur** [Shippable/support#2917] opened 2016-08-28 14:42 UTC
Shippable is building PRs fine but the PR page does not show the build status of the PR

See the PR page at https://bitbucket.org/naksha/naksha/pull-requests/

**Comment by piyush-kurur** [comment] 2016-08-31 04:06
By the way is it okey that I merge this pull request? Currently there is no one other than me working on this and I can leave it open so that you can test it out.

**Comment by piyush-kurur** [comment] 2016-09-03 13:10
@manishas what is the time like for this feature request? I am sure other bitbucket users would be interested.

**Comment by tzar** [comment] 2016-12-14 04:55
Is there any progress on this? Running into the same problem

**Comment by manishas** [comment] 2016-12-14 05:02
@tzar we will need to look into this. This issue wasn't updated correctly, but we implemented this a couple of months ago. I will ask someone to dig in deeper.

**Comment by tzar** [comment] 2016-12-14 05:19
Thanks - we're seeing build status on merged pull requests, but not open ones. Master + forks all private and set up with the same deployment key. Builds are occurring correctly and notifying via email/slack, just no luck on bitbucket ☺

**Comment by piyush-kurur** [comment] 2016-12-14 08:54
I can confirm to what tzar is saying. Build status is shown on merged changes and not on yet to merge changes.

**Comment by avinci** [comment] 2017-02-28 11:56
We have opened another issue to make sure this si done correct. It will be done shortly.

**Comment by avinci** [comment] 2017-02-28 11:57
We have opened another issue to make sure this si done correct. It will be done shortly.

**Comment by piyush-kurur** [comment] 2017-03-01 18:46
@avinci thanks.

**Comment by avinci** [comment] 2017-03-02 12:47
@piyush-kurur we are not able to reproduce this. Can you try this let me know if the problem still persists.

**Comment by piyush-kurur** [comment] 2017-03-02 13:11
Sorry, I had migrated the repository to github but the pull request still stand. Here is the shipit build which you can see clearly failed.

https://app.shippable.com/runs/58075f4e6f3917100091bd13/summary

And here is the page of pull request 
https://bitbucket.org/naksha/naksha/pull-requests/

You can see that the field Build does not show whether the shipit build for the pull request failed or not.
Just to help you with debugging this issue. I want to clarify one thing I did which might
have been problematic. I started the repo under my name and the transfered it to group
naksha. Shipit automatically handled this change correctly  (if I remember correctly)
in the sense that the builds were happening on naksha instead of my private clone.

**Comment by piyush-kurur** [comment] 2017-03-02 13:15
Here is the case of a successfully merged build

https://app.shippable.com/runs/57ca7d1aeab2150f003d10e0/summary

https://bitbucket.org/naksha/naksha/pull-requests/?state=MERGED

Notice that the merged pull request shows the build status.

**Comment by avinci** [comment] 2017-03-08 16:26
@piyush-kurur this was fixed. Please let us know if this is still not working. The links are old builds and the issue was fixed after....

**Closed by avinci** 2017-03-08 16:26 UTC
Labels: bug, in progress

**Comment by garth-wells** [comment] 2017-06-17 16:41
This doesn't seem to fixed. The status is not shown against the PR at <https://bitbucket.org/fenics-project/ffc/pull-requests/74>.

Here's the run of the PR on Shippable: <https://app.shippable.com/bitbucket/fenics-project/ffc/runs/13/summary>.
