### ISSUE TITLE
Cannot add dedicated host

### ISSUE THREAD

**Issue by txchen** [Shippable/support#1140] opened 2015-03-09 20:28 UTC
Follow the UI and failed to init:
```
Writing key to file
mode of '/tmp/4d7846a1-f20f-449b-adef-bc26c0392b7f.rsa' changed from 0644 (rw-r--r--) to 0600 (rw-------)
KEY file created: /tmp/4d7846a1-f20f-449b-adef-bc26c0392b7f.rsa
Writing script to file
Script file created: /tmp/4d7846a1-f20f-449b-adef-bc26c0392b7f.sh
Warning: Permanently added '54.187.151.233' (ECDSA) to the list of known hosts. Permission denied (publickey). rsync: connection unexpectedly closed (0 bytes received so far) [sender] rsync error: unexplained error (code 255) at io.c(226) [sender=3.1.0]
```

How should I debug?
BTW, is there another channel for support other than github issues?

**Comment by manishas** [comment] 2015-03-09 20:43
@txchen before you clicked on 'save' while adding the host, did you run the command that starts with sudo useradd -d on your host? The error you're seeing happens when the command isn't run on the host, so we don't have permission to write to it. Let me know if you need more clarification.

**Comment by txchen** [comment] 2015-03-09 21:03
@manishas yes, of course, I have added shippable user. How do I debug this? As I don't have the private ssh key to test if ssh can actually work.

**Comment by ragsden** [comment] 2015-03-09 21:15
@txchen : I'm getting permission denied error when I'm trying to ssh into your machine. Can you please verify again and let me know? Thanks.

**Comment by txchen** [comment] 2015-03-09 21:32
@ragsden Actually my question is how should I verify it?
As I said, I don't have the private key so I could not verify the ssh. What should I check?

```
/home/shippable/.ssh
> cat authorized_keys
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3BfEoZg5TbFajhJZJlRXONVGAi+seTyZJ28MCUZ5qn5sBV7ex8eHVVDz+OyBROULYG6jscvPQdVBI3A+/uHi3ha9xqSFoLeMxaMRSg8SxWGQD0A0UfjwW9J5qCnYljDvbd6/4yT7DkZsgBPNMW5j8aSIjQZ7xYdpVPBSuheu/sIY1H9bXxjXI2xQpACxgfdmCO+FtWo2yMhBnBcvyTQcclSBeQAOKZZIiEy07ESk2lONMsnoBGrnGlqxYrD8Y0ugkiDfS/rY12ysdmQGElDz2R0wXCMII5tXkJIprVQU+h2IgnsYtJKkBuDckHYXl1ozJGLggxOa+a2VQGhiz7DMD 54b6d00a4051091100debf62
```

**Comment by ragsden** [comment] 2015-03-09 21:55
my email is raghu@shippable.com
Please send me your email and I can give you the private key

**Comment by ragsden** [comment] 2015-03-10 17:58
@txchen Thank your for your patience. The issue is now fixed and I'm closing this issue

**Closed by ragsden** 2015-03-10 17:58 UTC
Labels: question, triaged

**Comment by n0mer** [comment] 2015-11-07 00:26
@ragsden can you please follow-up on what was the problem and how did you fix it?

i'm having the same

**Comment by manishas** [comment] 2015-11-07 00:40
@n0mer can you please open a new issue and describe the problem you're running into?

**Comment by n0mer** [comment] 2015-11-07 02:10
@manishas in the spirit of http://www.catb.org/esr/faqs/smart-questions.html i'm sharing my feedback.

i built custom docker image, that includes /root/.ssh/id_rsa

shippable seems to overwrite /root folder with /root/workspace (i suppose this is docker volume container), so my id_rsa key was overwritten

i fixed the problem my putting id_rsa to /opt/ssh folder and then using rsync -e 'ssh -i /opt/ssh/id_rsa' ...
