### ISSUE TITLE
Branches to be displayed

### ISSUE THREAD

**Issue by navymaker** [Shippable/support#3301] opened 2017-01-19 14:47 UTC
Hi,
I have some issues setting Branches to be displayed on Dashboard/CI page, it resetting continuously after my modifications. Other settings such as "Configure Webhook Events for Triggering Builds" works as expected.

**Comment by a-murphy** [comment] 2017-01-19 17:32
This sounds like it might be a duplicate of #3290.  Would you mind clarifying if the dashboard doesn't match the settings or if the settings themselves are changing?  And a link to the project or dashboard where you're seeing this would be great as well.

**Comment by navymaker** [comment] 2017-01-19 18:02
Yes, its seems like similar issue, when I'm update settings, dashboard shows me correct branch, but its resetting after several builds, I think. I'm experienced this issues with almost all projects in this subscription: https://app.shippable.com/subscriptions/549abdcad46935d5fbc0f5aa

**Comment by stephanielingwood** [comment] 2017-01-19 19:33
Thanks for sharing the link - that helped us find it. Looks like there's a bug in our project sync flow that is resetting the branches to be displayed. We've opened a bug internally to fix this and will let you know when it's deployed.

**Comment by rageshkrishna** [comment] 2017-01-30 05:44
@navymaker This has been fixed. Syncing the project will no longer reset the branch options. Please let us know if you still see issues with this.

**Closed by rageshkrishna** 2017-01-30 05:44 UTC
Labels: bug, in progress
