### ISSUE TITLE
Multiple builds are run instead of just HEAD vs base

### ISSUE THREAD

**Issue by pmoust** [Shippable/support#940] opened 2015-01-05 12:59 UTC
I 've got a shippable.yml which states:

```yaml
branches:
  only:
    - testing
    - develop
```

When a push to `testing` and PR is issued from `testing` to `develop` there are two builds run, one for `testing` and one for `develop`.

I would need just one build, one that has merged the PR HEAD against the PR base branch.

**Comment by pmoust** [comment] 2015-01-05 13:00
for your reference builds 54aa887b42798d110054220d and 54aa887b42798d110054220e

**Comment by pmoust** [comment] 2015-01-05 13:18
![screenshot 2015-01-05 15 17 33](https://cloud.githubusercontent.com/assets/2493339/5613512/f4e7dce2-94ed-11e4-81ce-ead9de0c09ad.png)

This is from a PR with a base branch `next` and head branch `PPH-89`

**Comment by manishas** [comment] 2015-01-05 21:56
@pmoust this is by design. When you push to testing only that branch is built. When you open a PR and want to merge to develop, we run the merged build for testing+develop.

**Comment by manishas** [comment] 2015-01-06 21:24
Closing this since this is by design.

**Closed by manishas** 2015-01-06 21:24 UTC
Labels: question, triaged
