### ISSUE TITLE
Queue stalled

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#3043] opened 2016-10-13 10:14 UTC
Due to the maintenance today we see quite some runs stalled in our queue. Some have fully finished jobs but are still shown as running, others don't start at all.

Could you have a look at this?

**Comment by PaulWebbster** [comment] 2016-10-13 10:21
We have the same issue. Few builds start and finish after maintenance but now everything stuck in queues.

**Comment by phagunbaya** [comment] 2016-10-13 10:24
Same here. Builds in waiting state.

**Comment by kanthchandra** [comment] 2016-10-13 10:25
I'm sorry about this, we are looking into this.

**Comment by mbrodala** [comment] 2016-10-13 10:39
The queue seems to be processed normally again.

**Comment by PaulWebbster** [comment] 2016-10-13 10:42
Yes, I can confirm this also

**Comment by phagunbaya** [comment] 2016-10-13 10:45
For me it's stuck on "Provisioning job node"

**Comment by PaulWebbster** [comment] 2016-10-13 10:47
@phagunbaya This stage can take few minutes, be patient.

**Comment by kanthchandra** [comment] 2016-10-13 11:21
@phagunbaya our build scheduler had some issues and as a result some builds which were triggered during that time were not allocated nodes. So if you trigger one more build, it will allocate the nodes again. Thanks for your patience.

**Comment by phagunbaya** [comment] 2016-10-13 11:27
That worked. Thanks !

**Comment by mbrodala** [comment] 2016-10-13 12:03
Alright, closing this one, thanks for fixing.

**Comment by mbrodala** [comment] 2016-10-13 14:24
I am currently seeing stalled builds again, are there still some issues?

**Comment by PaulWebbster** [comment] 2016-10-13 14:34
Yes, I can confirm this also. Once again...

**Comment by phagunbaya** [comment] 2016-10-13 14:37
Same here.

**Comment by PaulWebbster** [comment] 2016-10-13 14:55
It's working now

**Comment by mbrodala** [comment] 2016-10-13 15:19
Yes, looks like. I'll keep the ticket open for now. ;-)

**Comment by manishas** [comment] 2016-10-13 17:27
closing since this is resolved. we can reopen if needed.

**Closed by manishas** 2016-10-13 17:27 UTC
Labels: cs, resolved
