### ISSUE TITLE
Error response from daemon: Wrong login/password, please try again

### ISSUE THREAD

**Issue by molinto** [Shippable/support#1671] opened 2015-07-13 12:59 UTC
Keep getting fails, due to this error:
time="2015-07-13T12:58:43Z" level=fatal msg="Error response from daemon: Wrong login/password, please try again"

Wrong login/password for what?

**Comment by molinto** [comment] 2015-07-13 13:07
Linked Docker integration to project & now getting this:
docker: "login" requires a maximum of 1 argument. See 'docker login --help'.

**Comment by manishas** [comment] 2015-07-13 15:55
@molinto can you describe your scenario in a bit more detail? Are you using a custom docker image or just our default one?

Can you share your shippable.yml?

**Comment by molinto** [comment] 2015-07-14 07:17
Yep, its:
```
language: node_js

build_image: shippableimages/ubuntu1404_nodejs

node_js:
  - "0.10"
  - "0.11"
  - "0.12"

env:
  - NODE_ENV=test

before_install:
  - npm install -g mocha
  - npm install -g nodemon
  - npm install -g gulp
  - npm install -g bower

install:
  - npm install

after_script:
  - ./node_modules/mocha/bin/mocha --timeout 5000 --reporter spec --recursive -t 5000 -G

notifications:
     email:
         recipients:
             - me@email.com
         on_success: change
         on_failure: always
```

**Comment by lekhab** [comment] 2015-07-17 00:05
@molinto: I noticed you are still using our old format of integrating with Docker Hub. Can you please delete your Docker Hub credentials from your subscriptions -> settings? And then try running the build again. Since the image you are using is a public image, this should work without adding a project integration. 

The only way I can reproduce the error you see is when I my docker login credentials are incorrect. Since you still have an old version of Docker Hub credentials, we are trying to login even for a public image.  In the current version, you don't have to add a project integration unless you are using a private image.

**Comment by lekhab** [comment] 2015-07-17 00:05
Also, did you receive our  email  on the changes you need to make to add Docker Hub Integration in the new version? Also on our blog here: http://blog.shippable.com/shippable-3.0-breaking-changes.

**Comment by lekhab** [comment] 2015-07-27 23:16
Closing this. Please let us know if this is still an open issue.

**Closed by lekhab** 2015-07-27 23:16 UTC
Labels: bug, resolved, triaged

**Comment by molinto** [comment] 2015-07-28 08:40
Hi, sorry for delay.
I have removed the 'build_image: shippableimages/ubuntu1204_nodejs' fro my shippable.yml file & put this line in my project settings > pull image from input box.

I've also removed the docker info from the same project (project integrations) section.
