### ISSUE TITLE
Available react version from npm seem to be stale

### ISSUE THREAD

**Issue by gcoombe** [Shippable/support#3651] opened 2017-06-15 23:12 UTC
### Description of your issue:
I'm not sure if shippable is using some caching in front of the npm repo but it seems like the results I'm getting back are stale.  It can't find react@15.6.1 even though it's been available for ~23 hours.  If I roll back to 15.6.0 then I get an error bc it can't find create-react-class@15.6.0 (which is a sub dependency of react)

- When trying to download 15.6.1: https://app.shippable.com/github/gcoombe/fetch-home/runs/807/1/console
- When trying react@15.6.0: https://app.shippable.com/github/gcoombe/fetch-home/runs/808/1/console

**Comment by ambarish2012** [comment] 2017-06-15 23:19
@gcoombe can you try updating the version of npm itself using npm install -g npm.

**Comment by gcoombe** [comment] 2017-06-15 23:28
That seems to have fixed it.  Not sure I understand why but it works! Thanks.

**Comment by gcoombe** [comment] 2017-06-16 00:41
@ambarish2012 Sorry it seems like I closed this prematurely.  the build after I added the "npm install -g npm" it worked but on the next one I got the same issue: https://app.shippable.com/github/gcoombe/fetch-home/runs/810/1/console

**Comment by ambarish2012** [comment] 2017-06-16 04:10
@gcoombe I got this to work using this approach - https://github.com/ambarish2012/samplePipelinesDemo/blob/master/shippable.yml

**Comment by gcoombe** [comment] 2017-06-16 04:27
I'll give that a try.  Any idea why https://github.com/ambarish2012/samplePipelinesDemo/blob/master/shippable.yml#L12 is required?  I'm wondering if I always need to do this from here on out or if it's a temporary work around for something.

**Comment by ambarish2012** [comment] 2017-06-16 04:30
@gcoombe I think this is a temporary workaround. I think there are some gotchas in npm but I am not 100% sure about the root cause. After much trial and error and looking at how others had solved similar problems, I finally landed on this solution.

**Closed** 2017-06-16 06:52 UTC
Labels: resolved
