### ISSUE TITLE
Docker build sometimes halts after "build image"

### ISSUE THREAD

**Issue by ashernevins** [Shippable/support#2074] opened 2015-11-24 03:51 UTC
Two examples: https://app.shippable.com/builds/5652cd420b0f290e00edae61 and https://app.shippable.com/builds/5653d80fe412bb0c0061cdcd

These builds are Docker builds that then push to a repo. In both of these cases the build has stopped after the "build image" step, which shows as completed successfully. Pushing again to the same repo can work sometimes (there were 3 successful builds between the two linked above).

**Comment by rageshkrishna** [comment] 2015-11-24 05:14
@ashernevins Thanks for reporting this. Our build containers try to install virtualenv when they boot with these commands:

````
  $SUDO apt-get update && $SUDO apt-get install -y python-pip ssh git-core
  pip install -I virtualenv==1.11.4
````

For some reason, the `virtualenv` installation with pip is occasionally failing on your containers with the following error:

````
Downloading/unpacking virtualenv==1.11.4
  Running setup.py egg_info for package virtualenv
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/cds/build/virtualenv/setup.py", line 33, in <module>
        f = open(os.path.join(here, 'docs', 'index.rst'))
    IOError: [Errno 2] No such file or directory: '/cds/build/virtualenv/docs/index.rst'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/cds/build/virtualenv/setup.py", line 33, in <module>

    f = open(os.path.join(here, 'docs', 'index.rst'))

IOError: [Errno 2] No such file or directory: '/cds/build/virtualenv/docs/index.rst'
````

I am not sure yet why this is happening. Would it be possible for you to share your Dockerfile with me at ragesh@shippable.com? This might make it easier for me to repro the problem and debug further.

**Comment by ashernevins** [comment] 2015-11-24 05:20
@rageshkrishna the Dockerfile is simply "FROM asher/nodejs-runtime" which can be found here https://hub.docker.com/r/asher/nodejs-runtime/~/dockerfile/

**Comment by rageshkrishna** [comment] 2015-11-24 05:27
Thanks. I don't see any reason why this wouldn't work, but I'll play around with it a bit.

**Comment by pquentin** [comment] 2015-12-01 05:37
@rageshkrishna Any reason why you're using such an old virtualenv version?

**Comment by rageshkrishna** [comment] 2015-12-02 04:40
@pquentin This script was written long ago and it's just been a case of "if it ain't broke, don't fix it". Of course, now that we _are_ seeing occasional failures with this I will look into upgrading to a newer virtualenv.

@ashernevins Unfortunately, I haven't been able to repro this issue yet so I still don't have a root cause for the occasional failure. Perhaps upgrading virtualenv will make this go away, but I'm not completely sure that is the problem. I'll keep digging and see if I can find something. In the mean time, we'll also look at upgrading virtualenv to rule that out.

**Comment by ashernevins** [comment] 2015-12-08 12:42
This issue is happening again for some of my images. It's a real problem to not have reliability with a service like this. Are we any closer to a diagnosis or fix?

**Comment by avinci** [comment] 2015-12-16 04:31
@ric03uec we should look into upgrading all the stuff on our build runners. can we do this soon?

**Comment by rageshkrishna** [comment] 2016-03-03 03:10
@ashernevins Sorry for the long delay on this, but we have addressed this with the recent overhaul of our build system. The first improvement is that we no longer require virtualenv to run builds so this particular issue should no longer be a problem. The second is that _all_ errors that might happen when we boot the build container will now be visible in the console logs.

Please let us know if you continue to run in to this.

**Comment by manishas** [comment] 2016-03-04 23:42
This should not happen with the build system upgrade. closing.

**Closed by manishas** 2016-03-04 23:42 UTC
Labels: bug, resolved
