### ISSUE TITLE
Shippable eb deploy ERROR IOError [Errno 2] No such file or directory(zip file)

### ISSUE THREAD

**Issue by ramasamymohan** [Shippable/support#2698] opened 2016-06-11 17:11 UTC
I'm trying to deploy docker application to elastic beanstalk. eb deploy says creating application archive, but its not able to locate the archive or may be archive not created. I'm not sure whether missing something. Any ideas?

Here is my shippable.yml,

```
language: node_js
node_js:
  - "6.1"
env:
  global:
    - SHIPPABLE_ARCHIVE=false
    #secure variable contains values for AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY
    - secure: xxxxxx/xxxxxxxx
build:
    ci:
      - echo 'CI is running'
    post_ci:
      - docker build -t xxx/xxxxx:0.0.1 --rm ./
      - docker tag -f xxxx/xxxxx:0.0.1 xxxxxx/xxxxxxx:latest
      - docker push xxxxx/xxxxxx:latest
    on_success:
      - aws s3 sync $SHIPPABLE_BUILD_DIR "s3://xxxxxx" --region "us-west-2"

integrations:
  hub:
    - integrationName: "xxxxxxxxxxx"
      type: docker

  deploy:
    - integrationName: "xxxxxxx"
      type: aws
      target: eb_docker
      platform: "Docker"
      application_name: "xxxxxxxx"
      env_name: "xxxxxxxx"
      bucket_name: "xxxxxx"
      region: "us-west-2"
      image_name: "xxxxxxx"
      image_tag: "latest"
```

![screen shot 2016-06-11 at 11 31 33 am](https://cloud.githubusercontent.com/assets/7361904/15986354/d0c50aae-2fcb-11e6-9a0d-36c4200b029c.png)

Thank you!

**Comment by a-murphy** [comment] 2016-06-13 18:58
It looks like you are attempting to deploy a Docker image to AWS Elastic Beanstalk, as documented [here](http://docs.shippable.com/ci_configure/#aws-elastic-beanstalk) under "Docker deployment to AWS Elastic Beanstalk".  If this is the case, do you have a dockerrun.aws.json file?

**Comment by ramasamymohan** [comment] 2016-06-13 19:01
Yes, I do have dockerrun.aws.json file.

```
{
  "AWSEBDockerrunVersion": "1",
  "Image": {
    "Name": "xxx/xxx-xxx:latest",
    "Update": "true"
  },
  "Ports": [
    {
      "ContainerPort": "3000"
    }
  ],
  "Volumes": [
    {
      "HostDirectory": "/var/app/",
      "ContainerDirectory": "/opt/app"
    }
  ]
}
```

**Comment by a-murphy** [comment] 2016-06-13 20:39
Could you check that your bucket name (in the deploy integration in shippable.yml) is correct?  It should be `elasticbeanstalk-us-west-2-<account ID>`, as documented [here](http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/AWSHowTo.S3.html).  You should also be able to find it if you go to S3 in the AWS Management Console.

**Comment by ramasamymohan** [comment] 2016-06-13 21:02
Yes, I tried that. I checked the S3 bucket as well, the archive is not created.

**Comment by ramasamymohan** [comment] 2016-06-14 16:32
Any updates?

**Comment by a-murphy** [comment] 2016-06-14 16:57
I haven't been able to reproduce the error and am still looking for possible causes.

**Comment by ramasamymohan** [comment] 2016-06-14 17:06
I'm doing exactly the same from this [sample_node_eb_docker](https://github.com/shippableSamples/sample_node_eb_docker/blob/master/shippable.yml). I'm still getting the same error. If you need further details, let me know. I got struck at this point, I'm very disappointed with this.

**Comment by a-murphy** [comment] 2016-06-14 17:40
Which "Environment Type" did you choose when creating the environment for your AWS Elastic Beanstalk application?  The Docker predefined configuration works for me with both of the options in the environment type dropdown and that sample project.

**Comment by manishas** [comment] 2016-06-14 17:44
@ramasamymohan let us know if you're available to debug this over a hangout. That will speed up the resolution.

**Comment by ramasamymohan** [comment] 2016-06-14 17:45
I created the application with "Docker" predefined configuration and "single instance" Environment Type.
<img width="1022" alt="screen shot 2016-06-14 at 12 43 55 pm" src="https://cloud.githubusercontent.com/assets/7361904/16053311/dd5706a0-322d-11e6-87b2-b97403d8adcb.png">

**Comment by a-murphy** [comment] 2016-06-14 18:20
We've finally found something.  It looks like it's the slashes in the branch name.  We're still investigating it.

**Comment by ramasamymohan** [comment] 2016-06-14 18:49
Yes, removing the slashes in the branch name works. But I get the following error now, 
"ERROR: Application version cannot be any larger than 512MB"

![screen shot 2016-06-14 at 1 45 55 pm](https://cloud.githubusercontent.com/assets/7361904/16055391/af2bea9e-3236-11e6-8ce7-3dd1698c54fc.png)

**Comment by trriplejay** [comment] 2016-06-14 18:56
This is an AWS hard limit set on the application upload size for beanstalk.  Since you're doing docker deploy, you likely don't need to zip the whole application, since it should just be pulling your image that you built on Shippable.

To accomplish this, I recommend adding an `.ebignore` file to your repo.  The EB CLI will see this and will avoid packaging anything that is ignored.

For example, you could do something like this:

```
*
!Dockerrun.aws.json
!.ebextensions/*
```

Which will ignore everything except the dockerrun and the ebextensions directory.  You can further tailor it to suit your purposes.

Let us know if that helps! We're in the process of fixing the branch-name-with-slashes issue.

**Comment by ramasamymohan** [comment] 2016-06-14 19:26
That was very helpful, thank you! I just got past that error. Now its creating the application version archive, updating the environment, but fails to pull the docker image and the deployment fails. Am I still missing something?

**Comment by trriplejay** [comment] 2016-06-14 19:31
Is your image in a private docker repo? if so, you may want to take a look at this documentation:
http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create_deploy_docker_image.html#docker-singlecontainer-dockerrun-privaterepo

**Comment by ramasamymohan** [comment] 2016-06-14 19:34
Yes it is. Got it! 
Please keep posted on branch-name-with-slashes issue.
Thank you.

**Comment by trriplejay** [comment] 2016-06-14 19:57
@ramasamymohan the slashes issue is fixed now. Give it a try, and please let us know if you have any more issues, or if you'd still like to get on a hangout to discuss anything.

**Comment by ramasamymohan** [comment] 2016-06-14 20:34
@trriplejay I'm good. Branch name with slashes works fine now. I'm working on pulling the image from private docker repo. 

Thank you!

**Comment by manishas** [comment] 2016-06-16 21:33
Closing this issue since there is nothing more to be done here.

@ramasamymohan Let us know if you have any other questions.... glad the deployment worked!

**Closed by manishas** 2016-06-16 21:33 UTC
Labels: in progress, technical issue
