### ISSUE TITLE
Can't enable CI project for renamed github repo

### ISSUE THREAD

**Issue by jpbochi** [Shippable/support#3824] opened 2017-09-08 11:47 UTC
I forked a repo called WebClient, and renamed the fork to ProtonMailWebClient so that the name would make more sense in my repos.

Then, I tried to enable shippable in it by going to https://app.shippable.com/subs/github/jpbochi/enable and and looking for the repo. The first issue was that only "WebClient" was listed, and not the new name. I tried to use the "Synchronize SCMs" feature, but nothing changed.

When I tried to enable "WebClient", I got an error message. Unfortunately, I didn't copied it. It was happening every time, though. Shouldn't be hard to reproduce.

Then, I renamed my repo back to "WebClient" and tried to enable it again. This time it worked. This is an unfortunate workaround. I trust you are able to detect repo renames, and act accordingly.

**Comment by jpbochi** [comment] 2017-09-08 13:52
update: after I managed to have a working integration with my "WebClient" repo, I renamed it. The integration continued to work for a couple of hours, until builds stopped running. "ProtonMailWebClient" finally showed up, though. I enabled that one and things look stable at the moment.

Summarising my current state, I have two integrations for the same repo. One is broken and can't be disabled. The other one looks good at the moment. And here's a screenshot of how that look like:

<img width="881" alt="screen shot 2017-09-08 at 15 48 44" src="https://user-images.githubusercontent.com/96475/30214639-7d3ff8c4-94ad-11e7-88a4-9a4da8587d34.png">

**Comment by a-murphy** [comment] 2017-09-08 16:39
I haven't been able to reproduce this.  Would you mind clarifying how you renamed the project?  It looks like GitHub's ID (not the same as name) for the project changed when you renamed it, which doesn't usually happen.  If a repository name is changed on the GitHub settings page, the GitHub ID usually stays the same and Shippable will identify it as the same project.  Shippable has two projects because there are two different IDs.

I've updated the "WebClient" project on Shippable to hide it so it should no longer appear in your list of projects.

**Comment by jpbochi** [comment] 2017-09-08 17:30
I used the rename feature in github at https://github.com/jpbochi/ProtonMailWebClient/settings Perhaps the fact that this repo was a fork might have something to do with it? Can you check if the ID of the broken project is the same as https://github.com/ProtonMail/WebClient?

I think I forked that same repo about 2 years ago, and later deleted the fork. Recently, I forked it again. Maybe Shippable got a ghost of that deleted fork.

**Comment by a-murphy** [comment] 2017-09-08 17:56
It shouldn't matter that it's a fork, but I made sure to check with a fork earlier just in case.  The fork's ID won't be the same as the parent repository.

If you deleted a previous fork, that fork is most likely the WebClient project you were seeing.  And it would explain why the renames didn't appear to work.  How long ago did you delete the original fork?  After a while Shippable should have stopped displaying it.

**Comment by jpbochi** [comment] 2017-09-08 18:09
> How long ago did you delete the original fork?

I'm not totally sure, but it must have been a couple of weeks ago. The weird thing is that the project was building from commit on the new repo for about 2 hours. If it had the id of the old project, how come it had a working integration to the new one?

Anyway, this seems to be an exceptional corner case, and I got everything working now. It might be impossible to trace what happened. If you choose to close the issue, I totally understand.

**Comment by a-murphy** [comment] 2017-09-08 19:46
Although we identify projects by ID, we have to make API calls to GitHub using the project name.  So, when you tried to enable the older fork and the name matched the current repository on GitHub, the webhook would have been created for that repository.  GitHub also redirects some requests when a name changes, which likely allowed it to continue working after the rename until your account synchronized properly and we found out it was the wrong project.

I'm not sure why your account didn't sync correctly the first time you clicked "sync." (I couldn't find any errors for your account in the sync logs.)  But, since it's working now it's unlikely I'll ever find a reason.

Since there isn't anything we can do about enabling a project that has been deleted on GitHub when there is another repository with the same name on GitHub and you have permission on that repository, I'm closing this.

**Closed by a-murphy** 2017-09-08 19:46 UTC
Labels: resolved
