### ISSUE TITLE
Rest API for triggering builds?

### ISSUE THREAD

**Issue by bbradbury** [Shippable/support#1010] opened 2015-01-28 23:16 UTC
Is there a REST api for triggering builds? I'd like to put hooks in my provisioning/CM to trigger a canary build on all deploys.

**Comment by manishas** [comment] 2015-02-03 00:44
@bbradbury we currently do not expose our API, but look for some upcoming announcements.

**Comment by manishas** [comment] 2015-02-03 01:01
Duplicate of https://github.com/Shippable/support/issues/768 so linking to that issue and closing.

**Closed by manishas** 2015-02-03 01:01 UTC
Labels: feature request, triaged
