### ISSUE TITLE
Some failed builds do not trigger a Slack notification

### ISSUE THREAD

**Issue by pquentin** [Shippable/support#2516] opened 2016-04-12 05:59 UTC
### Is your request:

- [ ] A feature request: The feature you want currently does not exist. If implemented, will provide additional value to you.
- [x] A technical issue: You are unable to use Shippable's service per your expectation & need help to resolve the issue.
- [ ] A question: A non-technical question such as billing.

### Description of your issue:

Some failed builds do not trigger a Slack notification (but others do). Somes examples (I'll add more when I see more):

https://app.shippable.com/runs/570b722da6dbbe0c00f47263
https://app.shippable.com/runs/570bd53ae9b5240d0064b10c
https://app.shippable.com/runs/570cc071ab73e00c0029fa32
https://app.shippable.com/runs/570cbb4a7f71080c006c2e38

The Slack integration looks like this in the `.shippable.yml` file:

```
integrations:
  notifications:
    - integrationName: slack
      type: slack
      recipients:
        - #dev
      on_success: never
      on_failure: always
```

I'm not sure what's the problem. How can we diagnose this further?

**Comment by pranaypareek** [comment] 2016-04-12 13:20
@pquentin would you please try using double quotes around the name of the slack channel?

```
      recipients:
        - "#dev"
```

We expect the channel names to be wrapped in quotes (http://docs.shippable.com/ci_configure/#slack-notifications)

The reason why this might be working in your case is if you have some channel names configured from the UI in the account integration. Our system takes those values as strings.

I reproduced this issue using my sample (https://github.com/pranaypareek/samplePyt/blob/support_2516/shippable.yml)

```
integrations:
  notifications:
    - integrationName: slack
      type: slack
      recipients:
        - "#guilty_spark"
        - #test_interns
      on_success: never
      on_failure: always
```

I was able to receive the messages for the channel `"#guilty_spark"`  but not for `#test_interns` since this format isn't recognized.

Please let us know if the problem persists after making the change!

**Comment by pquentin** [comment] 2016-04-13 05:50
Most Slack notifications do get through, and all our projects are configured in the exact same way. For this reason, I don't think this is the issue. And since I don't think this is the issue I'm reluctant to change the ~90 .shippable.yml files we have.

(By the way, having to configure this everywhere (in the Slack integration, in the Shippable integration, and in the .shippable.yml file) makes no sense. And having to activate the integration in each project means we lose the benefit of configuring this through the .shippable.yml file. But I should open another issue for those points.)

Before changing the .yml files and waiting for the issues to happen again, I would like to know:

- Do you log the API calls you make to Slack?
- Can you confirm that for the builds I mentioned no API call was made?
- Can you explain why some notifications work and others don't?

I hope you don't consider my questions as unreasonable.

**Comment by pranaypareek** [comment] 2016-04-13 10:20
Would you send us the `runId`s for which the slack notifications got through? We need to check a few things on our end and we'll get back to you with the answers to your questions.

**Comment by pquentin** [comment] 2016-04-13 11:10
Sure:

 * https://app.shippable.com/runs/570b722da6dbbe0c00f47263
 * https://app.shippable.com/runs/570bd9e7f07b8d0c001afc06
 * https://app.shippable.com/runs/570c58a77f71080c0062fef4
 * https://app.shippable.com/runs/570c871bab73e00c0022a0b5

**Comment by kanthchandra** [comment] 2016-04-13 13:14
- Results of our findings for all the run ids given by you which received the notifications.

    - https://app.shippable.com/runs/570c871bab73e00c0022a0b5 - Account Integration Id 56d70fafa4be6b0c0069b8dd - configured OK - notification received.
    - https://app.shippable.com/runs/570c58a77f71080c0062fef4 - Account Integration Id 56d70fafa4be6b0c0069b8dd - configured OK - notification received.
    - https://app.shippable.com/runs/570bd9e7f07b8d0c001afc06 - Account Integration Id 56d70fafa4be6b0c0069b8dd - configured OK - notification received.
    - https://app.shippable.com/runs/570b722da6dbbe0c00f47263 - Account Integration Id 56d70fafa4be6b0c0069b8dd - configured OK - notification received. (This one was mentioned in the list of runs that received a notification as well as in the list of runs that did not receive the notification. I'm assuming that this was by mistake.)

- Results of our findings for all the run ids given by you which did not receive the notifications.
    - https://app.shippable.com/runs/570bd53ae9b5240d0064b10c - Account Integration Id 56d7fa757cab880d00a22abc - BAD CONFIGURATION - The slack url is not configured correctly - has been specified twice in the same field. - As a result notification not received.
    - https://app.shippable.com/runs/570cbb4a7f71080c006c2e38 - Account Integration Id 56d7fa757cab880d00a22abc - BAD CONFIGURATION - The slack url is not configured correctly - has been specified twice in the same field. - As a result notification not received.
    - https://app.shippable.com/runs/570cc071ab73e00c0029fa32 - Account Integration Id 56d7fa757cab880d00a22abc - BAD CONFIGURATION - The slack url is not configured correctly - has been specified twice in the same field. - As a result notification not received.

**Comment by kanthchandra** [comment] 2016-04-13 13:15
Answering your questions.

>Do you log the API calls you make to Slack?
Yes we do keep the logs.

>Can you confirm that for the builds I mentioned no API call was made?
NO - We didn't check any logs because we found that the problem was the user input.

>Can you explain why some notifications work and others don't?
As mentioned in the previous comment the slack account integration is configured in an incorrect way.

I just wanted to take some time here and explain the way we send slack notifications and the reason to update your yml files.

Since slack allows notifications to multiple channels for one webhook url we look at the channels configured in your yml. If we dont find any then we look at the channel specified in the account integration and send it to that channel. The reason why you got the notification although the yml is configured incorrectly is because of our fallback to the default channel specified in the account integration. We are planning to remove the channel from account integration in the near future, so we suggest you to please update your yml files and also fix the webhook url account integration with id 56d7fa757cab880d00a22abc.

**Comment by manishas** [comment] 2016-04-14 05:00
@pquentin I am closing this issue since this is a config error. Please let me know if you have any questions or concerns.

**Closed by manishas** 2016-04-14 05:00 UTC
Labels: cs, notifications, resolved, technical issue

**Comment by pquentin** [comment] 2016-04-14 06:04
Thanks @kanthchandra and @pranaypareek! Things are clear now. Thank you for the investigation.
