### ISSUE TITLE
 Build container exits with status 100

### ISSUE THREAD

**Issue by grouxsome** [Shippable/support#3520] opened 2017-04-17 19:09 UTC
wait_for_exit 12s
  sudo docker logs -f c.exec.WiFast-Base.2368.1 11s  
  echo Container c.exec.WiFast-Base.2368.1 exited with 100 0s  
Container c.exec.WiFast-Base.2368.1 exited with 100
  sudo docker rm -fv $CONTAINER_NAME 0s  
  Debug 0s
  Debug logs 0s  
ScriptType:setup_integrations|msg:/tmp/mexec/tmp-script.sh: line 325: [: ==: unary operator expected
ScriptType:collect_stats|msg:Identity added: /tmp/ssh/00_sub (/tmp/ssh/00_sub)
ScriptType:collect_stats|msg:Identity added: /tmp/ssh/01_deploy (/tmp/ssh/01_deploy)
ScriptType:collect_stats|msg:Identity added: /tmp/ssh/GithubSSHKey (/tmp/ssh/GithubSSHKey)
ScriptType:on_start_job_envs|msg:Identity added: /tmp/ssh/00_sub (/tmp/ssh/00_sub)
ScriptType:on_start_job_envs|msg:Identity added: /tmp/ssh/01_deploy (/tmp/ssh/01_deploy)
ScriptType:on_start_job_envs|msg:Identity added: /tmp/ssh/GithubSSHKey (/tmp/ssh/GithubSSHKey)
ScriptType:boot|msg:Identity added: /tmp/ssh/00_sub (/tmp/ssh/00_sub)
ScriptType:boot|msg:Identity added: /tmp/ssh/01_deploy (/tmp/ssh/01_deploy)
ScriptType:boot|msg:Identity added: /tmp/ssh/GithubSSHKey (/tmp/ssh/GithubSSHKey)
ScriptType:boot|msg:sudo: unable to resolve host ip-10-4-16-28

https://app.shippable.com/github/zenreach/WiFast-Base/runs/2368/1/console

**Comment by ambarish2012** [comment] 2017-04-17 20:05
@grouxsome we are investigating.

**Comment by grouxsome** [comment] 2017-04-17 20:07
Thank you. Please note that this is now failing for all builds and has
halted development and our Monday release.

**Comment by ambarish2012** [comment] 2017-04-17 20:15
@grouxsome apt-get update is failing on your custom image here -

Ign:17 https://dl.bintray.com/sbt/debian  Packages
Err:17 https://dl.bintray.com/sbt/debian  Packages
  403  Forbidden

It seems like an issue with some repository you have added to apt in your image.

**Comment by Jsgoller1** [comment] 2017-04-17 20:18
@ambarish2012 where are you seeing that error specifically?

**Comment by ambarish2012** [comment] 2017-04-17 20:19
I am seeing the error in the wait_for_exit section in your console logs.

sudo docker logs -f c.exec.WiFast-Base.2368.1 11s  
sudo: unable to resolve host ip-10-4-16-28
No LSB modules are available.
Distributor ID: Ubuntu Description: Ubuntu 16.04.1 LTS Release: 16.04 Codename: xenial
Ubuntu confirmed
Looking for apt-get...
Found apt-get at /usr/bin/apt-get
Looking for sudo...
Could not find sudo. Installing...
Ign:1 http://debian.datastax.com/community stable InRelease
Get:2 http://debian.datastax.com/community stable Release [7,168 B]
Get:3 http://debian.datastax.com/community stable Release.gpg [280 B]
Ign:4 http://repo.mongodb.org/apt/ubuntu precise/mongodb-org/3.0 InRelease
Get:5 http://repo.mongodb.org/apt/ubuntu precise/mongodb-org/3.0 Release [3,464 B]
Get:6 http://debian.datastax.com/community stable/main amd64 Packages [44.1 kB]
Get:7 http://repo.mongodb.org/apt/ubuntu precise/mongodb-org/3.0 Release.gpg [455 B]
Get:8 http://repo.mongodb.org/apt/ubuntu precise/mongodb-org/3.0/multiverse amd64 Packages [10.7 kB]
Get:9 https://deb.nodesource.com/node_4.x xenial InRelease [4,634 B]
Get:10 https://deb.nodesource.com/node_4.x xenial/main Sources [763 B]
Get:11 http://ppa.launchpad.net/webupd8team/java/ubuntu xenial InRelease [17.6 kB]
Get:12 http://archive.ubuntu.com/ubuntu xenial InRelease [247 kB]
Get:13 https://deb.nodesource.com/node_4.x xenial/main amd64 Packages [967 B]
Ign:14 https://dl.bintray.com/sbt/debian  InRelease
Ign:15 https://dl.bintray.com/sbt/debian  Release
Get:16 http://ppa.launchpad.net/maarten-fonville/protobuf/ubuntu xenial InRelease [17.5 kB]
Ign:17 https://dl.bintray.com/sbt/debian  Packages
Ign:17 https://dl.bintray.com/sbt/debian  Packages
Get:18 http://ppa.launchpad.net/webupd8team/java/ubuntu xenial/main Sources [1,395 B]
Get:19 http://ppa.launchpad.net/webupd8team/java/ubuntu xenial/main amd64 Packages [3,101 B]
Ign:17 https://dl.bintray.com/sbt/debian  Packages
Ign:17 https://dl.bintray.com/sbt/debian  Packages
Get:20 http://ppa.launchpad.net/maarten-fonville/protobuf/ubuntu xenial/main Sources [1,042 B]
Get:21 http://ppa.launchpad.net/maarten-fonville/protobuf/ubuntu xenial/main amd64 Packages [1,834 B]
Ign:17 https://dl.bintray.com/sbt/debian  Packages
Err:17 https://dl.bintray.com/sbt/debian  Packages
  403  Forbidden
Get:22 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]
Get:23 http://archive.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
Get:24 http://archive.ubuntu.com/ubuntu xenial/main Sources [1,103 kB]
Get:25 http://archive.ubuntu.com/ubuntu xenial/restricted Sources [5,179 B]
Get:26 http://archive.ubuntu.com/ubuntu xenial/universe Sources [9,802 kB]
Get:27 http://archive.ubuntu.com/ubuntu xenial/main amd64 Packages [1,558 kB]
Get:28 http://archive.ubuntu.com/ubuntu xenial/restricted amd64 Packages [14.1 kB]
Get:29 http://archive.ubuntu.com/ubuntu xenial/universe amd64 Packages [9,827 kB]
Get:30 http://archive.ubuntu.com/ubuntu xenial-updates/main Sources [304 kB]
Get:31 http://archive.ubuntu.com/ubuntu xenial-updates/restricted Sources [3,202 B]
Get:32 http://archive.ubuntu.com/ubuntu xenial-updates/universe Sources [186 kB]
Get:33 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [652 kB]
Get:34 http://archive.ubuntu.com/ubuntu xenial-updates/restricted amd64 Packages [13.2 kB]
Get:35 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [577 kB]
Get:36 http://archive.ubuntu.com/ubuntu xenial-security/main Sources [82.1 kB]
Get:37 http://archive.ubuntu.com/ubuntu xenial-security/restricted Sources [2,779 B]
Get:38 http://archive.ubuntu.com/ubuntu xenial-security/universe Sources [29.6 kB]
Get:39 http://archive.ubuntu.com/ubuntu xenial-security/main amd64 Packages [308 kB]
Get:40 http://archive.ubuntu.com/ubuntu xenial-security/restricted amd64 Packages [12.8 kB]
Get:41 http://archive.ubuntu.com/ubuntu xenial-security/universe amd64 Packages [132 kB]
Fetched 25.2 MB in 10s (2,380 kB/s)
Reading package lists...
W: The repository 'https://dl.bintray.com/sbt/debian  Release' does not have a Release file.
E: Failed to fetch https://dl.bintray.com/sbt/debian/Packages  403  Forbidden
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by ambarish2012** [comment] 2017-04-17 20:25
There is a workaround posted on stackoverflow -

http://stackoverflow.com/questions/42189350/when-running-apt-get-update-prior-to-sbt-install-a-http-403-is-received

**Comment by grouxsome** [comment] 2017-04-17 20:34
I see those now. Isn't that a shippable script installing SBT? It's in the
wait for exit section..and `sudo docker logs -f c.exec.py-portal.566.1`

**Comment by ambarish2012** [comment] 2017-04-17 20:49
Shippable is running apt-get update, but is not installing SBT. The wait for exit section most tails the logs of the build container, it can be useful for diagnosing logs for problems such as the one you are seeing. This section is usually not displayed in the console unless there is an error. 

The image you are using most likely has an SBT repository configured for apt, that repository is giving you a 403. We have no control over the installation of SBT, since it's in your custom image.

**Comment by grouxsome** [comment] 2017-04-17 20:50
Hmmm Ok. We believe we no longer need SBT so we are attempting to remove it
from the build image.

**Comment by ambarish2012** [comment] 2017-04-18 01:01
@grouxsome please let me know if this issue is resolved from your end.

**Comment by manishas** [comment] 2017-04-18 18:07
@grouxsome I am closing this issue. Please let us know if this isn't resolved and we will reopen.

**Closed by manishas** 2017-04-18 18:07 UTC
Labels: question, resolved
