### ISSUE TITLE
Cannot access my Github Organization's private repos

### ISSUE THREAD

**Issue by bloo** [Shippable/support#1741] opened 2015-07-30 15:53 UTC
@manishas I can't re-open #617 so am creating a new issue. I'm part of Github org's Owner group and I also have "PRIVATE REPOS" enabled on my Shippable profile, but cannot see any of the private repos.

**Comment by bloo** [comment] 2015-07-30 16:04
update: logging out and back in did nothing, but _forcing sync_ on the projects page listed all the repos. Still a bug, but found the work-around.

**Comment by lekhab** [comment] 2015-07-30 22:58
@bloo: glad you managed to resolve this quickly. The workaround is actually by design - since we only sync at an hourly frequency. We do recommend force syncing if anything changed upstream and the sync hasn't happened. Not sure if that was the case for you. I was unable to reproduce your scenario.

Closing since the issue is resolved. Please let me know if this recurs and I will re-open.

**Closed by lekhab** 2015-07-30 22:58 UTC
Labels: question, triaged
