### ISSUE TITLE
Cache PHP extension directory

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#2553] opened 2016-04-20 10:49 UTC
### Is your request:

- [x] A feature request: The feature you want currently does not exist. If implemented, will provide additional value to you.
- [x] A technical issue: You are unable to use Shippable's service per your expectation & need help to resolve the issue.
- [ ] A question: A non-technical question such as billing.

### Description of your issue:

We are currently installing the PHP extension `intl` via Pickle as described in #2086. This process takes a bit more than one minute and we'd like to speed this up by skipping the installation if the extension is already present.

This could be achieved with the new `cache_dir_list` option but that one needs literal paths, thus the currently used `$HOME/.phpenv/versions/$(phpenv version-name)/lib/php/extensions/no-debug-non-zts-20131226/` cannot be added to that list.

Any idea how to achieve this or if there are other options?

**Comment by manishas** [comment] 2016-04-21 18:23
@mbrodala we have a bug at our end for this scenario. The $(phpenv version-name) is not being parsed correctly and hence there is an issue with caching this directory.

@chetantarale is going to work on fixing this.

**Comment by chetantarale** [comment] 2016-04-25 13:09
@mbrodala This has been fixed now. Can you please try and confirm that it works .
Also [here](https://github.com/chetantarale/php-intl/blob/master/shippable.yml) is sample project for your reference.

**Comment by mbrodala** [comment] 2016-04-25 14:23
@chetantarale Somehow it doesn't work [as it seems](https://app.shippable.com/runs/571e274c4374eb0c002c23a6). I'm using the following ATM:

```yaml
build:
  cache: true
  cache_dir_list:
    - ...
    - $HOME/.phpenv/versions/$(phpenv version-name)/lib/php/extensions/

  ci:
    # Debug before
    - find $HOME/.phpenv/versions/$(phpenv version-name)/lib/php/extensions/
    - find $HOME/.phpenv/versions/$(phpenv version-name)/lib/php/extensions/ -name intl.so | wc -l
    - >
      if [ $(find $HOME/.phpenv/versions/$(phpenv version-name)/lib/php/extensions/ -name intl.so | wc -l) -eq 0 ]; then
        # Install PHP "intl" extension for \Collator class usage
        pickle install --ansi intl
        echo "extension=intl.so" >> $HOME/.phpenv/versions/$(phpenv version-name)/etc/php.ini;
      fi;
    # Debug after
    - find $HOME/.phpenv/versions/$(phpenv version-name)/lib/php/extensions/
    - find $HOME/.phpenv/versions/$(phpenv version-name)/lib/php/extensions/ -name intl.so | wc -l
    - ...
```

The 2nd debug shows the installed `intl.so` but it's not present on rebuild/next build. Any idea why?

(I'm using this setup since I see no way to figure out the `no-debug-non-zts-20131226` part at build time, e.g. via `phpenv`.)

**Comment by manishas** [comment] 2016-04-25 15:52
@mbrodala I looked at the sample project in @chetantarale's comment above and he is caching the following directory -

```
cache_dir_list:
    -  /root/.phpenv/versions/$(phpenv version-name)/lib/php/extensions/$dirToCache
```

Can you try it the way it's being done in the sample? Sample yml is - https://github.com/chetantarale/php-intl/blob/master/shippable.yml

**Comment by mbrodala** [comment] 2016-04-26 07:37
@manishas Unfortunately not because in this case `$dirToCache` would be `no-debug-non-zts-20131226` which I cannot determine as stated.

**Comment by chetantarale** [comment] 2016-04-26 07:45
@mbrodala Caching would not work if you are running matrix builds.Currently this is a limitation on our end. But for non matrix builds caching should work as expected.
We tried reproducing the scenario but couldn't. [Here](https://github.com/chetantarale/php-intl/blob/master/shippable.yml) we tried doing something similar what you are doing and looks like its working fine.

**Comment by mbrodala** [comment] 2016-04-26 07:54
@chetantarale Are the builds for that project publicly accessible? I'd like to see two subsequent builds with this configuration.

**Comment by chetantarale** [comment] 2016-04-26 09:10
@mbrodala  I tried it with the sample php-intl project. [Here](https://app.shippable.com/runs/571f2ecf7a93fb0b006d5e4e) is the link for the sample.

**Comment by mbrodala** [comment] 2016-04-26 09:30
@chetantarale Hm, and did you flush the caches after the change? It's odd because by now you have basically the same setup as us.

**Comment by chetantarale** [comment] 2016-05-03 05:57
@mbrodala It looks like that particular build of yours failed. And caching will not work if a build fails.
We will be working on adding this feature(caching on build failure).

Closing the issue. Please let us know if you have further questions.

**Closed by chetantarale** 2016-05-03 05:57 UTC
Labels: beta verified, bug, core

**Comment by mbrodala** [comment] 2016-05-03 08:05
@chetantarale You are right, that indeed did prevent the caching. I've fixed this error and triggered a few builds and now the caching indeed [works as desired](https://app.shippable.com/runs/57285b033145260c00569b6e). :-)
