### ISSUE TITLE
GitHub pull request builds triggered twice

### ISSUE THREAD

**Issue by adambyrtek** [Shippable/support#1068] opened 2015-02-19 20:37 UTC
Every new push to a GitHub branch corresponding to an open pull request results in two builds being triggered with the following labels:
- Changeset: b456592 (PR#234), Branch: master
- Changeset: b456592, Branch: foo-bar

In other words, every commit is being built twice. How to avoid that?

**Comment by manishas** [comment] 2015-02-20 00:05
@adambyrtek this is by design. If the commit is a part of the pull request then we trigger a build on the branch where it was committed and another one to test the merged changes. 

We also show build status on your PR page on GitHub. If the status there is green, it means that CI for the master branch will pass after the merge, so the user is comfortable merging the PR.

**Comment by adambyrtek** [comment] 2015-02-21 00:18
Thanks for the explanation, this makes perfect sense now.

**Comment by manishas** [comment] 2015-02-21 00:21
Thanks! Closing.

**Closed by manishas** 2015-02-21 00:21 UTC
Labels: question, resolved

**Comment by lienvdsteen** [comment] 2015-03-02 16:57
@manishas Is there a way to disable the build for master?

**Comment by pmoust** [comment] 2015-03-02 17:03
@lienvdsteen what I did for repos that I did not need this feature was to disable the github payload to be sent on push event and just keep the PR event, go to `settings/hooks` in your Github project to find the shippable webhook.
![screenshot 2015-03-02 19 01 47](https://cloud.githubusercontent.com/assets/2493339/6445731/af8a7db0-c10e-11e4-8045-7f6f40cf2328.png)

**Comment by lienvdsteen** [comment] 2015-03-02 18:17
Thanks for the tip @pmoust !

**Comment by adambyrtek** [comment] 2015-03-04 16:14
:+1:
