### ISSUE TITLE
Urgent - Unable to build anything after card fails

### ISSUE THREAD

**Issue by Kivol** [Shippable/support#2860] opened 2016-08-08 11:42 UTC
I tried to add a card and subscribe, but failed somehow. However, I'm not able to build anything after card fails. 

The error message for the build attempt is: https://app.shippable.com/projects/566ff0f71895ca4474665ac8/status/
```
(Id: 4006) postRun failed for projectId: 566ff0f71895ca4474665ac8
verbose: projects|triggerNewBuildRequest:566ff0f71895ca4474665ac8|_queueRun
404
```

I guess it has to do something with the inactivity of the node presents in https://app.shippable.com/subscriptions/56f7e3f29d043da07b0507b7/settings/nodes .
Also, I cannot access to 'billing' menu at https://app.shippable.com/subscriptions/56f7e3f29d043da07b0507b7/settings/billing .

My github ID is Knowre-Dev (which is organization ID). Thanks in advance.

**Comment by kanthchandra** [comment] 2016-08-08 12:00
Hi @Kivol, you should be able to trigger builds now, I'm still looking into what happened in that background that caused this. Let us know if you are still not able to trigger builds.

**Comment by Kivol** [comment] 2016-08-08 12:18
Thanks, but it is being hold more than 15 minutes on 'Provisioning Job Node' phase, which didn't took that long before.

https://app.shippable.com/runs/57a8749a5aa7620d0090af26/1/console

**Comment by kanthchandra** [comment] 2016-08-08 12:25
@Kivol did you reset your subscription anytime in the last hour?

**Comment by Kivol** [comment] 2016-08-08 12:26
Yes, I tried resetting the subscription for a few times before you reach me.

**Comment by kanthchandra** [comment] 2016-08-08 12:36
We have resolved all the issues and you can trigger a build and they should be running. 

You can upgrade your sub again by adding the card and let me know if that works.

**Comment by Kivol** [comment] 2016-08-08 12:48
It doesn't seem to be resolved. I tried to reset every secure strings on my projects and tried to build again, but it is still being hold in 'provision job node'. Moreover, I tried to upgrade my subscription but it still fails, and I cannot enter 'billing' menu after that.

The holded build now is:
https://app.shippable.com/runs/57a87df66a05380c00b920a9/1/console

**Comment by kanthchandra** [comment] 2016-08-08 12:53
Sorry about the back and forth here, your node doesn't seem to connect to the queue for some reason. This might have to do something with the resetting of the node. So give me some time so that I'll verify a couple of things and get back to you.

**Comment by kanthchandra** [comment] 2016-08-08 13:18
@Kivol I can confirm that your node is able to connect to the queue now. I'm still investigating as to why you are not able to upgrade your sub. There are some issues with the upgrade of sub which is the root cause of this. I'll let you know when we have resolution on this one.

In the mean it would help us debug the issue if you can let us know the actions that you performed while upgrading the sub?

**Comment by Kivol** [comment] 2016-08-08 13:21
Hmm I'm afraid to spend more time on this today(because I reset my subscription key so I have to change every secure keys and confirm them on the projects), so I think it'll be better to just give up the upgrade today and try the subscription later. I'll let you know then.

Anyway, thank you very much!

**Comment by Kivol** [comment] 2016-08-08 13:26
It works! Thank you very much.

Well I didn't do much things because all I tried is upgrading the subscription(using two nodes) and it failed(the transaction was denied), and it seems like the shippable fails to provision my node, because every build attempted is hold from then. Plus, after that I cannot load the 'billing' menu.

**Comment by kanthchandra** [comment] 2016-08-08 13:30
I have opened an internal issue to track this. I'll get back to you when I have more info on this.

**Comment by kanthchandra** [comment] 2016-08-10 11:22
assigning this to @rageshkrishna after discussing with him.

**Comment by manishas** [comment] 2016-09-09 00:22
@Kivol are you still running into this?

**Comment by rageshkrishna** [comment] 2016-09-14 09:02
@Kivol We have completely revamped our billing system with the latest release. You should not be running in to this bug anymore.

**Comment by manishas** [comment] 2016-09-14 22:09
CLosing this issue since it should be fixed with the Aug 25 release. Please let us know if you're still running into this and we'll reopen and investigate.

**Closed by manishas** 2016-09-14 22:09 UTC
Labels: bug, investigate
