### ISSUE TITLE
CI process and environment variables

### ISSUE THREAD

**Issue by sheldon-sminq** [Shippable/support#2347] opened 2016-03-09 07:05 UTC
my environment variable set in the pre boot process, but these variable are not accessible in CI section.

My maven build depends on these environment variables, hence the build is failing everytime.

https://app.shippable.com/runs/56dfc2c4069dbc0d009d72bf

**Comment by avinci** [comment] 2016-03-09 07:17
This is by design as we wanted to separate integration keys etc. from the actual container. There are a few ways you could work around this. Could you help me understand your scenario and I could probably help you achieve what you are doing. 

The main question I have is, what are you doing in the pre_ci section? It was basically done to allow for Dockerbuild. Are you using that?

**Comment by sheldon-sminq** [comment] 2016-03-09 07:32
No i am not using the pre_ci, i am using a drydoc shippable container directly to run my build. I have attached my shippable.yml file for your reference

[shippable-sample.txt](https://github.com/Shippable/support/files/164677/shippable-sample.txt)

**Comment by sheldon-sminq** [comment] 2016-03-09 07:34
So i basically pull the drydock/u12javpls container, then set up a DB with my schema and test data in the ci step.
once i run mvn install in the ci step the build fails as the ENV variables are not present.

**Comment by avinci** [comment] 2016-03-09 07:38
Apologize for our docs being inaccurate. We will update it as we don't support `env` tag in your boot. You can use `-e` flag in the `options` tag to add all your environment variables and it should work. 

@manishas we need to update docs ASAP.

**Comment by sheldon-sminq** [comment] 2016-03-09 07:47
Thanks for the quick update.

**Comment by manishas** [comment] 2016-03-09 08:30
docs are updated.

**Comment by sheldon-sminq** [comment] 2016-03-09 08:33
is it -e or --env? or both are valid?

**Comment by manishas** [comment] 2016-03-09 09:05
@sheldon-sminq options are whatever docker run accepts. so -e and --env should both work.
https://docs.docker.com/engine/reference/commandline/run/

**Comment by sheldon-sminq** [comment] 2016-03-09 09:16
@manishas what is the default user for mysql if enabled in services?

**Comment by sheldon-sminq** [comment] 2016-03-09 09:29
No success with a single build since morning, i have attached the builds here

https://app.shippable.com/runs/56dfdf953da7e30c00a82be8
https://app.shippable.com/runs/56dfe74f3ef3a50c002a9831
[shippable-sample.txt](https://github.com/Shippable/support/files/164828/shippable-sample.txt)

https://app.shippable.com/runs/56dfc2c4069dbc0d009d72bf
https://app.shippable.com/runs/56dfc885069dbc0d009ef8c5
https://app.shippable.com/runs/56dfca663da7e30c00a5a932
https://app.shippable.com/runs/56dfd64db285810c004f7df3

not sure what i am missing here, update yml file uploaded

**Comment by sheldon-sminq** [comment] 2016-03-09 11:09
There was an issue with my trigger imports in Mysql, now the build progresses forward.

**Comment by sheldon-sminq** [comment] 2016-03-09 11:19
My DB triggers don't seem to run on the docker image, as a result test cases fail.

**Comment by sheldon-sminq** [comment] 2016-03-09 12:23
Have disabled tests for now as my build fails because of DB triggers
[shippable-sample.txt](https://github.com/Shippable/support/files/165093/shippable-sample.txt)

Also on deployment to AWS EBS get errors build attached
https://app.shippable.com/runs/56e011f8b285810c005906f5

**Comment by sheldon-sminq** [comment] 2016-03-09 12:27
https://app.shippable.com/runs/56e014c1b285810c005993fe failed EBS build

**Comment by sheldon-sminq** [comment] 2016-03-09 14:39
You can close this one i have created  another help request

**Comment by manishas** [comment] 2016-03-10 00:12
Closing this issue.

**Closed by manishas** 2016-03-10 00:12 UTC
Labels: bug, in progress

**Comment by gegere** [comment] 2016-03-11 16:09
Happy to see the docs updated. Nice job!
