### ISSUE TITLE
I can't see all the projects of my company others can

### ISSUE THREAD

**Issue by pschrammel** [Shippable/support#1050] opened 2015-02-11 15:53 UTC
this happened after some time. A guy (who configured shippable) can still see all repo's build status the rest of us can't.

https://app.shippable.com/subscriptions/54919ee3d46935d5fbc070d9

**Comment by avinci** [comment] 2015-02-11 17:45
can you see the private repos turned on for you? 
![screen shot 2015-02-11 at 9 45 05 am](https://cloud.githubusercontent.com/assets/1302035/6152525/b68883f0-b1d2-11e4-81cc-1aaef5b83891.jpg)

**Comment by pschrammel** [comment] 2015-02-13 06:51
Yes, both are on. It worked for some time then suddenly stopped.

**Comment by manishas** [comment] 2015-02-16 18:16
@pschrammel we need additional information to debug this issue -

- Are you facing an issue with all repos for this specific subscription? Or just a few?
- What is the username of the person who configured Shippable and who can see all the repos?
- Can you send some screen shots where the repo build status is missing?

Thanks!

**Comment by pschrammel** [comment] 2015-02-17 06:35
- Just a view repos are affected. e.g. priceapi_api is our most important (private) repo and I can't see it. Some outher private repos (e.g. ek) are visible.
- https://github.com/prabeshshrestha configured all of the repos
![shippable](https://cloud.githubusercontent.com/assets/27882/6224145/6ec0d9a6-b677-11e4-8f33-6eb81f0b8f5b.png)

**Comment by manishas** [comment] 2015-02-17 06:51
@pschrammel thanks! this is indeed very strange. we're taking a look at this and will let you know as soon as know what's up.

**Comment by manishas** [comment] 2015-02-17 07:40
We will need to do a hangout to further debug this issue. @rageshkrishna will send you an email to set up a time. He is in the IST time zone which is 4.5hrs ahead of CET so it should be easy to find a good time. Thanks!

**Comment by manishas** [comment] 2015-02-21 00:34
@pschrammel @rageshkrishna were you able to connect? I'm checking in to see if we've made any progress in identifying the issue.

**Comment by pschrammel** [comment] 2015-02-21 17:11
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

No, didn't get any mail.

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iQIcBAEBAgAGBQJU6LwpAAoJEHBsXR3UqtsxFGcQAIW+f33vmJ9w3aHCEukdaGeP
h6t6qY0vTIstO8IEhj2ENRxxjU4IE3VAzroq2KakCZN+OBoOZKUZdSm6AUQkWKe8
73pXM++Qj2YF0MNdZJtBiueSSFnLr1+DMfJ5xPHFyBix+BAF26wEBJdpoCCKluea
ZITrLDfsBHiSsvVA8HR2dGf1hbZ9C+QuU33OIg5WUsAObTO71ndXwdBJxBYAWuo5
0poUC3K++t3nH3Ff6iThVU0v9ZrGNMUZZs6W07DXnx+hIAUBJv1kRQLgDU6E32hP
Q5F2c/mcAtXvQDgTu21PxqUA5tupxKRO4nI6HRIlX5T7LKI/cD8Wm/pD+26C+2JL
9HzCsziqs5+xQxIAn0Zz/x/e2qk8lKMrI3Q9wNJRyTrKsWQkus+rTQaTBYLUwi6q
KBDbR12iWlMimcqqkSOD0ZX+5Fid9mJ9TebeAunLM1O4T6NrE025AkiNDFh7aKaI
rlPZ9STUOCrMbGixr6csV6m4Yr7mynn+a8GnKN7mH3UEDgpOPV+amp5JoH+z5wUS
lAjvlgLvcV9G36r8PqEdsLqLvSx+yTSYDwi+e9JjP2sVU1tjmpq9vm0ep6+PvcSK
pGhllzYeLGb1+7I9or444B1ZBNJ6YnVXM17//UArdp1/6zT4ZeGvRAjetVUZbPdG
KPoCZ8cmNto0ixJlJuFZ
=JoAz
-----END PGP SIGNATURE-----

**Comment by rageshkrishna** [comment] 2015-02-21 17:27
@pschrammel I'm not sure why my email didn't reach you. Can you please mail me at ragesh@shippable.com so we can schedule something for next week? Thanks!

**Comment by pschrammel** [comment] 2015-03-11 07:00
Hi, I still can's see my projects. Did you fix the github syncing issue?

**Comment by pschrammel** [comment] 2015-03-23 08:36
Could you please give me some feedback about the state? I can't see our main project which is quite annoying.

**Comment by pschrammel** [comment] 2015-03-24 09:55
Okay guys this is open since 11. Feb we'll wait until 30. Mar then we'll switch somwhere else ...

**Comment by rageshkrishna** [comment] 2015-03-24 12:47
@pschrammel I'm very sorry about the delay on this. We've identified exactly what the problem is.

The issue is that we hide forks of private repositories, unless the fork is in your account.

I'm not sure if you're comfortable with me sharing actual github names here so I'm anonymizing them. The problem is that the repository you're unable to view (let's call it `abc/priceapi_api`) is a fork of the private repo `jjj/priceapi_api`. Since you have access to both the original and the fork, we keep the fork hidden from your view.

We do this so your dashboard is not cluttered with information from personal forks of an organization's repositories. This was a huge problem for some other customers because they could see dozens of forked repositories on their dashboards that they have no interest in tracking.

However, in your case this is clearly not the ideal outcome. 

Once again, I'm very sorry that this has taken so long. When you first reported this issue we were overhauling our permissions model and I had hoped that your issues would be resolved with the updates. Now that we have an exact cause behind this issue I can assure you that a fix will be coming very soon.

Please bear with us while we figure out how best to resolve this.

**Comment by pschrammel** [comment] 2015-03-26 09:12
For now we'll detach the forked repos from the upstream then our problems should be solved but as you have different requirements from different users a user's global or per repo decision would be a possible solution.

**Comment by manishas** [comment] 2015-03-29 16:46
this is now fixed even without the detachment. Please let us know if it works. Again, sorry for the delay!

**Comment by manishas** [comment] 2015-04-06 02:05
I am closing this issue. @pschrammel please let us know if you run into any issues again. Sorry for the long delay in fixing this.

**Closed by manishas** 2015-04-06 02:05 UTC
Labels: bug, resolved
