### ISSUE TITLE
AWS EB Docker deploy always failing now

### ISSUE THREAD

**Issue by ryancampbell** [Shippable/support#2765] opened 2016-06-30 18:08 UTC
Check out the build below. This has been running successfully for a month but now the pip install awsebcli command and all eb commands are failing. Possible a new version of python, pip or eb is causing the issue?

https://app.shippable.com/runs/57755d95561e0a0c00da798f

**Comment by a-murphy** [comment] 2016-06-30 18:17
It's a new version of `awsebcli`, and it's failing because it needs a newer version of `botocore` than is installed.  Just update `botocore` in `ci` or `post_ci` and it should work.

Duplicate of #2760, #2759, and #2757.

**Comment by abhijitkini** [comment] 2016-06-30 18:20
We have updated the [troubleshooting section of our documentation](http://docs.shippable.com/ci_troubleshoot/#importerror-cannot-import-name-config) to handle this error.

Let us know if you need further help on this issue.

**Comment by ryancampbell** [comment] 2016-06-30 18:21
Great thanks! Trying it now

**Closed by abhijitkini** 2016-06-30 18:20 UTC
Labels: cs, duplicate, resolved, technical issue
