### ISSUE TITLE
YAML config to specify which branches deploy to EB

### ISSUE THREAD

**Issue by JADurham909** [Shippable/support#2091] opened 2015-12-01 18:42 UTC
Is there a way to do the following workflow?

1) Run build scripts
2) Deploy / push docker image on all branches for formations
3) Deploy to AMAZON EB ONLY on master and no other branches.

**Comment by JADurham909** [comment] 2015-12-01 20:01
It there a hook I can use to manually push my container up and then conditionally deploy?  I tried after_success and after_script, but both say command docker is not found.  I assume these are running in the container itself, and thats why.

**Comment by avinci** [comment] 2015-12-04 14:05
this is a duplicate of this issue https://github.com/Shippable/support/issues/2031.
 
The other issue has been resolved and your workflow should be possible now. Let me know if you need any additional information.

**Closed by avinci** 2015-12-04 14:05 UTC
Labels: feature request, resolved
