### ISSUE TITLE
Slow pull times from Docker hub

### ISSUE THREAD

**Issue by rarkins** [Shippable/support#2686] opened 2016-06-08 11:43 UTC
Example:

```
Pulling selenium (elgalu/selenium:2.53.0o)...
2.53.0o: Pulling from elgalu/selenium
Digest: sha256:5cba1f7f0a748e27453e619d3a249e49ae085bb7ec701c7cfde00fceca00f0b4
Status: Downloaded newer image for elgalu/selenium:2.53.0o
```

The above takes over 10 minutes - is that expected?
Copy/pasted from https://app.shippable.com/runs/5757fe055cde2b0c0082c0c0 but seems to be the same on every run

**Comment by rarkins** [comment] 2016-06-08 11:54
Based on analysing different docker pull, I think the shippable minions are currently pulling from docker hub about 3-4x slower than when using a t2.micro on EC2.

**Comment by rarkins** [comment] 2016-06-08 12:59
Actually the same image took over 25 minutes to pull in the next build. Admittedly it's about a 2GB image but this speed makes it unfortunately impossible. Is the shippable <-> docker hub connection normally this slow, or is something abnormal causing speeds to drop?

**Comment by abhijitkini** [comment] 2016-06-09 18:12
@rarkins we are investigating the issue. We will get back with a update, as soon as we find something.

**Comment by rarkins** [comment] 2016-06-10 09:03
@abhijitkini I have created a public repository for simpler testing of docker pull times

Here's an example shippable build where `elgalu/selenium:2.53.0o` takes 10 minutes to pull: https://github.com/rarkins/docker-ci-test/tree/selenium

Here's the same pull at alternative provider CCI where it took less than 2 minutes: http://bit.ly/21bOD5F

Here's the same at alternate provider SCI where it took 1.5 minutes: http://bit.ly/1UG9OYY

Running the same command on a t2.micro EC2 instance took 3 minutes but that seems variable based on load.

**Comment by abhijitkini** [comment] 2016-06-10 22:33
@rarkins appreciate the above information. Our devs continue to investigate. We hope to have an update soon.

**Comment by manishas** [comment] 2016-06-10 22:40
@rarkins we can reproduce this issue and we'll get to the bottom of this. Thanks for the investigation!

**Comment by avinci** [comment] 2016-06-11 16:51
There is an issue with EBS block storage. if we use SSD machines, we get 2.5 minute pulls and with EBS blocks with even dedicated IOPS we are getting 8 minute pulls. 

As it was hinted in the thread above that this was due to resource contention, that is not true. Its not even network latency as we can clearly see the download occurs and the extract of images which is a local disk operation is what is killing it. We are working with AWS folks as well trying to see if there are workarounds. Currently this affects folks pulling from external registries. This happens only the first time you pull the image. 

If you use Shippable images its a non factor. 

Once we get more info, we will update the issue. Thanks very much for your patience.

**Comment by rarkins** [comment] 2016-06-12 04:20
Hi @avdrav, thanks for updating the progress here. I have some related questions below.

> Machines stay up for upto an hour.

I understand that once a machine is created, it stays up for up to an hour. Once an hour has passed, will it shut down immediately once it has no build queue? Or even after one hour, is there some "waiting" period after last build and before it initiates shutdown?

> If you use Shippable images its a non factor

But 100% of customers who need to pull from external registries are impacted by this slowness, right?

**Comment by avinci** [comment] 2016-06-12 10:48
@rarkins 
* yes, if the machines have not builds, they shutdown after an hour
* yes, 100% if the customers who pull are impacted. But this also depends on the image they are pulling. The image that you are referring to has 1 layer thanks 87% of the image and hence its impacted more as it can use only 1 thread. if the image sizes are more balanced, you don't see such a drastic impact...

**Comment by rarkins** [comment] 2016-06-13 10:46
@avinci FYI I still see at least 2x impact for any image I've tried (standard ones like node, nginx, postgres, etc). So yes, not as drastic, but still makes a big impact on any "cold" builds.

**Comment by avinci** [comment] 2017-02-28 10:02
Please let us know if this is still and issue. We have not seen this for a while now and hence closing it.

**Closed by avinci** 2017-02-28 10:02 UTC
Labels: in progress, question
