### ISSUE TITLE
eb_deploy ERROR - but aws_eb_deploy still marked as success

### ISSUE THREAD

**Issue by bobbydeveaux** [Shippable/support#2635] opened 2016-05-20 08:32 UTC
### eb_deploy ERROR - but aws_eb_deploy still marked as success

When AWS reports a failure with the eb_deploy command, the whole 'aws_eb_deploy' step should be marked with a red cross. However, it's being marked as successful, and this marking the entire  build as successful.

Please see:
https://app.shippable.com/runs/573ec9656138aa0c00a68fc5

**Comment by avinci** [comment] 2016-05-20 10:14
We do not fail the build on deploy. I agree that that red check mark should exist which we can fix, but the build will still be marked as success as everything after `post_ci` is considered to be non fatal to the build by design.

**Comment by bobbydeveaux** [comment] 2016-05-20 10:43
Thanks @avinci  - any chance you could look at https://github.com/Shippable/support/issues/2632 - currently can'y deploy as the Dockerrun.aws.json is being replaced with a blank file!

**Closed** 2017-02-28 09:43 UTC
Labels: feature request
