### ISSUE TITLE
Formation: Not able to set deploy settings for AWS 

### ISSUE THREAD

**Issue by manish-sangani** [Shippable/support#2179] opened 2016-01-06 21:38 UTC
Hi,

I am trying to set up a service to deploy docker build using AWS integration but not able to set a cluster name.

In a Cluster field, the list is not displaying.
Can you assist me so that I can proceed further?

Thanks
Manish

**Comment by abhijitkini** [comment] 2016-01-15 19:32
Were you able to set the previous step - Deploy integration to AWS successfully?
Can you also include a screenshot?

Here are step-wise instructions for your reference: http://blog.shippable.com/shippable-continuous-delivery-to-amazon-ec2-container-services-0

**Comment by manish-sangani** [comment] 2016-01-15 19:39
Yes, I followed that artcle.
Here is the screenshot where the service is running.

But when I click on the external link it timesout.

[cid:image001.png@01D14FA2.767B8DC0]

Thank you,
Manish Sangani | Technical Lead
P: 212.235.5324
manish.sangani@prideglobal.com<mailto:manish.sangani@prideglobal.com>
[p_logo]
420 Lexington Avenue, Suite 2220
New York, NY 10170

**Comment by trriplejay** [comment] 2016-01-15 19:52
I see in your service that although you've selected a load balancer, you have not checked the "load balanced" box next to the port that you'd like to expose.  Try checking that box, followed by a "deploy", and then your link should correctly route to your service.

**Comment by manish-sangani** [comment] 2016-01-15 20:00
As soon as I select the box, I get deployment failed error message.
I was wondering where can I see the logs so that I can determine why it failed.

Thank you,
Manish Sangani | Technical Lead
P: 212.235.5324
manish.sangani@prideglobal.com<mailto:manish.sangani@prideglobal.com>
[p_logo]
420 Lexington Avenue, Suite 2220
New York, NY 10170

**Comment by trriplejay** [comment] 2016-01-15 20:09
Ah, ok I believe the problem is related to your AWS roles.

In order to deploy an ECS service with a loadbalancer, AWS requires the specification of a "role" that it can use to access both ECS and EC2.  Shippable uses the AWS api to search for a role that meets these requirements.

To meet the requirements, you need to have a role which has a 'trust relationships' tab that looks like this:
![image](https://cloud.githubusercontent.com/assets/6869398/12363953/95d7c64e-bb80-11e5-8526-2a1ffa72f86d.png)

In order to get that, you can just click "edit trust relationship" and give it this input as the policy document:

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "Service": "ec2.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    },
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "Service": "ecs.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
```

Then click update.  Once your role has those relationships, Shippable will find it and use it to deploy your service.

We're working on getting this step added to our documentation.  We're also working on properly revealing deployment failure messages so that you will actually know what went wrong.

**Comment by manish-sangani** [comment] 2016-01-15 20:18
I followed the outline steps but still the deployment failed.

[cid:image001.png@01D14FA7.E9EDBEE0]

Thank you,
Manish Sangani | Technical Lead
P: 212.235.5324
manish.sangani@prideglobal.com<mailto:manish.sangani@prideglobal.com>
[p_logo]
420 Lexington Avenue, Suite 2220
New York, NY 10170

**Comment by trriplejay** [comment] 2016-01-15 20:27
hmm, The error is slightly different now, but it still seems to be related to your AWS permissions:

Here's the actual response from AWS:
```
2016-01-15T20:15:04.544Z - error: InvalidParameterException: Unable to assume role and validate the listeners configured on your load balancer.  Please verify the role being passed has the proper permissions.
```

Is your role attached to a policy that allows ec2, ecs, and elasticloadbalancing?
When I look at my role, I have an 'attached policy'.  And if I look at this policy, it has a policy document that contains the following settings:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": "ec2:*",
            "Effect": "Allow",
            "Resource": "*"
        },
        {
            "Action": "ecs:*",
            "Effect": "Allow",
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": "elasticloadbalancing:*",
            "Resource": "*"
        }
    ]
}
```
I'm not an expert on AWS IAM settings, but I think there are specific actions that your role needs to be able to access for ecs, ec2, and loadbalancing.  My policy just lets me do everything, but you can probably fine tune it to give you exactly what you need.  You may want to check out the ECS documentation for further details on what permissions are required.

**Comment by manish-sangani** [comment] 2016-01-15 20:55
I was able to deploy service by adding a policy.
However, my website displays blank page.

Can you send the error logs or whatever from your end so that I can troubleshoot?

Thank you,
Manish Sangani | Technical Lead
P: 212.235.5324
manish.sangani@prideglobal.com<mailto:manish.sangani@prideglobal.com>
[p_logo]
420 Lexington Avenue, Suite 2220
New York, NY 10170

**Comment by trriplejay** [comment] 2016-01-16 00:47
Well, at this point, the deploy was successful which means that Amazon ECS fully accepted the task definition and service update.  If you can't access your service, my guess is that there is something misconfigured in AWS.

On your services status page, try checking the "events" tab.  This is a list of events that we pull directly from amazon ECS, and it might give you some clue as to what the problem is.

**Comment by manishas** [comment] 2016-03-09 22:15
We have deprecated Formations on 2/29 and replaced it with a better implementation called Pipelines - http://docs.shippable.com/pipelines_overview/

I am closing this issue since it's related to Formations. Please try using pipelines and open up a new issue if you run into problems.Thanks!!

**Closed by manishas** 2016-03-09 22:15 UTC
Labels: info request
