### ISSUE TITLE
build killed

### ISSUE THREAD

**Issue by oppianmatt** [Shippable/support#2513] opened 2016-04-11 14:04 UTC
Is your request:
---------------------------

- [ ] A feature request: Feature currently does not exist. If implemented, will provide additional value to you.
- [x] A technical issue: You are unable to use Shippable's service per your expectation & need help to resolve the issue.
- [ ] A question: A non-technical question such as billing.

Description of your issue:
--------------------------

2 recent builds just died in the middle of running tests.

https://app.shippable.com/runs/570b840cc713690c002a1599
https://app.shippable.com/runs/570b83a364e3cd0c00e71686

```
python -u manage.py test --noinput --with-xunit --xunit-file=shippable/testresults/nosetests.xml 6m 17s  
SITE_ROOT: /root/src/github.com/pitchup/Pitchup.com
nosetests --with-xunit --xunit-file=shippable/testresults/nosetests.xml --verbosity=1
Creating test database for alias 'default'...
................................/root/d91d1939-f6c2-40f5-8503-131e8e81191d.sh: line 58:   362 Killed                  python -u manage.py test --noinput --with-xunit --xunit-file=shippable/testresults/nosetests.xml
```

In the shippable.yml file:

```
  ci:
    - mkdir -p shippable/testresults
    - python -u manage.py test --noinput --with-xunit --xunit-file=shippable/testresults/nosetests.xml
    - ls shippable/testresults
    - ls $(pwd)/shippable/testresults
```

**Comment by oppianmatt** [comment] 2016-04-11 18:09
It's not always happening, but it happens often. This is what I see:

![image](https://cloud.githubusercontent.com/assets/48596/14437365/c3fdeab2-0018-11e6-84cc-7b9d6b67d34f.png)

**Comment by oppianmatt** [comment] 2016-04-11 18:11
If I could get a look at the script, around line 58 I might be able to work out/around.

**Comment by oppianmatt** [comment] 2016-04-11 18:11
https://app.shippable.com/runs/570bd791f07b8d0c001a4327

**Comment by trriplejay** [comment] 2016-04-11 18:42
I think that `python -u manage.py ... ` command is line 58, and the script is terminating while attempting to execute that command, but I will see if I can confirm that line number.  We do have a 'script' tab you could look at, but it does not contain line numbers.

**Comment by trriplejay** [comment] 2016-04-11 18:57
looks like it's struggling with that create test database step.  Could this be related to that binding issue you had previously mentioned?

**Comment by oppianmatt** [comment] 2016-04-11 19:00
It's not that, the binding is all fine and some containers finish building. It does create the database and runs test as each period `.` is a successful test run. If I had to guess without seeing logs I would say the process/container got killed by something outside, is there an oom-killer running?

**Comment by trriplejay** [comment] 2016-04-11 19:16
Our build nodes don't have any modifications to the kernel's default OOM behavior, so that's definitely a possibility.  We also don't currently allocate any swap for the nodes, though I believe we have plans to do so in the near future.

**Comment by oppianmatt** [comment] 2016-04-12 09:36
Split up tests using parallel test and was all good last night (GMT) but now this morning started to get killed again.

Running test runner in verbose mode shows:

```
Calls the feature widget default params ... ok (6.2469s)
Calls the widget wth all params ... ok (0.0002s)
Calls the feature widget with facilities ... ok (0.0002s)
Calls the feature widget with location ... ok (0.0001s)
Calls the feature widget with types ... ok (0.0001s)
Calls the map widget with default ... ok (14.1017s)
Calls the map widget wth all params ... ok (0.0003s)
Calls the map widget with location filter ... ok (0.0004s)
Calls the map widget with facilities filter ... ok (0.0002s)
Calls the map widget with types filter ... ok (0.0002s)
Calls the widget view with no params ... ok (31.3863s)
Calls the widget wth some params ... /root/ba04c201-f17b-422d-990d-109b5eb8700b.sh: line 58:   347 Killed                  python -u manage.py test --noinput --with-xunit --xunit-file=shippable/testresults/nosetests.xml --verbosity=2 --logging-clear-handlers --with-parallel --with-timer
```

Will update if it keeps happening

**Comment by oppianmatt** [comment] 2016-04-12 10:17
yep still happening on random tests so it's not test specific:

```
test_can_list_campsites (xxx.api.tests.test_views.TestCampsiteViews) ... ok (27.6660s)
test_can_create_extra_price (xxx.api.tests.test_views.TestExtraPriceViews) ... ok (64.5078s)
test_can_patch_extra_price (xxx.api.tests.test_views.TestExtraPriceViews) ... /root/499993e0-1eb2-43a4-a9dd-8aaed5a190c3.sh: line 58:   374 Killed                  python -u manage.py test --noinput --with-xunit --xunit-file=shippable/testresults/nosetests.xml --verbosity=2 --logging-clear-handlers --with-parallel --with-timer
```

annoyingly it will kill one half of the parallel tests, the other half still goes but it's already a wasted build by then :(

**Comment by oppianmatt** [comment] 2016-04-12 10:17
https://app.shippable.com/runs/570cc344ab73e00c002a5d12

**Comment by oppianmatt** [comment] 2016-04-12 13:00
```
test_booking_arrive_filter (xxx.api.tests.test_views.TestBookingViews) ... ok
test_booking_depart_filter (xxx.api.tests.test_views.TestBookingViews) ... ok
test_booking_filters_after (xxx.api.tests.test_views.TestBookingViews) ... ok
test_booking_filters_before (xxx.api.tests.test_views.TestBookingViews) ... ok
test_booking_query_count (xxx.api.tests.test_views.TestBookingViews) ... ok
test_can_list_campsites (xxx.api.tests.test_views.TestCampsiteViews) ... /root/41a27d39-c31b-4808-ac58-d673720e8f57.sh: line 58:   363 Killed                  python -u manage.py test --noinput --with-xunit --xunit-file=shippable/testresults/nosetests.xml --verbosity=3
```

frustratingly they have all seemed to be killed today

**Comment by manishas** [comment] 2016-04-13 19:47
@oppianmatt we believe this might be an out of memory issue. Couple of suggestions:

- If you're kicking off tests in parallel, serializing them might help.
- Our build machines are 2 core, 3.75GB and this might be not be enough for your tests. You can try attaching your own build host to your subscription so that your builds run in bigger containers. Enabling swap space will help even further.
Advantages of running builds on your own infrastructure are detailed here - http://docs.shippable.com/ci_byoh/
Instructions for adding your own nodes are in our docs - http://docs.shippable.com/ci_subscriptions/#adding-your-own-build-infrastructure-byoh

**Comment by oppianmatt** [comment] 2016-04-14 13:42
yep we came to the same conclusion. I was running the test suite locally in a 4gb limited docker instance and getting the same results. We refactored our tests and they are now passing without getting killed.

Thanks for looking into it.

**Comment by oppianmatt** [comment] 2016-06-01 09:47
Reopening this as it's started to happen again. All builds since last Friday at 1:19 PM have started failing due to getting killed.

Last time the builds were getting killed was due to the OOM killer being invoked due to much memory usage by the tests. I could reproduce that on my VM that had the same hard memory limits. 

This time the tests run successfully on that VM.

**Comment by a-murphy** [comment] 2016-06-01 17:13
It's interesting that you couldn't reproduce the error, but your logs are consistent with running out memory.  Looking at a few of them, it is either killed or times out around the same test, which looks like a likely out-of-memory error to me.  Could it be that you aren't allowing for the memory used by Shippable in your tests?  It shouldn't be much, but it's impossible to run tests with absolutely no overhead.  The `Job node info` step in each build's logs will tell you how much is really available before we start the build container.  Would you mind trying to reproduce the error with slightly lower memory limits or by adding your own node (directions above)?

**Comment by abhijitkini** [comment] 2016-06-06 17:12
@oppianmatt following up to see if you were able to reproduce the error with the above suggestions.

**Comment by abhijitkini** [comment] 2016-06-07 21:26
Closing the issue. Please let us know if you need help on this issue.

**Closed by abhijitkini** 2016-06-07 21:26 UTC
Labels: cs, need info from customer, technical issue
