### ISSUE TITLE
branch not being built/deployed if it's been rebased?

### ISSUE THREAD

**Issue by fernandezpablo85** [Shippable/support#417] opened 2014-08-20 20:06 UTC
Hi,

We use shippable to build, test, and deploy to heroku using an after_success script. Our workflow is as follows:

* we commit to `master` and push changes to `origin`
* we have a branch per environment (`dev`, `integration`, `production`, etc)
* when we want to move our (say) development environment forward we do:

```bash
  git checkout dev
  git rebase master
  git push origin dev
```

This doesn't trigger a shippable build, because the commit that `master` points to has already been built when we pushed `master` to `origin`.

My question is: what would be the best way to make shippable execute at least the after_success script even though the commit has already been built (in a previous and different branch push)?

(I'm guessing merging instead of rebasing would fix it but it's messy and would like to avoid it).

**Comment by rageshkrishna** [comment] 2015-01-05 04:41
@fernandezpablo85 I think we've been able to finally identify the root cause for this issue. I believe you're using BitBucket for all your projects. BitBucket has a bug in their webhooks where the payload of the webhook does not contain a "branch" name for fast-forward merges. I have links to the issue tracker on BitBucket for this bug, and also a possible workaround you might be able to use at https://github.com/Shippable/support/issues/897#issuecomment-67817110

Unfortunately, the bug is entirely at BitBucket's end. Without a branch name we can't say for sure what needs to be built so there's not much we can do at this point except wait for BitBucket to get around to fixing this.

**Comment by manishas** [comment] 2015-02-11 05:17
Closing this since there is nothing actionable for us to do.

**Closed by manishas** 2015-02-11 05:17 UTC
Labels: bug, triaged
