### ISSUE TITLE
Disk space on dedicated host is getting full (  /data directory )

### ISSUE THREAD

**Issue by vkuusk** [Shippable/support#1517] opened 2015-06-03 00:53 UTC
the /data directory on the dedicated host is growing with the usage until it fills the whole disk

We have /data directory mounted on a separate disk so it does not kill the server, but new build do not go through. (Our situation right now)

What is the procedure to clean up the /data directory safely.
Last time (couple of months ago) I ended up removing dedicated server  and adding a new one.

@manishas  Could you, please, point me to a manual procedure to cleanup the "/data" dir, which does not require reinstall of the dedicated host

Thanks

**Comment by vkuusk** [comment] 2015-06-03 14:52
Similar issue is described in #1096

**Comment by manishas** [comment] 2015-07-14 22:51
duplicate of #1096. This is due to a Docker limitation and we'll work on giving customers easy ways to clean up periodically.

**Closed by manishas** 2015-07-14 22:51 UTC
