### ISSUE TITLE
Limit builds when using dedicated hosts

### ISSUE THREAD

**Issue by velo** [Shippable/support#1065] opened 2015-02-18 19:20 UTC
My build is really greedy.  And I wanna limit how many builds I run per machine.

If I don't linux will start killing processes.

How can I do so?

**Comment by rogierslag** [comment] 2015-04-20 16:32
duplicate of https://github.com/Shippable/support/issues/1200

**Comment by manishas** [comment] 2016-03-01 01:07
this is now available. Dedicated hosts are available as part of your subscription and are priced according to number of parallel builds. More at http://docs.shippable.com/ci_byoh/

**Closed by manishas** 2016-03-01 01:07 UTC
Labels: feature request, triaged
