### ISSUE TITLE
Shippable webhook error: Failed to generated outPayload

### ISSUE THREAD

**Issue by bram-rongen** [Shippable/support#4342] opened 2018-05-17 12:49 UTC
### Description of your issue:
I'm triggering webhooks from my build, they work for `start` and `success` but not for `failure` or `cancel`.

The error that is shown is: `Failed to generated outPayload: Could not parse body`

The relevant part of our shippable.yml:
```
env:
  - BUILD_STARTED: false
  
build:
  ci:
    - export BUILD_STARTED=true

integrations:
 notifications:
   - integrationName: primate_webhook
     type: webhook
     payload:
        - branch=$BRANCH
        - url=$BUILD_URL
        - build_number=$BUILD_NUMBER
        - commit=$COMMIT
        - compare=$COMPARE_URL
        - repo=$REPO_FULL_NAME
        - repo_url=$REPOSITORY_URL
        - project_id=$PROJECT_ID
        - started=$BUILD_STARTED
        - success=$is_success
     on_start: always
     on_success: always 
     on_failure: always
     on_cancel: always
```

link to the failing build: https://app.shippable.com/bitbucket/goalgorilla/eci_demo/runs/111/1/console

I'm unable to debug this, could you let me know what's wrong?

**Comment by bram-rongen** [comment] 2018-05-17 16:51
I notice it does work when the tests fail: https://app.shippable.com/bitbucket/goalgorilla/eci_demo/runs/93/1/console
But it doesn't work when it fails during install:
https://app.shippable.com/bitbucket/goalgorilla/eci_demo/runs/97/1/console

**Comment by trriplejay** [comment] 2018-05-17 17:21
hmm, i think this is a bug. it looks like the problem is that the script that saves the ENVs for the payload gets attached to the "on_failure" or "on_success" sections.  However, when the `on_failure` section itself fails, the steps to save the payload are skipped.  

You can see the difference in the 'on_failure' sections between your first example (run 111) and one of your other examples (run 93).  Our injected job_envs scripts are skipped in run 111.  As a result, there is no payload to parse later, and we get the error you saw.

As a workaround, I'd recommend you try to write your on_failure section in a way that it won't fail early itself, (for example putting `|| true` after the commands).

I'll open an internal ticket to address this.

**Comment by bram-rongen** [comment] 2018-05-17 18:26
Thanks! That workaround works!

**Comment by trriplejay** [comment] 2018-06-14 23:02
This fix has been released so that the payload workflow will still be executed if the on_failure or on_success sections fail.

**Closed as completed by trriplejay** 2018-06-14 23:02 UTC
Labels: bug
