### ISSUE TITLE
ssh hangs

### ISSUE THREAD

**Issue by adamyao** [Shippable/support#1259] opened 2015-04-01 23:48 UTC
In the shippable.yaml, I have the cmd:
after_success:
  - 'ssh -o "StrictHostKeyChecking no" -i $HOME/.aws/skybase_test_rsa ubuntu@10.253.116.251 "ls -al"'

and the build  prints:
Warning: Permanently added '10.253.116.251' (ECDSA) to the list of known hosts.
 
and hangs.

What possible wrong with my cmd? 
Thanks.

**Comment by manishas** [comment] 2015-04-02 03:48
tagging @rageshkrishna to help.

**Comment by rageshkrishna** [comment] 2015-04-02 07:07
Hi, @adamyao! Please try adding `-v` and `-o "BatchMode yes" to the ssh command like this:

````
ssh -v -o "BatchMode yes"  -o "StrictHostKeyChecking no" -i $HOME/.aws/skybase_test_rsa ubuntu@10.253.116.251 "ls -al"
````

`-v` will give us more verbose output, and enabling the `BatchMode` option will force SSH to quit with an error instead of prompting for input. My suspicion is that the public key authentication is failing and SSH is asking for a password to connect. This can be confirmed if you see something like this after adding the flags:

````
debug1: Authentications that can continue: publickey,password
debug1: Next authentication method: publickey
debug1: Offering RSA public key: /root/.ssh/foo_rsa
debug1: Authentications that can continue: publickey,password
debug1: No more authentication methods to try.
Permission denied (publickey,password).
````

**Comment by manishas** [comment] 2015-07-09 18:04
@adamyao i am closing this issue since it's more than 3 months old. Please re-open or comment if you want us to debug further.

**Closed by manishas** 2015-07-09 18:04 UTC
Labels: question, triaged
