### ISSUE TITLE
Allow running scripts in on_cancel or always for runCI

### ISSUE THREAD

**Issue by deanmraz** [Shippable/support#3017] opened 2016-10-05 01:22 UTC
## Cancelled build continues to run docker container
- we run our selenium tests in a container through a docker-compose run task. 
- when clicking on the cancel button shippable shows cancelled by the test continue to run. 
- project/run: https://app.shippable.com/runs/57f45342a4b44e0f004d99f1/1/console

Whats the best way to clean up?

**Comment by deanmraz** [comment] 2016-10-10 20:54
@manishas happen again on this build: https://app.shippable.com/runs/57fbff76865a090e00b76a23/1/console

**Comment by avinci** [comment] 2017-02-28 11:29
If you run compose, then cancelling will not kill any of your docker containers as we are not aware of any of that. This is by design. The best way to do it is to clean up the docker containers that you might spin up in the pre_ci script. Just be careful not to remove shippable containers and your builds will time out. I have added a feature request for the same where we can give you a tear down section after the build has been cancelled. I dont have a date for when that will be prioritized.

**Comment by ric03uec** [comment] 2018-10-16 20:52
@deanmraz we're now supporting `always` section in runCI. adding support for `on_cancel` required larger changes in our runtime which we're unable to take up at this point due to other high priority issues. We have added the support request for `on_cancel` in our backlog. We'll provide an update when it is available.
Closing this issue for now. Feel free to reopen if this is not working as expected.

**Closed by ric03uec** 2018-10-16 20:52 UTC
Labels: approved, feature request
