### ISSUE TITLE
Node setup fails

### ISSUE THREAD

**Issue by karamosky** [Shippable/support#3460] opened 2017-03-23 16:26 UTC
Hello Shippable
We are currently experiencing an issue with the build.
Here is the output of the setup_ve :1st_place_medal: 
```bash
  . /root/.nvm/nvm.sh 0s  

  nvm install "4.6.0" 
v4.6.0 is already installed.
nvm is not compatible with the npm config "prefix" option: currently set to "/usr"
Run `npm config delete prefix` or `nvm use --delete-prefix v4.6.0` to unset it.

  nvm use "4.6.0" 
nvm is not compatible with the npm config "prefix" option: currently set to "/usr"
Run `npm config delete prefix` or `nvm use --delete-prefix v4.6.0` to unset it.
```
Any idea on how to fix this ?
Thanks

**Comment by rageshkrishna** [comment] 2017-03-24 05:38
@karamosky Can you please share a link to your Shippable project so we can take a look? Thanks.

**Comment by karamosky** [comment] 2017-03-24 08:09
Hi @rageshkrishna 
Sure here is the link https://app.shippable.com/github/hiptest/hiptest/status/dashboard

**Comment by karamosky** [comment] 2017-03-24 13:13
@rageshkrishna I have been able to clear the cache and now the build is okay, but we had not set the npm prefix at anytime in our scripts.
Anyway, thanks a lot for your help.
And have a nice day :+1:

**Comment by rageshkrishna** [comment] 2017-03-24 15:40
Happy to help. Closing this issue as the problem is resolved.

**Comment by aurelien-reeves** [comment] 2017-03-27 10:04
Hi,

The issue is come back after one successful build.
I guess clearing the cache would allow us to pass the build. But what next?

As Karamosky wrote it, we don't set npm prefix in our scripts. Is there something else we should check?

Thanks in advance,
Aurélien

**Comment by rageshkrishna** [comment] 2017-03-27 10:47
What directories are you caching?

Can you try adding a `npm config list` as the first and last steps of your build? This will tell us if it really is being set by _something_ during the build or if it's actually something else that's going wrong.

**Comment by aurelien-reeves** [comment] 2017-03-27 12:40
```
  cache: true
  cache_dir_list:
    - /usr/local/rvm/environments
    - /usr/local/rvm/gems/$(rvm strings 2.3.1)
    - /usr/local/rvm/gems/$(rvm strings 2.3.1)@global
    - /usr/local/rvm/rubies/$(rvm strings 2.3.1)
    - /usr/local/rvm/wrappers/$(rvm strings 2.3.1)
    - /usr/local/rvm/wrappers/$(rvm strings 2.3.1)@global
    - /root/.nvm/versions/node/v4.6.0/lib/node_modules
    - $SHIPPABLE_BUILD_DIR/node_modules
    - $SHIPPABLE_BUILD_DIR/frontend/node_modules
    - $SHIPPABLE_BUILD_DIR/frontend/bower_components
```

First step of build:
```
npm config list
; cli configs
user-agent = "npm/2.15.9 node/v4.6.0 linux x64"

; node bin location = /root/.nvm/versions/node/v4.6.0/bin/node
; cwd = /root/src/github.com/hiptest/hiptest
; HOME = /root
; 'npm config ls -l' to show all defaults.
```

Last step of build (bug before post-ci)
```
npm config list
; cli configs
user-agent = "npm/2.15.9 node/v4.6.0 linux x64"

; node bin location = /root/.nvm/versions/node/v4.6.0/bin/node
; cwd = /root/src/github.com/hiptest/hiptest
; HOME = /root
; 'npm config ls -l' to show all defaults.
```

**Comment by aurelien-reeves** [comment] 2017-03-28 11:42
Hi,

The build seems to pass after removing `/root/.nvm/versions/node/v4.6.0/lib/node_modules` from the cache

**Closed** 2017-04-05 15:01 UTC
Labels: question, resolved
