### ISSUE TITLE
Bower install exits with "EINCOMPLETE"

### ISSUE THREAD

**Issue by SkyHacks** [Shippable/support#3182] opened 2016-11-21 23:18 UTC
Bower version: `1.8.0`

Shippable.yml snippet: `  - bower install --allow-root -V`

During the install, if a dependency returns with an error "EINCOMPLETE" then the Shippable build exits. Bower returns this error when `contentLength && bytesDownloaded < contentLength`. 

Related Bower source code: https://github.com/bower/bower/blob/d405917b4a6efdeeb24a2087680fd4163896ab8e/lib/util/download.js

This error has been returned from many different dependencies including Angular, Lodash, Moment, and Moment-Timezone.

Our shippable builds have been failing since November 10, 2016. Our source code has not changed and the error does not occur in a local environment. THIS ERROR PREVENTS THE COMPANY FROM DEPLOYING TO PRODUCTION.

A Failed Build: https://app.shippable.com/runs/5833728ab8b8e41000a5f610/1/console

```
....
bower angular-chart.js#~0.8.8                                     download https://github.com/jtblin/angular-chart.js/archive/0.8.9.tar.gz
bower angular-elastic#~2.5.1                                      download https://github.com/monospaced/angular-elastic/archive/v2.5.1.tar.gz
bower card#~1.2.2                                                 download https://github.com/jessepollak/card/archive/v1.2.2.tar.gz
bower ngclipboard#^1.1.1                                          download https://github.com/sachinchoolur/ngclipboard/archive/1.1.1.tar.gz
bower ng-img-crop-full-extended#~0.5.5                            download https://github.com/CrackerakiUA/ngImgCropExtended/archive/0.5.7.tar.gz
bower jquery#2.2.4                                                download https://github.com/jquery/jquery-dist/archive/2.2.4.tar.gz
bower angular-file-saver#~1.1.1                                   download https://github.com/alferov/angular-file-saver/archive/1.1.2.tar.gz
bower linkifyjs#~2.0.3                                            download https://github.com/nfrasser/linkify-shim/archive/v2.0.5.tar.gz
bower angular-bootstrap-switch#master                              extract archive.tar.gz
bower angular-ui-router#~0.2.14                                    extract archive.tar.gz
bower moment#~2.10.3                                                 error Transfer closed with 641071 bytes remaining to read
bower moment#~2.10.3                                                 retry Download of https://github.com/moment/moment/archive/2.10.6.tar.gz failed with EINCOMPLETE, trying with git..
bower angular-froala#master                                        extract archive.tar.gz
bower angular-md5#^0.1.10                                         download https://github.com/gdi2290/angular-md5/archive/v0.1.10.tar.gz
bower socket.io.c#master                                           extract archive.tar.gz
bower font-awesome#~4.6.x                                            error Transfer closed with 1821247 bytes remaining to read
bower font-awesome#~4.6.x                                            retry Download of https://github.com/FortAwesome/Font-Awesome/archive/v4.6.3.tar.gz failed with EINCOMPLETE, trying with git..
bower jasny-bootstrap#master                                       extract archive.tar.gz
bower angular-scenario#=1.3.15                                    download https://github.com/angular/bower-angular-scenario/archive/v1.3.15.tar.gz
bower lodash#~4.15.0                                                 error Transfer closed with 620032 bytes remaining to read
bower lodash#~4.15.0                                                 retry Download of https://github.com/lodash/lodash/archive/4.15.0.tar.gz failed with EINCOMPLETE, trying with git..
bower moment-timezone#~0.5.4                                      download https://github.com/moment/moment-timezone/archive/0.5.9.tar.gz
bower moment#~2.10.3                                              checkout 2.10.6
bower angular-mocks#=1.3.15                                       download https://github.com/angular/bower-angular-mocks/archive/v1.3.15.tar.gz
bower json3#~3.3.1                                                   error Transfer closed with 96802 bytes remaining to read
bower json3#~3.3.1                                                   retry Download of https://github.com/bestiejs/json3/archive/v3.3.2.tar.gz failed with EINCOMPLETE, trying with git..
bower angular-payments#9643191f2359e18d543c4abf1581f91f6729445f    extract archive.tar.gz
bower font-awesome#~4.6.x                                         checkout v4.6.3
bower lodash#~4.15.0                                              checkout 4.15.0
bower angular-resource#=1.3.15                                     extract archive.tar.gz
bower angular-validation-match#~1.5.0                              extract archive.tar.gz
bower json3#~3.3.1                                                checkout v3.3.2
bower angular-bootstrap#=0.13.0                                    extract archive.tar.gz
bower angulartics-google-analytics#~0.1.1                          extract archive.tar.gz
bower angular#=1.3.15                                              extract archive.tar.gz
bower angulartics#~0.20.1                                          extract archive.tar.gz
bower async#~1.3.0                                                 extract archive.tar.gz
bower angular-sanitize#=1.3.15                                     extract archive.tar.gz
bower es5-shim#~3.0.1                                              extract archive.tar.gz

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: ENOENT, rename '/tmp/cd410c6948279a1118a6b68c367bd77a/bower/673d4f049f0db3d188488f447477968a-6624-l05RsE/archive.tar.gz.160083588'
```

Notice the MD5 hash `673d4f049f0db3d188488f447477968a` in the error file path. This hash decodes to "lodash" which is the first file to error out with "EINCOMPLETE".

Why would this be happening? It seems like maybe our docker image is having network issues?

**Comment by SkyHacks** [comment] 2016-11-22 23:18
Any feedback?

**Comment by SkyHacks** [comment] 2016-11-28 16:07
It has been a week since I posted this issue.

**Comment by stephanielingwood** [comment] 2016-11-28 23:09
Sorry you're having trouble with your bower install. From what you're describing, the pattern of errors on the bower installs is too consistent to be a network issue. When AWS has network issues, we see a much more sporadic pattern of failures to download - it wouldn't be only on your bower installs.

We did notice that your builds started failing around the time bower released a new version (1.8.0). I would suggest trying to install the previous version of bower to see if that makes a difference. (`npm install -g bower@1.7.9`) One of the [changes](https://github.com/bower/bower/releases) in that release was to how it manages package downloads, so perhaps that's the cause of your problem.

FWIW, the image you're using is one we no longer support; the `shippableimages/ubuntu1204_nodejs` image hasn't been updated in about a year. The most current ubuntu 12.04 node image is `drydock/u12nod`. There is also `drydock/u14nod` available, if you want ubuntu 14.04. Both of those images already have rvm installed, so you wouldn't need to install it in your yml anymore.

Another potential culprit may be if you're committing your bower_components directory. It's possible that something odd may be happening on the bower install when the dependency is already present in bower_components. Admittedly, this is more of a longshot - I'd give the bower version a try first.

Hope this helps. Let us know if you have any other questions.

**Comment by SkyHacks** [comment] 2016-11-28 23:11
Thanks. I take a look at all of your suggestions and report back.

**Comment by stephanielingwood** [comment] 2016-11-28 23:15
Great. Hope it works. :)

**Comment by manishas** [comment] 2016-12-02 19:57
Closing this issue. @SkyHacks let us know if you're still running into this problem.

**Closed by manishas** 2016-12-02 19:57 UTC

**Comment by jacobuk** [comment] 2017-07-26 10:38
Would like to know if moving to an older version helped.

**Comment by SkyHacks** [comment] 2017-07-26 17:03
Sorry, I don't know. After having these issues, the company decided to move off of Shippable and run our own deployments.

**Comment by jacobuk** [comment] 2017-07-26 17:11
Thanks for the update! We're also looking for alternatives.

**Comment by manishas** [comment] 2017-07-26 17:21
Also happy to jump on a call and discuss the issues you're running into. Let me know if you're available now.
