### ISSUE TITLE
Cannot create API token

### ISSUE THREAD

**Issue by caarlos0** [Shippable/support#1750] opened 2015-08-03 12:44 UTC
Error:

```json
{
  "id":3000,
  "message":"APIToken creation failed",
  "methodName":"caller:540e7792399939140041ee81|accountPermissions|post|_checkPaidPlans"
}
```

**Comment by kevinhodges** [comment] 2015-08-03 14:46
Also seeing this error message, are you aware of this problem?

**Comment by notABluesSinger** [comment] 2015-08-03 14:46
Can also confirm I'm seeing this exact issue.

**Comment by lekhab** [comment] 2015-08-03 16:06
following up on this.

**Comment by lekhab** [comment] 2015-08-04 16:49
@caarlos0, @notABluesSinger, @kevinhodges:  We fixed this bug yesterday - a miss when we were making upgrades to our PlanManagement code. 

If you are still facing this, please add the link to the subscription so we can take a look.

**Comment by lekhab** [comment] 2015-08-11 20:18
closing this, as the issue is resolved.

**Closed by lekhab** 2015-08-11 20:18 UTC
Labels: bug, resolved, triaged

**Comment by caarlos0** [comment] 2015-08-11 20:41
Sorry, forgot to do that.

Thanks @lekhab !

**Comment by norbe** [comment] 2015-08-17 21:10
I've got the same problem at [our subscription](https://app.shippable.com/subscriptions/54e08c3a5ab6cc13528bff48).

**Comment by lekhab** [comment] 2015-08-17 22:54
@norbe - opened a new support issue to track your case, since this one was already closed.

Issue here: https://github.com/Shippable/support/issues/1797
