### ISSUE TITLE
FEATURE: Ability to customize message published to Slack

### ISSUE THREAD

**Issue by jtaylor10** [Shippable/support#3405] opened 2017-02-28 16:54 UTC
Using slack notifications in Pipelines you can set each job to notify on various events but from what I can tell there is no way customize the message. The message that gets posted just has a timestamp and the title of the job that's running. This is a great start but the ability to customize the messages would be great.

My specific example: I post to my slack channel whenever the `deploy_to_test` job starts and finishes. I'd love to customize the message so it said `now deploying version x.y.z to test env @ http://....`

**Comment by avinci** [comment] 2017-03-02 12:26
this is already planned and will be done in 5.3.3

**Comment by avinci** [comment] 2017-03-02 12:26
closing this as a duplicate of https://github.com/Shippable/support/issues/2650

**Closed by avinci** 2017-03-02 12:26 UTC
Labels: feature request, spec

**Comment by JoeRattanamaneesilp** [comment] 2018-03-01 00:30
Hi @a-murphy, 

Could you please let me know if there is any update or future plan about implementing this kind of feature

Regards,
Joe

**Comment by a-murphy** [comment] 2018-03-01 00:54
We don't currently support sending custom payloads with Slack integrations.  You can send custom payloads with a [webhook integration](http://docs.shippable.com/ci/webhook/#using-webhook-integration-in-ci).  Any updates for custom Slack payloads will be mentioned in #2650.
