### ISSUE TITLE
Build stopping midway in an "ls -l" command

### ISSUE THREAD

**Issue by albertolacework** [Shippable/support#2630] opened 2016-05-19 00:28 UTC
### Description of your issue:

Build is failing at an "ls -l" command. I can run make shippable locally but all in all this doesn't make sense lol.

- https://app.shippable.com/runs/573d0653383ab70c00a67c20

**Comment by a-murphy** [comment] 2016-05-19 16:07
Is there anything different about the files in the folder it stops on?  Does an `ls` of just that folder work?  There isn't anything obvious in your logs, but it is certainly odd that it's failing listing ordinary files.

**Comment by albertolacework** [comment] 2016-05-19 16:30
@a-murphy Nothing has changed in that particular directory since the last build

**Comment by a-murphy** [comment] 2016-05-19 17:15
Were there any changes to your makefile?  Could it be that it actually failed on the next command?  Otherwise it looks like a build that doesn't have enough available memory, and that does not seem likely for an `ls` command (and more often results in a timeout).

**Comment by albertolacework** [comment] 2016-05-19 17:43
Yes but well before the `ls` command and only to copy another html file over. I agree it looks like it ran out of memory though I've built far larger builds so I'm not sure why this happened.

**Comment by a-murphy** [comment] 2016-05-20 21:42
I've tried (and failed) to reproduce this.  Any chance that there's something else running in the background in your build?  Just ```ls -lR``` in a makefile isn't causing any errors for far more files than you are listing.

**Comment by albertolacework** [comment] 2016-05-20 22:06
It is possible but I can't find why. I've tried several times now for it to fail in a local make but it never has. We now have tons of builds failing for some reason in this particular way. The only difference between the two is that we have added a significant amount of alternative css files which I don't think take up that much memory or should be causing this issue.

**Comment by a-murphy** [comment] 2016-05-21 01:35
I couldn't find any clues in your logs.  It is interesting that it keeps getting stuck on the same file.  Are you sure there's nothing strange about that folder?  If it's memory or CPU constraints (we have build machines with 3.75GB of RAM and two cores), adding a larger build machine usually helps.  Here's the [documentation on using your own build machine](http://docs.shippable.com/ci_byoh/) if you want to try it.

**Comment by albertolacework** [comment] 2016-05-23 17:47
Yea this is a front end pull request. There are no file changes in our server directory where this is failing.

**Comment by manishas** [comment] 2016-05-27 04:55
@albertolacework thanks for the update! I am closing this issue but happy to take another look if you see the issue again.

**Closed by manishas** 2016-05-27 04:55 UTC
Labels: cs, investigate, technical issue
