### ISSUE TITLE
encrypted env vars doesn't work with forked repos

### ISSUE THREAD

**Issue by hackerhasid** [Shippable/support#1380] opened 2015-04-28 18:10 UTC
our development flow works like this:

1 - developers fork our repo
2 - developers work on their fork
3 - developers create pull requests when they're ready to merge back into the main repo

right now every user needs to encrypt variables themselves and this means that everyone needs their own `shippable.yml` file with these (differently) encrypted values! and none of the PRs can build because you guys won't decrypt env variables from forked repos for security reasons!

the solution codeship, heroku, and aws opsworks use for secure variables is storing them on the website (instead of in the shippable.yml). so as the admin for my company i'd set these variables inside shippable.com's ui.

**Comment by avinci** [comment] 2015-11-11 16:58
this is by design. But I think we should give an option to use a global encryption and local encryption. Thanks for pointing this out and we will implement this soon...

**Comment by rageshkrishna** [comment] 2016-03-15 08:02
I'm not sure I understand how to implement this securely for public projects. Even if the secure vars were injected server-side and not from the YML as secure envs, a malicious user can simply send a pull request that runs `env` and view all the secrets.

For private projects on the latest version of Shippable, this should already be working because we do not filter anything anymore. The assumption here is that only trusted users have been granted access to private projects.

@hackerhasid Does this work for you, or are you saying you need this on a public project?

**Comment by manishas** [comment] 2016-03-16 22:19
This is not on our near term roadmap, so closing as deferred.

**Closed by manishas** 2016-03-16 22:19 UTC
Labels: feature request, implement
