### ISSUE TITLE
Builds are timing out

### ISSUE THREAD

**Issue by dennissugar** [Shippable/support#1419] opened 2015-05-06 18:44 UTC
All of our builds have been timing out for the past couple of days, though from the logs it looks like they are completing successfully.

E.g. 55496213e4b7390c00600d8b

**Comment by manishas** [comment] 2015-05-07 01:45
we'll take a look at this and get back to you.

**Comment by fommil** [comment] 2015-05-07 09:06
I'm seeing the same thing on our dedicated hosts. The build is running fine to completion but shippable just doesn't see that the build has finished.

**Comment by VaclavSir** [comment] 2015-05-07 15:54
Same here. Unless the build fails, it times out.

E. g. this build took 2926 seconds (49 minutes) according to the console output, but 2 hours according to build details: https://app.shippable.com/builds/554b40f3ff724e0c00e4dc51

**Comment by soby** [comment] 2015-05-07 23:01
I get something similar on https://app.shippable.com/builds/554be258ff724e0c00e4ec03

It's a python repo using tox and I was getting timeouts regularly when I was calling external commands without the appropriate whitelist_externals set in my tox file, which throws warnings. Fixing that reduced the timeouts but they're still there. I'm guessing this may have something to do with parsing stderr output?

**Comment by jorgeer** [comment] 2015-05-08 08:50
Same as mine, all are timing out even though they should be finishing up at the end.
5547641d42da970c000f0952

**Comment by fommil** [comment] 2015-05-08 11:58
can we assume this is double red alert priority? It's breaking every build.

**Comment by pmacosta** [comment] 2015-05-11 15:03
I am seeing the same thing. All tests pass but I get a timeout status

**Comment by stekycz** [comment] 2015-05-11 18:17
It worked for a short time today but it is failing by timeout again :-(

**Comment by mortgagemapp** [comment] 2015-05-11 20:36
Same here.  Everything completes successfully, but shippable doesn't finish and we get a timeout.

**Comment by stekycz** [comment] 2015-05-12 19:50
It worked today well however it is failing again. The reason is different on the other hand. The build is run multiple times in one minion. For example here https://app.shippable.com/builds/55520d8bff724e0c00e53635

**Comment by phagunbaya** [comment] 2015-05-13 03:53
Same here. Shippable team please help!

**Comment by manishas** [comment] 2015-05-13 04:34
We pushed some fixes to production today, so your builds should not time out now. Please let us know if everything works as expected.

**Comment by manishas** [comment] 2015-05-13 22:34
This should be fixed now. Please re-open if you still run into this.

**Closed by manishas** 2015-05-13 22:34 UTC
Labels: bug, triaged

**Comment by fommil** [comment] 2015-05-14 14:06
@manishas there is a regression, now everything is timing out but isn't even getting started. e.g. https://app.shippable.com/builds/5554a98ed81dea0d0039cd7d

**Comment by dennissugar** [comment] 2015-05-14 21:56
Builds are working fine for us now.

**Comment by soby** [comment] 2015-05-15 19:26
@manishas Still timing out for me: https://app.shippable.com/builds/55563835d81dea0d0039eeb4 . Can't reopen.
