### ISSUE TITLE
Exception POSTing

### ISSUE THREAD

**Issue by dtroberts** [Shippable/support#2942] opened 2016-09-06 12:04 UTC
I am unable to build my project due to the following error:
```ERROR:shippable_adapter - shippable_adapter:Exception POSTing to https://api.shippable.com/jobs/57ceabc1d9cbdb0e000f8451/postConsoles: 'utf8' codec can't decode byte 0xb3 in position 0: invalid start byte: Traceback (most recent call last):
  File "shippable_adapter.py", line 54, in __post
    data=json.dumps(body),
  File "json/__init__.py", line 243, in dumps
  File "json/encoder.py", line 207, in encode
  File "json/encoder.py", line 270, in iterencode
UnicodeDecodeError: 'utf8' codec can't decode byte 0xb3 in position 0: invalid start byte```

The build in question: https://app.shippable.com/runs/57ceafe9be9c0a0e00535cf8/1/console

Any help is appreciated.

**Comment by kanthchandra** [comment] 2016-09-06 13:06
Hi @dtroberts , are you writing some non-ascii special character to the console? We always expect the output stream to be utf-8 compatible.

**Comment by dtroberts** [comment] 2016-09-08 13:28
No, not that I'm aware of. I don't see why anything non-ASCII would be getting outputted from the commands in place.

**Comment by kanthchandra** [comment] 2016-09-14 10:01
hi @dtroberts , I looked at this today, So can you try removing `"cat /etc/shippable/testresults/dbworker.tests.xml"` this command from your yml and try again? 

If the problem is solved and if you have no objections can you please email me the dbworker.tests.xml file so that we will repro this at our end and figure out a way to fix it?

Here is our theory - Our Build runner which streams the console output to your browser maintains a buffer which gets flushed at certain time intervals. So while flushing the buffer the encoded string from the stdout could be an invalid UTF-8 because it was cut in half or something like that and as a result the json parser is not able to decode it.

**Comment by kanthchandra** [comment] 2016-10-03 13:27
Closing this in favour of https://github.com/Shippable/support/issues/3011 since they both are related.

**Closed by kanthchandra** 2016-10-03 13:27 UTC
Labels: bug, core, need info from customer
