### ISSUE TITLE
Builds no longer triggering on commit

### ISSUE THREAD

**Issue by sethamclean** [Shippable/support#2897] opened 2016-08-23 15:50 UTC
### Description:
Feature branches no longer build when a commit is pushed to bitbucket. In the past we have not been able to manually trigger branches on these builds due to the slash in the branch name. Now we cannot trigger builds by pushing commits either.

**Comment by avinci** [comment] 2016-08-23 15:59
Bitbucket is having issues with we hooks. They just posted saying the issue is resolved. Can you try again and see if this has truly been resolved on bitbucket side?

**Comment by manishas** [comment] 2016-08-24 18:11
CLosing this since it was a bitbucket problem.

**Closed by manishas** 2016-08-24 18:11 UTC
