### ISSUE TITLE
can't log in

### ISSUE THREAD

**Issue by diwu1989** [Shippable/support#1925] opened 2015-10-07 08:41 UTC
Whenever I click log in
```
failed to fetch user profile (status: 401 data: {"message":"Requires authentication","documentation_url":"https://developer.github.com/v3"})
   at /home/shippable/www/node_modules/passport-github/lib/passport-github/strategy.js:90:28
   at passBackControl (/home/shippable/www/node_modules/passport-github/node_modules/passport-oauth/node_modules/oauth/lib/oauth2.js:123:9)
   at IncomingMessage.<anonymous> (/home/shippable/www/node_modules/passport-github/node_modules/passport-oauth/node_modules/oauth/lib/oauth2.js:143:7)
   at IncomingMessage.emit (events.js:117:20)
   at _stream_readable.js:944:16
   at process._tickCallback (node.js:448:13)
```

**Comment by rageshkrishna** [comment] 2015-10-07 08:54
@diwu1989 Is this happening for your consistently? I can't seem to reproduce this issue at the moment.

**Comment by diwu1989** [comment] 2015-10-08 06:12
Yes this happens to me consistently

**Comment by rageshkrishna** [comment] 2015-10-09 07:10
@diwu1989 We're still unable to reproduce this issue. I have contacted Github support to see if they might be able to give us some details on why your login is failing. I'll update this issue as soon as I have more information.

**Comment by diwu1989** [comment] 2015-10-09 09:50
You guys are probably hitting the oauth rate limit and has my account in a messed up state.

**Comment by avinci** [comment] 2015-10-26 15:24
@diwu1989 how many orgs/projects do you have under your account?

**Comment by manishas** [comment] 2015-11-09 05:03
@diwu1989 are you still running into this?  If yes, can you force sync your account and let us know... if it happens again we'll take a deeper look.

**Comment by avinci** [comment] 2015-11-11 17:54
closing this. please let us know if its still happening..

**Closed by avinci** 2015-11-11 17:54 UTC
Labels: bug, resolved
