### ISSUE TITLE
aws_eb_deploy not replacing "<IMAGE_NAME>:<TAG>" values in Dockerrun.aws.json

### ISSUE THREAD

**Issue by bobbydeveaux** [Shippable/support#2632] opened 2016-05-19 14:27 UTC
### aws_eb_deploy not replacing "<IMAGE_NAME>:<TAG>" values in Dockerrun.aws.json

Please see this successful build:
https://app.shippable.com/runs/573dca2712ebb90c00a9e031

It pushed the code to AWS, but really I wanted to push the Docker Image. I don't really want AWS to ru-run the Dockerful, as that build has already happened on Shippable.

The docs here:
http://docs.shippable.com/ci_configure/

Say:

```
Docker deployment to AWS Elastic Beanstalk
Shippable performs the following steps for you to deploy Docker on EB, after all the steps in shippable.yml that run inside the container are complete:

* Logs into EB
* Updates your Dockerrun.aws.json file with the IMAGE_NAME & TAG
* Uploads the artifacts to S3
* Updates the application version
* Issues the command to update the EB environment

Upon completion of the above, EB updates your environment based on the uploaded application version, independent of Shippable.
```

**BUT** - the zip file published to S3, has just the original Dockerrun.aws.json file, and AWS deployed using the Dockerfile.

**Comment by bobbydeveaux** [comment] 2016-05-19 14:30
My shippable.yml

```
# specifying build image
build_image: drydock/u14php7all:tip

# language setting
language: php

# specifying runtime
php:
   '7.0'

build:

  ci:
    - echo "No tests yet. Build successful."

  post_ci:
    - docker build  --rm=true -t bobbydvo/quint-api-release:$BRANCH.$BUILD_NUMBER .
    - docker build  --rm=true -t bobbydvo/quint-api-release:latest .
    - docker push xxxxxxx/xxxxxxxxxx:$BRANCH.$BUILD_NUMBER
    - docker push xxxxxxx/xxxxxxxxxx:latest

integrations:
  hub:
    - integrationName: "integrationName"
      type: docker
      branches:
      only:
        - master
  deploy:
    - integrationName: "integrationName"
      type: aws
      target: xxxxxx
      platform: "64bit Amazon Linux 2016.03 v2.1.0 running Docker 1.9.1"
      application_name: xxxxxxxxxxxxxxx
      env_name: xxxxxxxxxx
      bucket_name: xxxxxxxxxxxxxxxx/xxxxxxx
      region: eu-central-1
      image_name: "xxxxxx/xxxxxx"
      image_tag: "$BRANCH.$BUILD_NUMBER"

```

**Comment by trriplejay** [comment] 2016-05-19 17:23
If the image_name and image_tag aren't being replaced, that sounds like a bug. We'll investigate.  

One additional note.  When 'eb deploy' is run, if you have both a Dockerfile and a Dockerrun.aws.json file in the uploaded package, EB will favor the Dockerfile.  So even if your dockerrun has the correct image and tag, EB will run docker build instead.

If you've already built your image on shippable, the way to avoid building a second time on EB is to add a `.ebignore` file to your project that lists your dockerfile.  

Actually when I run an eb docker project, I have an `.ebignore` file that looks like this:
```
*
!Dockerrun.aws.json
!.ebextensions/*
```

This ignores my entire repo, except for the Dockerrun and the .ebextensions directory.  Since the image is already built on shippable, and you just have to pull and run it, sending the rest of the repo doesn't help.

Maybe you can give this a try.  In the meantime, we'll look for a reason why the name/tag replacement might be failing.

**Comment by bobbydeveaux** [comment] 2016-05-19 19:24
Adding Dockerfile to .eignore is perfect and exactly what I want to do! Thank you! 

However, the bug regarding the image tag and build not being replaced in Dockerrun.aws.json ... Would be awesome if that could be patched!!

Thanks again for you help, much appreciated

**Comment by trriplejay** [comment] 2016-05-20 01:01
I can't seem to reproduce the issue you experienced. Maybe you can try a build again now that you've ignored the Dockerfile and see what happens?

**Comment by bobbydeveaux** [comment] 2016-05-20 08:10
Built again. It pushed a zip file to S3 with just my Dockerfile.aws.json - which is great.

**however** - the file is empty!

**Comment by bobbydeveaux** [comment] 2016-05-20 09:05
Example build here:
https://app.shippable.com/runs/573eccf36138aa0c00a7694f

You can see I've added a 'cat Dockerfile.aws.json' in the post_ci step which shows this file:

```
{
  "AWSEBDockerrunVersion": "1",
  "Image": {
    "Name": "<IMAGE_NAME>:<TAG>",
    "Update": "true"
  },
  "Ports": [{
    "ContainerPort": "80"
  }],
  "Volumes": [
  ]
}
```

**Comment by bobbydeveaux** [comment] 2016-05-20 15:19
Further info, regardless of what I put in the Dockerrun.aws.json.. it gets wiped out now:

Build
https://app.shippable.com/runs/573f2968d352450c0085574b

**Comment by bobbydeveaux** [comment] 2016-05-20 15:31
Currently using the free tier, but would like to pay for more builds & pipelines.. Really need this to be working to use Shippable.

**Comment by trriplejay** [comment] 2016-05-20 18:27
Hey, we've found the problem. Should have a fix out by end of day.  I'll update this issue when it's available.

**Comment by bobbydeveaux** [comment] 2016-05-20 20:06
Excellent, thanks @trriplejay - much appreciated! :)

**Comment by trriplejay** [comment] 2016-05-20 21:48
fix is available now. Let me know if you run into any other issues!

**Comment by bobbydeveaux** [comment] 2016-05-20 22:16
Working perfectly! Thanks :)

**Comment by manishas** [comment] 2016-05-21 18:28
closing this issue since it is fixed.

**Closed by manishas** 2016-05-21 18:28 UTC
Labels: cs, resolved, technical issue
