### ISSUE TITLE
Cannot delete project

### ISSUE THREAD

**Issue by sethamclean** [Shippable/support#1965] opened 2015-10-22 12:39 UTC
Deleting a project seems to fail because the bitbucket webhook shippable is attempting to delete does not exist.

```json
{"id":1004,"message":"deleteHook Failed for WebHookId: 7241698","methodName":"|common|bitbucket|delWebHook|**reponame**|_deleteHook","link":{"statusCode":500,"data":"{\"error\": {\"message\": \"badly formed hexadecimal UUID string\", \"id\": \"7858467b0ec6405fae97e0414d56dac2\"}}"}}
```

**Comment by avinci** [comment] 2015-10-22 13:36
@sethamclean we are having issues with bitbucket for the last couple of days. Adding our dev into the ticket...

@kanthchandra can you look into this and make sure its not a problem on our side. I know we have made some updates to this processing in the last few days.

**Comment by sethamclean** [comment] 2015-10-22 13:51
I have also confirmed that the webhook/service does not exist in bitbucket.

**Comment by avinci** [comment] 2015-10-22 13:54
@kanthchandra I think we are aggressively looking for a hard delete. I think we should not be failing on this delete fail from BB. Can you confirm that our error handling treats this as warning as opposed to failing the delete

**Comment by kanthchandra** [comment] 2015-10-22 15:03
@sethamclean as @avinci pointed out the problem is we are not correctly handling the case where the webhook was already deleted or when Bitbucket gives an error when trying to delete the webhook. We will have the fix for this in a day and let you know about it.

**Comment by sethamclean** [comment] 2015-10-22 15:49
@kanthchandra That was my suspicion. Thanks for the quick response and turn around!

**Comment by kanthchandra** [comment] 2015-10-23 15:42
Hi @sethamclean @avinci Since bitbucket was having issues throughout the day today we couldn't do much on this today, we will try to get this issue resolved at the earliest. Sorry about the delay.

**Comment by sethamclean** [comment] 2015-10-26 14:12
This seems to be working. I am having additional issues but will file another defect.

**Comment by avinci** [comment] 2015-10-26 14:40
thanks @sethamclean will be happy to help on your other issues

**Closed by avinci** 2015-10-26 14:40 UTC
Labels: bug, resolved
