### ISSUE TITLE
have no permission to see builds

### ISSUE THREAD

**Issue by romand** [Shippable/support#1035] opened 2015-02-05 19:08 UTC
I'm collaborator on https://github.com/ValuationMetrics/Valuation-Metrics repo, but I can't see its shippable builds.
https://app.shippable.com/builds/54d3abd308ac4d0e00c897b5
![2015-02-05-160654_1920x1080_scrot](https://cloud.githubusercontent.com/assets/1204410/6067133/0acc4284-ad51-11e4-8bff-5d0407003c6b.png)
https://app.shippable.com/subscriptions/540e78303479c5ea8f9e9819
![2015-02-05-160737_1920x1080_scrot](https://cloud.githubusercontent.com/assets/1204410/6067145/250c1b42-ad51-11e4-9da1-357f0cb458fc.png)

**Comment by pwalsh** [comment] 2015-02-06 07:16
I just came for the exact same issue. I have added someone as a collaborator on a private project in my repository. He cannot see builds in Shippable.

**Comment by manishas** [comment] 2015-02-06 17:53
@romand couple of qs - are private repos enabled for your shippable account? You can figure this out by looking at the 'Private repos' at the top right of your dashboard. These should be set to 'on'. 
One private repos are enabled, can you click on the 'sync account' button on your dashboard? 

Please let me know if you still cannot see the orgs.

@pwalsh can you ask @zhenyab to follow the steps above as well?

**Comment by romand** [comment] 2015-02-06 18:02
today I see the build from the repo (despite 'private repos' being off at start)
not closing issue because others may still have it

**Comment by zhenyab** [comment] 2015-02-06 19:53
Thank you, I see the builds and I can run the builds, but:
1. I can't delete builds
2. builds I run never end, even if all tests passed successfully.

**Comment by manishas** [comment] 2015-02-06 21:37
@zhenyab you cannot delete builds because you're a collaborator for the repo. You can only delete if you're an owner.

Can you point me to a build that never ended even though tests passed? Do you have something in your scripts that waits for user input? Can you please share your shippable.yml?

**Comment by zhenyab** [comment] 2015-02-06 22:04
@manisha, please find below all the information:

This is the link to such build example: https://app.shippable.com/builds/54d5118521e8ee0e00db5757

Here the script:
```
language: php

php:
  - 5.5
  - hhvm

install:
  - composer install

before_script:
  - cp .env.shippable .env
  - mkdir -p shippable/testresults
  - mkdir -p shippable/codecoverage
  - mysql -e 'create database stickyz;'

script:
  - php artisan migrate
 # - php artisan db:seed
  - phpunit --log-junit shippable/testresults/junit.xml --coverage-xml shippable/codecoverage

notifications:
  email:
```
Here run only one simple test.

Thank you!

**Comment by pwalsh** [comment] 2015-02-07 19:08
Just confirming: I've tried to re-run a build that @zhenyab did in our private repo (he collaborates on my repo). The test passes, and then something goes wrong. At time of writing, the build has been "processing" for 25 mins: https://app.shippable.com/builds/54d65cbf5e46b00e000f88f5

**Comment by pwalsh** [comment] 2015-02-10 11:14
@manishas ?

**Comment by pwalsh** [comment] 2015-04-26 06:46
@manishas or @anyone - we still have the problem described here on February 7th.

**Comment by manishas** [comment] 2015-04-26 07:21
@pwalsh sorry for the delay!

tagging @rageshkrishna - can you please take a look? thanks!

**Comment by rageshkrishna** [comment] 2015-04-27 06:53
@pwalsh This appears to be something specific to phpunit's code coverage processing. I still don't have an exact root cause for this problem, but can you try the solution in https://github.com/Shippable/support/issues/1263#issuecomment-88907061 and see if it works for you?

**Comment by manishas** [comment] 2015-06-27 01:41
Closing. Please re-open if you're running into this still.

**Closed by manishas** 2015-06-27 01:41 UTC
Labels: question, triaged
