### ISSUE TITLE
Sample application doesn't push to my docker hub

### ISSUE THREAD

**Issue by eric-naguras** [Shippable/support#2492] opened 2016-04-06 10:06 UTC
I'm trying to follow the Deploy A Sample Application tutorial.
All seems to go well except at the end there is an error:
Error response from daemon: could not find image: no such id: ericnaguras/micro-www:latest

Do you need to make the repositories upfront in docker yourself?

Any help would be appreciated.

eric-naguras/micro-sample/master.4

[5704da6e018a420c0038b0fb.log.zip](https://github.com/Shippable/support/files/206164/5704da6e018a420c0038b0fb.log.zip)

[shippable.yml.zip](https://github.com/Shippable/support/files/206168/shippable.yml.zip)

**Comment by rageshkrishna** [comment] 2016-04-06 10:36
Hi @eric-naguras. The problem is that your docker build is doing this:

````
docker build -t naguras-docker/micro-www
````

but you are trying to tag something else:

````
docker tag -f ericnaguras/micro-www:latest ericnaguras/micro-www:$BRANCH.$BUILD_NUMBER
````

I think this line should be:

````
docker tag -f naguras-docker/micro-www ericnaguras/micro-www:$BRANCH.$BUILD_NUMBER
````

**Comment by eric-naguras** [comment] 2016-04-06 10:46
Thanks for your info.
I’ll give it a try.

I guess someone needs to update the tutorial then.

**Comment by eric-naguras** [comment] 2016-04-06 10:56
Now I get an other error: Integration name specified in yml does not match integrations present in project settings: my_docker

I deleted the integration I made earlier and created a new one named my_docker.

 on_success:
       - cd ..
       - cd micro-www && docker build -t naguras-docker/micro-www .
       - docker tag -f my_docker/micro-www:latest ericnaguras/micro-www:$BRANCH.$BUILD_NUMBER 
       - docker tag -f my_docker/micro-api:latest ericnaguras/micro-api:$BRANCH.$BUILD_NUMBER
       - docker push ericnaguras/micro-api:$BRANCH.$BUILD_NUMBER
       - docker push ericnaguras/micro-www:$BRANCH.$BUILD_NUMBER
integrations:
    hub:
        - integrationName:  my_docker
          type: docker

**Comment by rageshkrishna** [comment] 2016-04-06 11:03
It's not enough to create the account integration. You also need to go to the project settings page and enable the integration on the project by selecting it from the "Integrations" panel.

**Comment by eric-naguras** [comment] 2016-04-06 11:05
I did that too.

**Comment by rageshkrishna** [comment] 2016-04-06 11:11
OK, I think I see the problem here. You have created an integration for "Private Docker Registry". This is intended to work with custom deployments of the registry. If you are using Docker Hub, please choose "Docker" as the type of integration when you create the account integration.

**Comment by eric-naguras** [comment] 2016-04-06 12:58
Hi Ragesh,

I managed to finish the build, thanks for your help.
I made a mistake somewhere else in the shippable.yml file.

Can I ask you for some guidance?

I want to have a production and a beta server.

How would I do this with Shippable?

When I add some new features to my service that I first want in the beta service do I make a branch in git first?
If so, how would I organise the builds?

Can you point me to some examples or other documentation?

So far I only need to have repositories built. I’m using Docker Cloud to update containers.
But do I understand it correctly that Shippable can also do that? 
Is Shippable an alternative to Docker Cloud?

Hope you can help me save some time.

Cheers,
eric

**Comment by avinci** [comment] 2016-04-06 14:57
@eric-naguras I think the best way would be to setup a demo. I am happy to walk through it and also show you what we do internally at shippable as we use our product to build our product :-) 

my email is avi@shippable.com if you would like to the conversation offline.

**Comment by manishas** [comment] 2016-04-06 20:30
I am closing this issue since it is resolved. @eric-naguras as Avi mentioned, please reach out to him to discuss the best way to set up your deployments.

**Closed by manishas** 2016-04-06 20:30 UTC
Labels: cs, resolved, technical issue

**Comment by eric-naguras** [comment] 2016-04-09 02:12
Hi Avi,

Thanks for your email.

I would love to get some guidance on how to use the Shippable CI/CD service to fit our workflow.

I have succeeded in doing some of the most urgent things already and my production/test deployments 
Are working the way I want them to.

I’m thinking of moving all our build processes to the cloud, as much as possible.
Although we have some builds for Mac and Windows, I don’t think they can be done in Docker.

I want to play around a little bit more and when I get stuck, come to you with some very specific questions.

One thing I would like to know more about is how would Shippable compare to Docker Cloud.
Can it also provision nodes (virtual machines) and start and stop services on those nodes?

I really like Docker Cloud but if we an do everything within one toolset, I would prefer that.

Kind regards
eric
