### ISSUE TITLE
ECR Login Issue

### ISSUE THREAD

**Issue by deanmraz** [Shippable/support#2703] opened 2016-06-14 01:43 UTC
Keep seeing an issue where ECR login doesn't work, but triggering a rebuild allows it to run. 

Doesn't work: https://app.shippable.com/runs/575f609e5a31ce0d00a34fb1

Works: https://app.shippable.com/runs/575f60b75198350c00f8920d

**Comment by pranaypareek** [comment] 2016-06-14 14:11
I wasn't able to reproduce the ECR Login failure on either Shippable nodes or Custom nodes.

(The affected builds in question are running on custom nodes)

The problem here is sporadic as it doesn't affect all builds that use ECR login. This _might_ be a config issue with the node itself.

---------------------------------------------------------

Notes from investigation:

##### From https://forums.aws.amazon.com/thread.jspa?threadID=223958,

* This might be a transient network issue.

* External routes might be inaccessible by the docker daemon due to the node being behind a proxy or if you're using a VPN.

---------------------------------------------------------

##### From https://github.com/docker/docker/issues/18842 (related to docker)

* This might be a deeper issue with Docker itself related to its embedded DNS server (https://github.com/docker/docker/issues/18842#issuecomment-209684566)

* The fix for this was pushed in Docker 1.11.1 (https://github.com/docker/libnetwork/issues/1113)

* We are currently using 1.9.1 so the fix isn't available yet.

---------------------------------------------------------

@manishas would you please let me know how to proceed further here?

**Comment by deanmraz** [comment] 2016-06-14 22:37
@pranaypareek thanks for the info, I'm using DigitalOcean.

**Comment by manishas** [comment] 2016-06-16 21:36
@deanmraz is this still happening? We haven't been able to repro this or find a root cause and at this point, I am inclined to defer it unless it's happening consistently and/or more folks complain about it. Let me know.

**Comment by manishas** [comment] 2016-06-23 18:36
Closing this. @deanmraz let us know if you still help with this.

**Closed by manishas** 2016-06-23 18:36 UTC
Labels: need info from customer, technical issue
