### ISSUE TITLE
Build stuck on  Running job on on-demand node pool: default_node_pool. Timeout after 1 hour

### ISSUE THREAD

**Issue by schumannd** [Shippable/support#4637] opened 2018-11-01 14:59 UTC
our last successful build was on 25.9. since the 30.10. all our builds time out.
Since there has been a release on monday, could it be related to that?

We use bitbucket integration, but also manual rebuilds simply timeout.

**Comment by a-murphy** [comment] 2018-11-01 15:56
Since it sounds like this is a Bitbucket project, and it doesn't appear that your GitHub user has ever logged into Shippable, would you mind including some way for us to identify your project?  We have not seen an increase in timeouts overall, so it is most likely something specific to your subscription or project.

Any of the following would help us identify which project you are having trouble with:
  * the name of a Bitbucket user with access to the project
  * the name of the subscription containing the project
  * the "Subscription Id" from the bottom of the subscription dashboard
  * the "Project Id" from the bottom of the project dashboard (this is usually preferred if you don't want to expose any names publicly for a private project)

Obviously, we don't need all of those, but any one of those pieces of information is usually enough to identify the project so that we can see what may be happening.

**Comment by yulianovdey** [comment] 2018-11-01 17:43
Unfortunately we're having the same issue. Here is one build that timed out: https://app.shippable.com/github/ExecThread/ExecThread/runs/9048/1/console

Let me know if there is any other info I can provide.

**Comment by trriplejay** [comment] 2018-11-01 17:53
we're investigating. thanks for the info.

**Comment by trriplejay** [comment] 2018-11-01 18:28
@yulianovdey This appears to be resolved now. Let me know if you see this issue again.

@schumannd hopefully the root cause for your timeout was the same and is now corrected, but let us know if you're still having problems (and link us to the build).

**Comment by yulianovdey** [comment] 2018-11-01 19:11
Thanks @trriplejay! Everything looks good on our end.

**Comment by rageshkrishna** [comment] 2018-11-02 07:30
@schumannd I believe the problem has been corrected, so I'm going to close this issue now. Please re-open it if it hasn't been resolved for you. Thanks!

**Closed as completed by rageshkrishna** 2018-11-02 07:30 UTC

**Comment by Borda** [comment] 2019-02-12 19:13
Hello @trriplejay @schumannd, I am facing probably the same issue while building public repo from GitHub, and a few days ago everything was fine... https://app.shippable.com/github/Borda/pyImSegm/runs/316/1/console and https://app.shippable.com/github/Borda/BIRL/runs/533/summary/console

**Comment by a-murphy** [comment] 2019-02-12 20:49
@Borda Your issue appears to be a duplicate of https://github.com/Shippable/support/issues/4744 and not related to this issue.  Provisioning of some nodes was delayed earlier today and is now resolved.
