### ISSUE TITLE
Script fails mid-process

### ISSUE THREAD

**Issue by tomsterritt** [Shippable/support#3785] opened 2017-08-22 11:46 UTC
While mid-zip the logs stop with the following error:

```
ERROR:script_runner - script_runner:Command failed : ssh-agent bash -c 'ssh-add /tmp/ssh/00_sub;ssh-add /tmp/ssh/01_deploy; cd /root && /root/88e20a7d-1612-41b0-af25-21384717b9b4.sh'
Exception Invalid or no script tags received
ERROR:script_runner - script_runner:Command failed : ssh-agent bash -c 'ssh-add /tmp/ssh/00_sub;ssh-add /tmp/ssh/01_deploy; cd /root && /root/88e20a7d-1612-41b0-af25-21384717b9b4.sh'
Exception Invalid or no script tags received
```

Script I'm running:

```
zip -r artifacts.zip artifacts
```

I can't link to the build in a public issue as URLs include details of a private repo.

**Comment by scriptnull** [comment] 2017-08-22 13:50
Hi @tomsterritt,

Could you send your build link to vishnu@shippable.com ? It would be helpful for us.

Thanks.

**Comment by tomsterritt** [comment] 2017-08-22 14:30
Thanks, I've emailed.

If it helps, this has only happened after specifying a node version. If I leave it default it seems to work.

**Comment by a-murphy** [comment] 2017-09-06 21:46
We've seen this occur when there is a command that suddenly outputs a lot to the console.  We suggest adding `-q` to the zip command to reduce the output.

This is likely a duplicate of https://github.com/Shippable/support/issues/3450.

**Comment by manishas** [comment] 2018-04-25 01:13
@tomsterritt i hope the suggestion above helped mitigate this issue. Closing since there is already a console logs issue open and this is likely a duplicate.

**Closed by manishas** 2018-04-25 01:13 UTC
Labels: resolved
