### ISSUE TITLE
Pull request builds trigger deployment 

### ISSUE THREAD

**Issue by npahucki** [Shippable/support#2464] opened 2016-03-30 21:30 UTC
So, I noticed a feature today that was both cool and not so cool at the same time. I made a PR against our develop branch. Shippable did a build where the PR is merged in to develop and shows the status in the PR, letting us know that all the tests passed, etc. This is really cool. 

The not so cool part: it merged the pull into develop and proceeded to create another build with the tag develop.225 (the last develop build was 224). However, because this matches our autodeploy pattern of develop.*, it caused our development machine to have the result of the PR deployed to it. It was a little confusing at first trying to figure out what happened in this isolated case, but imagine several developers working on several feature branches all making PRs close in time. You can see that these would all overwrite each other in a last-one-wins manner and what would be running on our development server does not match what anyone expects. 

Is there a way to 

1) avoid deployment in the case of a PR
2) use a different tag for the PR triggered builds (not the name of the branch being merged into) which would avoid an unintentional deployment. 

Thanks.

**Comment by trriplejay** [comment] 2016-03-30 21:50
There are two environment variables you can reference from your yml to help you decide whether or not to push (or how to tag your image):
IS_PULL_REQUEST, and PULL_REQUEST

IS_PULL_REQUEST is a simple true/false, while PULL_REQUEST will contain the actual pull request number (or it will be falsy if not a PR).

For a more comprehensive list of our environment variables, check out our docs here:
http://docs.shippable.com/ci_configure/#using-environment-variables

**Comment by manishas** [comment] 2016-03-31 05:52
@npahucki I am closing this issue since your question was answered and this should help you avoid pushes to Docker registry for pull request builds and hence avoid your environment from being automatically updated.

I am closing this issue, but please do let us know if you have any questions.

**Comment by npahucki** [comment] 2016-03-31 10:03
Ok, this is a good start, however I don't see mentioned in the docs what I could actually do with this env var. The shippable.yml is declarative and not a scripting language, so I am not putting together how to conditionally skip pushing the build to the repo. Please point me to some docs that would indicate how to conditionally executes things based on an env var in a shippable.yml.

**Comment by rageshkrishna** [comment] 2016-03-31 10:13
@npahucki You are free to use valid bash syntax in your YML file. Something like this:

````
build:
  ci:
    - if [ "$IS_PULL_REQUEST" == false ]; then ./doSomething.sh; fi
````

**Comment by npahucki** [comment] 2016-03-31 13:47
Thanks, that would let me run one command, how would I skip the entire post_ci section which consists of multiple lines (each starting with a dash). Surely I can not wrap all the lines or the entire post_ci section in an 'if' as that would not be valid YML.

**Comment by npahucki** [comment] 2016-04-01 21:22
Hello? Anyone going to address the above comment?

**Comment by manishas** [comment] 2016-04-01 21:39
@npahucki sorry for the delay. I have reopened this issue so that it is on the radar.

I was thinking through your case, and you can do (2) use a different tag for the PR triggered builds (not the name of the branch being merged into) which would avoid an unintentional deployment.

In your yml, you can use the IS_PULL_REQUEST variable to tag the image differently if its a pull request, so that it doesn't get picked up by auto-deploy. Let me know if that works for you...

**Comment by npahucki** [comment] 2016-04-01 22:11
This is what I have essentially done, but it is very very nasty and I had to hack around the fact that an 'export' is added in front of all the env vars combined with the fact that bash has no real ternary operator. 

Here is the nastiness for your amusement: 

env:
  global:
    # DUMMY just gets exported - a NOOP essentially
    - DUMMY && test $IS_PULL_REQUEST == true  && NEW_DOCKER_TAG="${BRANCH/\//_}-pr$PULL_REQUEST" || NEW_DOCKER_TAG="${BRANCH/\//_}.$BUILD_NUMBER"
    - NEW_DOCKER_IMAGE=728892293674.dkr.ecr.us-east-1.amazonaws.com/execthread/web-app:$NEW_DOCKER_TAG

**Comment by manishas** [comment] 2016-04-04 03:14
I am closing this issue since there is a way to configure the yml to skip deployments for PR builds. I'll look into this some more tomorrow to see if there is a cleaner way to do this.

**Closed by manishas** 2016-04-04 03:14 UTC
Labels: cs, technical issue

**Comment by bittner** [comment] 2016-05-23 13:21
@manishas Can you give a concrete example on how skipping deployments for PRs is configured?

I've seen how to [exclude branches for builds](http://docs.shippable.com/ci_configure/#includingexcluding-branches#using-environment-variables#includingexcluding-branches), but I want the builds to happen on PRs. Only deployment should not be triggered (unless the PR or branch is merged into `master`).

We have an `after_success:` section in our `Shippable configuration that looks like this:
``` yaml
script:
  - python setup.py test
after_success:
  - if [[ "$BRANCH" == "master" && ! "$PULL_REQUEST" ]]; then ssh deployment@example.com /opt/example/scripts/setup.sh $BRANCH; else echo "Skipping deployment for branch $BRANCH."; fi
```
Unfortunately, since `PULL_REQUEST` is not `false` when a PR is merged into master this now even skips deployment when it actually should take place! When the PR is merged into `master`.

How do we have to configure Shippable for the deployment to be triggered correctly?

**Comment by bittner** [comment] 2016-05-26 00:00
@manishas @rageshkrishna Any hint on how to configure this correctly?

**Comment by rageshkrishna** [comment] 2016-05-26 03:29
@bittner I think what you need is the `IS_PULL_REQUEST` env var, which will contain `true` or `false` values all the time. `PULL_REQUEST` will contain the pull request number whenever `IS_PULL_REQUEST` is true.

**Comment by bittner** [comment] 2016-05-26 08:12
@rageshkrishna The problem lies somewhere else:

1. Shippable is running a build on _both_ the feature branch and the main branch, and in both cases `PULL_REQUEST` and - as you say - `IS_PULL_REQUEST` is set. -- *This is fine! A build on, say, `master` is run, but I can detect that the changes are not "really" there, this is  just a "test integration" run.*
2. However, when you **merge** a PR Shippable runs he build on the main branch again, which is fine, but also here `PULL_REQUEST` - and obviously `IS_PULL_REQUEST` - are set. -- *This is not a PR any more; this is a build on the main branch.*

There should be no `PULL_REQUEST` environment variables set in a build that is running on the main branch after the change sets have been integrated. Or do you have a different concept of this, and different / additional variables to check for?

**Comment by rageshkrishna** [comment] 2016-05-26 09:45
I see the confusion now... `PULL_REQUEST` and `IS_PULL_REQUEST` will actually have the value `false` when the merged build is run. The problem is in your bash condition. You need to explicitly check for `[ "$PULL_REQUEST" == false ]` instead of doing `[ ! "$PULL_REQUEST" ]`

**Comment by bittner** [comment] 2016-05-29 22:10
@rageshkrishna I can confirm that this works. Thank you!
