### ISSUE TITLE
Build are not executing

### ISSUE THREAD

**Issue by attiam-blueoak** [Shippable/support#4617] opened 2018-10-22 02:50 UTC
The build for several projects are not being executed and showing an error that is not clear as to what needs to be the resolution.

Example build where we are having this issue are:
https://app.shippable.com/github/attiam-blueoak/BlueBillingBanking/runs/388/1/console
https://app.shippable.com/github/attiam-blueoak/BlueBillingCRM/runs/495/1/console

Please note, this problem has started today; we did not have any of this issue last week.

We would appreciate if you could look into this issue promptly as we are nearing a release that is already behind schedule.

**Comment by rageshkrishna** [comment] 2018-10-22 03:04
@attiam-blueoak GitHub has been reporting errors from around 4 hours ago: https://status.github.com/messages. I believe this is the root cause of the problem.

**Comment by trriplejay** [comment] 2018-10-23 16:25
closing as the github issues are resolved. please let us know if you're still having problems.

**Closed as completed by trriplejay** 2018-10-23 16:25 UTC
