### ISSUE TITLE
Not able to receive any email notification about build failure or status change

### ISSUE THREAD

**Issue by phagunbaya** [Shippable/support#980] opened 2015-01-16 23:50 UTC
Not able to receive any email notification about build failure or status change with following config

notifications:
     email:
         recipients:
             - dev-one@org.com
             - dev-two@org.com
         on_success: change
         on_failure: always

**Comment by manishas** [comment] 2015-01-17 19:41
@phagunbaya can you please validate your yml at http://www.yamllint.com/

I want to make sure there isn't a typo somewhere.

**Comment by phagunbaya** [comment] 2015-01-17 19:44
@manishas : I did check that it is a valid yml.

**Comment by manishas** [comment] 2015-01-17 19:46
can you send me the yml and also point me to a build that failed and did not trigger an email?

Please send to manisha@shippable.com

**Comment by manishas** [comment] 2015-01-17 19:47
also, are you seeing this across repositories or for a specific repo?

**Comment by phagunbaya** [comment] 2015-01-17 19:53
@manishas : Mail sent ! I just applied email notification config to just 1 repo and it even did not sent email to committer.

**Comment by manishas** [comment] 2015-01-28 22:52
@phagunbaya we cannot reproduce this at our end. Is it still happening?

**Comment by phagunbaya** [comment] 2015-01-29 03:33
@manishas : This happens only when we mention two emails. For single email it works.

**Comment by manishas** [comment] 2015-03-29 16:43
@phagunbaya is this still a problem? Sorry for the long wait!

**Comment by phagunbaya** [comment] 2015-03-30 10:31
@manishas : Yes it is still happening. I tried setting "on_success: always" but did not receive any notification.

**Comment by manishas** [comment] 2015-07-03 04:31
@phagunbaya I think this keeps falling off the radar for some reason. Really sorry about that!

Can you set up a call with us from https://shippable.youcanbook.me/ ?

If you're working from india, please select a time that works for you IST and I will ask someone from our team in India to help debug over a call.

**Comment by phagunbaya** [comment] 2015-07-03 05:30
@Thanks !

**Comment by manishas** [comment] 2015-07-09 20:05
This has been addressed, so closing.

Shippable only sends notifications to email addresses configured for the account in GitHub. If you specify an email address in the yml that is not a part of your GitHub config, we do not send emails to that address.

**Closed by manishas** 2015-07-09 20:05 UTC
Labels: bug, triaged
