### ISSUE TITLE
Please can we have support for CCtray/CCMenu?

### ISSUE THREAD

**Issue by toby-griffiths** [Shippable/support#1031] opened 2015-02-05 13:43 UTC
Hi there,

I use CCTray to monitor the status of all my open source projects on Travis.  Could you please add this feature to Shippable so I can use it for my private projects?

Thanks :o)

**Comment by manishas** [comment] 2015-02-06 17:56
We'll definitely consider adding support for this. 

This issue is a duplicate of #604 so closing as dup. we will track both requests in the original issue.

**Closed by manishas** 2015-02-06 17:56 UTC
Labels: duplicate, feature request

**Comment by toby-griffiths** [comment] 2015-02-06 18:26
Oops. Sorry. That's was me too. Guess I must really want it ;-)

Toby Griffiths
Cubic Mushroom
m: 07533 777371
e: toby@cubicmushroom.co.uk  |  skype: toby_griffiths  |  tw: @cubicmushroom

> On 6 Feb 2015, at 17:56, Manisha <notifications@github.com> wrote:
> 
> We'll definitely consider adding support for this.
> 
> This issue is a duplicate of #604 so closing as dup. we will track both requests in the original issue.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

-- 

Cubic Mushroom Ltd. is a company registered in England and Wales. 
Registered number: 7891099. Registered office: Unit G9 Castle Cavendish 
Business Centre, Dorking Road, Nottingham NG7 5PN.  VAT Registration 
Number: GB 199 6865 21
