### ISSUE TITLE
docker build is happening several times during pre CI workflow

### ISSUE THREAD

**Issue by manishas** [Shippable/support#2023] opened 2015-11-12 23:14 UTC
https://app.shippable.com/builds/564467ec7d9a840d00a9cb2d

Something is going into an infinite loop and the docker container is being built again and again....

**Comment by manishas** [comment] 2015-11-12 23:42
assigning to @ric03uec

**Comment by ric03uec** [comment] 2015-11-13 17:34
i'm investigating this but haven't been able to get to the exact cause. there are few probable causes which i'll look into today. will update once i have more info

**Comment by ric03uec** [comment] 2015-11-13 23:49
@fabiocarneiro can you please trigger the build on the project and try again. i'm not able to re-run a build on the `sha` that was causing this issue on your repo. it was probably rebased or removed.
thanks

**Comment by fabiocarneiro** [comment] 2015-11-16 10:17
Well, I triggered another one and it seems to work now. https://app.shippable.com/builds/5648cfac15227c0d004b16ca
Did you change something?

**Comment by ashernevins** [comment] 2015-11-19 04:46
@ric03uec

I am now experiencing this bug. Cancelled the first build and started another with the same issue. Current build is https://app.shippable.com/builds/564d40139f59620d00190378

Unlike fabiocarneiro this is not a pull request build.

Has anyone found a workaround for this until the bug is fixed?

**Comment by rageshkrishna** [comment] 2015-11-19 07:51
@fabiocarneiro @ashernevins Did you happen to notice whether there is a long delay between the end of the docker build completing and the next part of your build starting to run? I think I may have identified where the problem is happening but need your input to confirm whether this is really what you are running in to.

**Comment by ashernevins** [comment] 2015-11-20 03:56
@ric03uec There is some delay yes, approximately 1-2 minutes.

**Comment by JADurham909** [comment] 2015-11-20 04:48
I just posted another bug about this very issue before reading this.

https://github.com/Shippable/support/issues/2064

**Comment by manishas** [comment] 2015-11-20 05:03
I am raising priority on this issue. @rageshkrishna we have to take a look at this asap

**Comment by rageshkrishna** [comment] 2015-11-20 09:04
I've identified the underlying problem. We were having some issues with RabbitMQ and upgraded to a newer version a couple of days ago. Unfortunately, we did not notice that the default connection timeout was dropped from 580s to 60s in this release. As a result, messages are timing out and being redelivered when they really shouldn't be. This, coupled with what I think is a bug in the AMQP client we are using in our python microservices, is what is causing all of these issues.

I'm looking in to how we can fix this now and will update this issue as soon as I can confirm an ETA for this fix.

**Comment by rageshkrishna** [comment] 2015-11-20 19:47
We've deployed a fix for this.

@fabiocarneiro @ashernevins @JADurham909 Please let me know if you still run in to this.

**Comment by JADurham909** [comment] 2015-11-20 22:05
Testing it now

**Comment by JADurham909** [comment] 2015-11-20 22:47
Not sure this is related... but I cannot push to docker now.

  sudo docker push adexchangegrp/aeg-affiliate-portal-app:master.174 2>/tmp/push-error.txt
The push refers to a repository [adexchangegrp/aeg-affiliate-portal-app] (len: 1)
22ee36e0c564: Buffering to Disk
22ee36e0c564: Image push failed
  echo -e 'Error pushing to registry: Server error: unexpected 500 response status trying to initiate upload of adexchangegrp/aeg-affiliate-portal-app'
Error pushing to registry: Server error: unexpected 500 response status trying to initiate upload of adexchangegrp/aeg-affiliate-portal-app

**Comment by JADurham909** [comment] 2015-11-20 22:48
I see the build numbers are not aligning with the docker tags now.  I will cancel a few builds and try again.

**Comment by JADurham909** [comment] 2015-11-20 22:55
I think docker hub is having problems at the moment.  Nothing will push.

**Comment by ashernevins** [comment] 2015-11-23 02:33
Working for me. Thanks.

**Comment by avinci** [comment] 2015-11-23 03:06
closing as this is resolved.

**Closed by avinci** 2015-11-23 03:06 UTC
Labels: bug, resolved
