### ISSUE TITLE
Logging back into Shippable is painful

### ISSUE THREAD

**Issue by schmmd** [Shippable/support#684] opened 2014-10-17 15:52 UTC
I frequently click links from emails about failed builds.  They go directly to the URL of the build.  However, I often need to reauthenticate (which is fairly easy--I just click "GitHub").  However, after reauthentiacation I an directed to Shippable's main page and I need to go back to my email and click the original link.

**Comment by schmmd** [comment] 2015-02-11 04:18
Yes, this still happens.

**Comment by schmmd** [comment] 2015-02-11 04:34
@jkinkead can you elaborate on this issue?  I have not been using Shippable as much lately and I think this might be fresher in your mind.

**Comment by jkinkead** [comment] 2015-02-11 20:43
I tried reproducing just now with a fresh browser session, and couldn't. I can't say with certainty that this has happened since the start of the year, but I'll update this issue if I see it again.

**Comment by manishas** [comment] 2015-02-11 20:46
thanks for checking. i will close this issue for now, but if you see this happen or anything funny with reauth again, please re-open and we can test out your exact scenario.

**Closed by manishas** 2015-02-11 20:46 UTC
Labels: bug, triaged

**Comment by mbrodala** [comment] 2015-11-12 11:18
I see this all the time with Bitbucket. We have set up notifications in a Slack channel and the first build link I follow per day always redirects me to the start page (apparently due to performing authentication in this very moment). Clicking the same link a 2nd time then opens the build as expected.
