### ISSUE TITLE
Issue installing npm modules globally

### ISSUE THREAD

**Issue by phagunbaya** [Shippable/support#4093] opened 2018-01-27 02:58 UTC
I have started noticing errors while installing node modules globally with the recent upgrade (drydock/genexec:v6.1.4).

Link to the build: https://app.shippable.com/github/Falkonry/systems/runs/2324/1/console

Error snippet
```
/root/.nvm/versions/node/v7.10.1/bin/ng -> /root/.nvm/versions/node/v7.10.1/lib/node_modules/@angular/cli/bin/ng

> node-sass@4.7.2 install /root/.nvm/versions/node/v7.10.1/lib/node_modules/@angular/cli/node_modules/node-sass
> node scripts/install.js


module.js:340
    throw err;
          ^
Error: Cannot find module '/root/.nvm/versions/node/v7.10.1/lib/node_modules/@angular/cli/node_modules/node-sass/scripts/install.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
```

I'm running this command `npm install -g @angular/cli`. I don't understand why the upgrade would break my builds. Impacting our production environment.

**Comment by rageshkrishna** [comment] 2018-01-27 04:40
@phagunbaya It seems very unlikely that this is related to the genexec version changing, because that component is mainly responsible for spinning up your build container, which it appears to be doing without any issues.

I noticed that your build is running on `drydock/u14nodall:prod`. This is an _extremely_ old and unsupported image that has not seen any updates in well over a year now. I think your problems are most likely related to some dependencies in this image no longer being compatible with the latest versions of the npm packages that you are using.

I would first try changing your build image to use either `drydock/u14nodall:v6.1.4` (released 2 days ago) or `drydock/u14nodall:v5.10.4` (released 3 months ago) to see if it helps resolve this issue. If this doesn't help, please share your `package.json` and, if possible, the contents of your `setup.sh` file. You can send them to ragesh@shippable.com.

**Comment by rageshkrishna** [comment] 2018-01-27 04:49
@phagunbaya I just took a look at your older builds and noticed that you have been getting the same error at least all the way back to 15 January 2018 (I haven't looked at anything older than that), so it's safe to rule out that the genexec upgrade to 6.1.4 is the root cause of the issue, because that was released only a couple of days ago.

I also noticed that despite this error, your build script continues to execute and reports a successful build. You might want to check the error handling in your `setup.sh` script to ensure that it exits correctly on errors.

The recommendation in my previous comment still holds -- please update to a more recent drydock tag so we can debug this in a supported image.

**Comment by phagunbaya** [comment] 2018-02-04 22:02
Upgrading to `drydock/u14nodall:v6.1.4` didn't help. 
https://app.shippable.com/github/Falkonry/systems/runs/2343/1/console

**Comment by rageshkrishna** [comment] 2018-02-05 03:58
Can you point me to the last build that ran everything successfully?

**Comment by phagunbaya** [comment] 2018-02-06 20:37
We started running this command `npm install -g @angular/cli` in the build step early January. Only thing I'm worried about is, it fails on shippable but succeeds locally. npm and node versions are same though. I'll find out. Thanks

**Comment by manishas** [comment] 2018-08-02 03:12
@phagunbaya was this ever resolved?

**Comment by phagunbaya** [comment] 2018-08-02 05:55
This is still an issue but we have the workaround.

**Comment by rageshkrishna** [comment] 2019-01-25 06:17
I'm closing this as there seems to be a resolution. Feel free to re-open if we still need to investigate.

**Closed by rageshkrishna** 2019-01-25 06:17 UTC
Labels: need info from customer, question
