### ISSUE TITLE
Bug in how Shippable git sync behaves on Pull Request event

### ISSUE THREAD

**Issue by pmoust** [Shippable/support#988] opened 2015-01-19 16:19 UTC
When a PR is issued I expect shippable to perform a git sync from BASE repobranch/commit id with PR HEAD branch merged in to perform tests.

*edit* applies on shippable.yml

**Comment by pmoust** [comment] 2015-01-19 16:24
@manishas has described (https://github.com/Shippable/support/issues/940#issuecomment-68789114) the desired behaviour. 
I believe there is a regression somewhere.

**Comment by spyrospph** [comment] 2015-01-20 09:29
Hi,

This is a big fail and is really making our development cycle impossible.

Can this be prioritised?

-S.

**Comment by rageshkrishna** [comment] 2015-01-20 09:53
The builds aren't being triggered because of the following error:
````
 Use of the "privileged" build_image option requires an initialized dedicated host.
````
Can you check the YML file in your PR branches to see if this is the case?

These notifications are surfaced in the "Notifications" tab for the project. We're working on making this more visible, but for now you should be able to see everything listed there.

**Comment by pmoust** [comment] 2015-01-20 09:55
@rageshkrishna the error you mention was during us transitioning to a more powerful dedicated host (~few minutes ago).
We do use privileged mode, and we do use a dedicated host. 

Reference build: 54be217d68606e0e0056dc29

**Comment by pmoust** [comment] 2015-01-20 09:57
To clarify @rageshkrishna, builds are triggered. The issue is on the logic in what is being tested on PR event.

**Comment by rageshkrishna** [comment] 2015-01-20 10:38
I just took a look at that build. If I've understood it correctly, you have a PR from branch `nsync` to branch `next`. Typically for PR builds from branches, we run two builds; one on the `nsync` branch, and one after merging `nsync` into `next`.

At the moment, `nsync` isn't being built because your YML is configured to build only 4 branches.

However, if you look at the git operations on the build that ran, you'll see that it is indeed running the results of merging the HEAD of the PR into `next`:

![build-merged](https://cloud.githubusercontent.com/assets/1134972/5815722/295f137e-a0be-11e4-8959-74d90ed18e8f.png)

It seems to me that it is working as intended. Can you please let me know how this is not meeting your expectation?

**Comment by pmoust** [comment] 2015-01-20 10:48
@rageshkrishna thanks for taking a close look.
Please check https://app.shippable.com/builds/54be1d4568606e0e0056db29

Here the `shippable.yml` fails in a step that should not exist if the merge had taken place properly.
If you check the merge you 'll see `shippable.yml -+11', yet it does run that version of shippable.yml.

If you like we can get in a skype or google hangouts session to speed up the debug process.

**Comment by pmoust** [comment] 2015-01-20 10:57
@rageshkrishna also on your example above, I would expect to be
  a. checkout origin/next
  b. merge origin pull/21317/head into origin next (here git will determine if its fast-forward merge or 3-way merge)
  c. read shippable.yml 
  d. proceed to steps

Now the process is 
  a. checkout in  pull/21317/head
  b. read shippable.yml
  c. merge origin/next
  d. proceed

Am I wrong somewhere?

**Comment by rageshkrishna** [comment] 2015-01-20 10:58
Hmm, I now see what you're saying. It looks like we aren't merging the shippable.yml file before running the build; it's currently picking it up straight from the head of the pull request but merging the rest of the code for the builds. This is definitely a bug at our end. I've already created an issue in our internal tracker for this.

**Comment by pmoust** [comment] 2015-01-20 11:11
@rageshkrishna thanks, the original Issue I raised was misleading.

**Comment by pmoust** [comment] 2015-01-26 12:25
@rageshkrishna any news on this?

**Comment by rageshkrishna** [comment] 2015-01-27 11:31
@pmoust Yes, this fix will be available in a day or two.

**Comment by manishas** [comment] 2015-02-10 00:07
sorry for the delay in fixing this. ETA is before EOD Thursday 2/12.

**Comment by manishas** [comment] 2015-03-09 23:12
this has been fixed. please re-open this issue if it doesn't work for you.

**Closed by manishas** 2015-03-09 23:12 UTC
Labels: bug, triaged
