### ISSUE TITLE
Many failures recently writing to file system

### ISSUE THREAD

**Issue by npahucki** [Shippable/support#3441] opened 2017-03-15 20:28 UTC
`/root/863b8e00-d2bb-4abf-8a2e-ba1b3fc7872a.sh: line 87: echo: write error: Resource temporarily unavailable`

This happens every few builds for the last few days - a rebuild usually works. Highly annoying!

Please fix ASAP.

**Comment by npahucki** [comment] 2017-03-15 20:52
Here is an example, 3rd one in the last hour.

**Comment by stephanielingwood** [comment] 2017-03-16 00:34
Hi @npahucki,

We've spent this afternoon troubleshooting and have yet to find anything substantial. What we've got right now is that a `Resource temporarily unavailable` error can happen when you exceed one or more of the following: 

- Allowed number of threads
- Allowed number of processes
- Memory
- Allowed number of file descriptors
- Stack size

FWIW, though, we haven't been able to create a build that exceeds any one of those yet. 

Would you mind logging the following, after your npm install and before the cp:
- `ulimit -a` (this will give us your allowed limits)
- `lsof | wc -l` (to get current # of file descriptors)
- `ls -1d /proc/*/task/* | wc -l` (current # of processes)
- `free -m` (currently used memory)

Hopefully that can point us in the right direction. Thanks.

**Comment by rageshkrishna** [comment] 2017-03-16 06:24
@npahucki `Resource temporarily unavailable` is a very uncommon error. I suspect a buffering issue in the way we redirect console outputs is the root cause, but the nature of this bug means it's going to take us some time to be even able to reproduce it reliably and then we can start looking at how to fix it.

In the mean time, I would recommend trying to reduce the log level on your `npm install` if you can. Maybe set it to error or warn instead of the default of info. Do you _really_ need all the info logs in the console?

**Comment by npahucki** [comment] 2017-03-16 13:52
One thing worth noting, is that we are using a custom build image that is derived from the standard unbuntu 14.04 and has a few things preinstalled on it (including most of the npm modules that we would otherwise install each build). 

I have included the diagnostic command as requested and will post the results as soon as it fails again (which should be several times today if it continues to follow the same pattern of the last few days).

**Comment by nealeu** [comment] 2017-03-23 15:09
If it's of use, we've had an issue with some file operations dying too.  For us it seems to correlate to us moving to the v5.3.2 build image at https://app.shippable.com/subs/{github|bitbucket}/{repo}/settings/options

I wonder if this change includes changes to the host operating system and Docker version in which our images are run...

**Comment by stephanielingwood** [comment] 2017-03-23 21:55
Hi @nealeu,

Thanks for letting us know. Would you mind sharing a link to a build where that happened?

**Comment by manishas** [comment] 2017-05-09 22:49
@npahucki can you let us know if you're still running into this?

**Comment by npahucki** [comment] 2017-05-10 12:21
We have not seen these failures in a long time now.

**Comment by trriplejay** [comment] 2017-09-06 19:21
closing this since the problem is no longer occurring.

**Closed by trriplejay** 2017-09-06 19:21 UTC
Labels: bug, investigate
