### ISSUE TITLE
New home page doesn't work over https

### ISSUE THREAD

**Issue by coddie001** [Shippable/support#1842] opened 2015-09-03 10:13 UTC
i cant seem to login to shippable as some URl's are loading over http and shippable is opened in https

**Comment by taz77** [comment] 2015-09-03 10:58
You mean the website? Allow mixed mode in your web browser, you probably are using IE right?

**Comment by coddie001** [comment] 2015-09-03 11:21
i am using chrome, when i try to login with a bitbucket account i get the error

**Comment by taz77** [comment] 2015-09-03 11:45
Using Chrome 45 here on a Mac, logging in with Bitbucket. I do have a warning symbol in my URL bar because they use an SHA-1 signature but I am communicating with TLS 1.2.

I run an eCommerce... Deal with SSL certs a lot.

**Comment by lekhab** [comment] 2015-09-03 19:04
@coddie001: are you using https://www.shippable.com? We are not able to reproduce this on our end. Can you attach some screenshots if you are still facing this?

**Comment by coddie001** [comment] 2015-09-07 09:11
i am using https://www.shippable.com, anytime i try to login to bitbucket,
i get an internal server error .

*Error message*


*Mixed Content: The page at 'https://app.shippable.com/error
<https://app.shippable.com/error>' was loaded over HTTPS, but requested an
insecure stylesheet 'http://fonts.googleapis.com/css?family=Open+Sans
<http://fonts.googleapis.com/css?family=Open+Sans>'. This request has been
blocked; the content must be served over HTTPS.*

**Comment by lekhab** [comment] 2015-09-10 18:02
@coddie001: This is a normal console error when a font cannot be downloaded, but it should not block the whole site and should not be an issue at all..do you have any special settings/plugins that causes such an error to block downloading the site itself?

**Comment by lekhab** [comment] 2015-09-10 18:34
also opened an internal issue to resolve this console error on our end.

**Comment by coddie001** [comment] 2015-09-11 07:45
hello lekha,

i dont use any plugins that could have caused this, the font is a google
http link which would not be allowed on an https website therefore causing
an internal server error

**Comment by taz77** [comment] 2015-09-11 07:50
@coddie001 Being I run an eCommerce site, I have a lot of experience with SSL and I use Chrome exclusively. Something has been changed in your installation of Chrome. By default Chrome will allow mixed mode SSL on a website. Have you attempted to use an Incognito window that has all plugins disabled?

**Comment by coddie001** [comment] 2015-09-11 08:00
i have used incognito window so many times, still same error. Can send the
snapshot in

**Comment by taz77** [comment] 2015-09-11 09:15
@coddie001 Have you confirmed that the extensions are off in incognito mode? If you go to your extensions in settings there are check boxes on each one that can make the available in incognito. Like I said, the default installtion of Chrome allows for mixed mode. So something is amist with your browser, it isn't a standard installation of Chrome.

**Comment by lekhab** [comment] 2015-09-14 16:12
the console error has been fixed on our end. are you able to load the website now?

**Comment by coddie001** [comment] 2015-09-15 08:23
Thanks Brady, My error is resolved

**Comment by taz77** [comment] 2015-09-15 10:22
Great!

**Closed** 2015-09-15 13:04 UTC
Labels: bug, resolved, triaged
