### ISSUE TITLE
ImportError: No module named packaging.version

### ISSUE THREAD

**Issue by ryancampbell** [Shippable/support#3316] opened 2017-01-23 23:05 UTC
echo | eb init "acm-risk-alive" -r "us-east-1" -p "64bit Amazon Linux 2016.03 v2.1.3 running Docker 1.11.1" 0s  
Traceback (most recent call last):
  File "/usr/local/bin/eb", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 70, in <module>
    import packaging.version
ImportError: No module named packaging.version

- Link to the build failure
https://app.shippable.com/runs/588653ed11c45a1000af9744/1/console

- shippable.yml

language: node_js
node_js:
  - "5.7.1"

branches:
  only:
    - master
    - staging
    - develop

build:
  ci:
    - nvm use 5.7.1
    - echo 'CI is running'
    - npm install
    - npm install webpack -g
    - npm run build
    - shippable_retry docker build -t "acm-risk-alive:$BRANCH.$BUILD_NUMBER" .
    - docker tag acm-risk-alive:$BRANCH.$BUILD_NUMBER 508647932042.dkr.ecr.us-east-1.amazonaws.com/acm-risk-alive:$BRANCH.$BUILD_NUMBER
    - docker push 508647932042.dkr.ecr.us-east-1.amazonaws.com/acm-risk-alive:$BRANCH.$BUILD_NUMBER
    - pip install --upgrade botocore

integrations:
  deploy:
    - integrationName: "acm-aws"
      type: aws
      target: eb_docker
      application_name: "acm-risk-alive"
      env_name: "acm-risk-alive-$BRANCH"
      bucket_name: "elasticbeanstalk-us-east-1-508647932042"
      region: "us-east-1"
      image_name: "508647932042.dkr.ecr.us-east-1.amazonaws.com/acm-risk-alive"
      image_tag: "$BRANCH.$BUILD_NUMBER"
      platform: "64bit Amazon Linux 2016.03 v2.1.3 running Docker 1.11.1"
  hub:
    - integrationName: "acm-aws-ecr"
      type: ecr
      region: "us-east-1"

**Comment by a-murphy** [comment] 2017-01-24 00:09
It looks like something is wrong with one of the awsebcli dependencies, causing the awsebcli installation to fail.  We have not yet determined which dependency or why it changed.

**Comment by ryancampbell** [comment] 2017-01-24 02:12
@a-murphy thank you, I'll watch for updates.

**Comment by a-murphy** [comment] 2017-01-24 02:33
It looks like a new version of `setuptools` was released and the dependencies of that dependency (`packaging` and `appdirs`) are causing the problem.  Installing the latest version of `setuptools` or its dependencies before `awsebcli` appears to help.  So, adding either `pip install packaging=16.8 appdirs=1.4.0` or `pip install setuptools==34.0.1` to the end of your `ci` section (after `botocore`) should allow `awsebcli` to be installed.

**Comment by jwg4** [comment] 2017-01-24 10:54
Does this means that it is expected behavior that `pip install -U setuptools` should fail, when a version before 34 is currently installed? This seems surprising! Should this be reported as a bug to pip?

**Comment by auzias** [comment] 2017-01-24 12:05
I got the same error by installing an unrelated project but using `setuptools` with `pip3`. I'ld cast my vote to report this to `pip`.
See: rflamary/POT/issues/4

**Comment by avinci** [comment] 2017-01-24 15:34
closing this from our side as its not a Shippable issue.

**Closed by avinci** 2017-01-24 15:34 UTC
Labels: question, resolved

**Comment by ryancampbell** [comment] 2017-01-24 18:12
@avinci I agree, not directly a shippable problem

If anyone happens to solve this before I do please share the fix. I'll do the same

**Comment by vshih** [comment] 2017-03-11 07:21
@a-murphy,

> pip install packaging=16.8 appdirs=1.4.0

should be

> pip install packaging==16.8 appdirs==1.4.0

which worked for me.  `pip install setuptools==34.0.1` did not work for me, it failed with the same ImportError as the original issue.
