### ISSUE TITLE
Blank Shippable

### ISSUE THREAD

**Issue by WLimpens** [Shippable/support#4618] opened 2018-10-22 14:54 UTC
Hi,

I had 2 projects setup including subscription integrations. However, they are gone. I had problems with login using Firefox (logged in on GitHub, Shippable still wanted me to log in on GitHub). Registering issues also failed cause I always got logged out from GitHub. So I switched to Chrome which at least let me log in on GitHub and Shippable. But the projects are gone.

What happened and how to get the projects and integrations back?

**Comment by deepikasl** [comment] 2018-10-22 15:12
Hi @WLimpens,
GitHub has been reporting errors from around 15 hours ago: https://status.github.com/messages. I believe this is the root cause of the problem.

**Comment by trriplejay** [comment] 2018-10-23 16:24
closing as the github issues are resolved. please let us know if you're still having problems.

**Closed as completed by trriplejay** 2018-10-23 16:24 UTC

**Comment by WLimpens** [comment] 2018-10-23 18:06
I can confirm it is resolved. Even when GitHub reported webhooks where back active, it still took a while before my dashboard was back. Thx.
