### ISSUE TITLE
Cannot login to Shippable with Bit-Bucket credentials

### ISSUE THREAD

**Issue by ramstm** [Shippable/support#4562] opened 2018-09-20 07:06 UTC
Hi Team,

We are seeing the following error when trying to login Shippable with Bit-bucket credentials.

Can you please look in to the issue.

InternalOAuthError: Failed to obtain request token
    at Strategy.OAuthStrategy._createOAuthError (/home/shippable/www/node_modules/passport-oauth1/lib/strategy.js:396:17)
    at /home/shippable/www/node_modules/passport-oauth1/lib/strategy.js:244:41
    at /home/shippable/www/node_modules/oauth/lib/oauth.js:543:17
    at passBackControl (/home/shippable/www/node_modules/oauth/lib/oauth.js:397:13)
    at IncomingMessage.<anonymous> (/home/shippable/www/node_modules/oauth/lib/oauth.js:409:9)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

Thanks,
Ram

**Comment by rageshkrishna** [comment] 2018-09-20 07:21
Closing as a duplicate of https://github.com/Shippable/support/issues/4561. Please follow that issue for updates. Thanks.

**Closed as completed by rageshkrishna** 2018-09-20 07:21 UTC
