### ISSUE TITLE
Shippable builds incredibly slow

### ISSUE THREAD

**Issue by nathanpeck** [Shippable/support#1352] opened 2015-04-23 21:01 UTC
I'm having issues where builds take 15 or more minutes at the `test_ve` stage. Here is my `shippable.yml` file:

```yaml
# Language setting
language: node_js

# Version number
node_js:
  - 0.12.2

services:
  - redis

env:
  - REDIS_HOST=localhost REDIS_PORT=6379

cache: true

# scripts
script:
  # Install dependencies
  - npm install

  # Start server
  - node cluster.js &
  - NODE_PID=$!

  # Run tests
  - npm test

  # Cleanup
  - kill $NODE_PID
```

It appears that Shippable is compiling Node.js from source, as I see thousands of lines of build output like this:

```
ln -f "/home/shippable/.nvm/src/node-v0.12.2/out/Release/obj.target/deps/uv/libuv.a" "/home/shippable/.nvm/src/node-v0.12.2/out/Release/libuv.a" 2>/dev/null || (rm -rf "/home/shippable/.nvm/src/node-v0.12.2/out/Release/libuv.a" && cp -af "/home/shippable/.nvm/src/node-v0.12.2/out/Release/obj.target/deps/uv/libuv.a" "/home/shippable/.nvm/src/node-v0.12.2/out/Release/libuv.a")
```

Expected behavior would be that Shippable uses something like a prebuilt binary at https://nodejs.org/dist/ which should be able to be installed in seconds.

**Comment by manishas** [comment] 2015-04-24 00:41
@nathanpeck the easiest way to get around this is to user the custom build image shippableImages/ubuntu1204_nodejs or shippableImages/ubuntu1404_nodejs.

These have node 0.12 preinstalled. However, you will need to install any services you need, and you can then use cache: true in your yml to cache the image.

http://docs.shippable.com/en/latest/custom_images.html#language-specific-images

**Comment by jeffkole** [comment] 2015-04-30 20:38
I've spent several hours today trying to properly install postgres and redis on top of `shippableImages/ubuntu1404_nodejs` so that I can try to diagnose a broken build.  The installation steps work just fine when I run them in the docker container manually, but they break when run through Shippable's build process.

Do you have full examples of how to do this kind of service installation that you can point us to?

**Comment by manishas** [comment] 2015-05-01 13:11
@jeffkole does the solution in https://github.com/Shippable/support/issues/746 help with Postgres installation?

I'm sorry for the delay in responding. We were battling some service issues yesterday but it is mostly under control now.

**Comment by jeffkole** [comment] 2015-05-01 14:17
I reverted back to non-dedicated hosts after using the shipimg/minv2 on the
dedicated host failed with more than one parallel build (the postgres
service was being shut down by the first build before the second build was
finished, even though they are run in containers).  If I get back to using
dedicated hosts, I will give this a shot.

Is Shippable back to a performant state now?  Tests that take fractions of
a second on my laptop were taking 30-60 seconds on my Shippable builds
yesterday.

**Comment by davidgovea** [comment] 2015-05-12 22:46
I was also noticing that node 0.12.2 was being built from source.

In **test_ve**, I'd see an error like  
```
mv: cannot move `/home/shippable/.nvm/bin/node-v0.12.2-linux-x64' to `/home/shippable/.nvm/versions/v0.12.2': No such file or directory

Binary download failed, trying source.
```
The problem is: `~/.nvm/versions` does not exist on the default shippable image.

I've solved it by removing the `node_js:` version key from my `shippable.yml` (so that we can install node 0.12.2 manually in `before_install`)

*shippable.yml*
```
language: node_js

# no node version specifier

before_install:
  - mkdir -p ~/.nvm/versions
  - source ~/.nvm/nvm.sh && nvm install 0.12.2
```

**Comment by manishas** [comment] 2015-07-02 22:39
Closing this issue, please re-open or comment if you need more help with your scenario.

**Closed by manishas** 2015-07-02 22:39 UTC
Labels: question, resolved
