### ISSUE TITLE
Ruby build fails on image versions greater than 6.1.4

### ISSUE THREAD

**Issue by oriolbcn** [Shippable/support#4593] opened 2018-10-04 09:44 UTC
### Description of your issue:

I have this build which runs correctly on version 6.1.4 of the image: https://app.shippable.com/github/localistico/l-photo-booth/runs/24/summary/console

When changing the image to 6.2.4 or greater, the build fails without any apparent error, as all the tests pass as all the steps are reported with a green tick.

The only error reported in the logs is the following during the Cleanup step:

```
Booting up CEXEC
WARNING:execute - execute:Using new build runner
Running CEXEC script
ERROR:script_runner2 - script_runner2:Command failed : ssh-agent bash -c ' cd /root && /root/1ad13228-8ea6-44c6-ae31-08636bf8a76a.sh'
Exception Invalid or no script tags received
ERROR:script_runner2 - script_runner2:Command failed : ssh-agent bash -c ' cd /root && /root/1ad13228-8ea6-44c6-ae31-08636bf8a76a.sh'
Exception Invalid or no script tags received
sudo docker rm -fv $CONTAINER_NAME c.exec.l-photo-booth.18.1
```

Example of failed build (using v 6.9.4): https://app.shippable.com/github/localistico/l-photo-booth/runs/25/summary/console

The only related issue I have found to this is: https://github.com/Shippable/support/issues/4297 but according to that it should be fixed in the latest version, however it is failing in 6.9.4 so I am not sure if it is that issue or another.

This issue is currently blocking us from deploying this application, as I can't use 6.1.4 because the chromedriver version is too old.

Thanks!

### shippable.yml

```
language: ruby
rvm:
  - 2.5.1
services:
  - postgres
env:
  global:
    - IMAGE_NAME_STAGING=l-photo-booth-staging
    - IMAGE_NAME_PRODUCTION=l-photo-booth-production
    - GCR_REPO=xxx
runtime:
  nodePool: new_node_pool
build:
  ci:
    - sudo apt-get -y update
    - sudo apt-get -y install libpq-dev libqtwebkit-dev xvfb imagemagick
    - mkdir -p shippable/testresults
    - mkdir -p shippable/codecoverage
    - cp config/database.shippable.yml config/database.yml
    - cp config/secrets.yml.sample config/secrets.yml
    - rvm use $SHIPPABLE_RUBY
    - bin/bundle install
    - bin/rails db:setup RAILS_ENV=test
    - LOCALISTICO_API_URL=http://example.com rspec spec/models/import_spec.rb -f RspecJunitFormatter -o shippable/testresults/results.xml
    - mv coverage shippable/codecoverage
    - rubocop
  post_ci:
    - >
      if [ $BRANCH = "master" ] && [ $IS_PULL_REQUEST == "false" ]; then
        ENV=staging;
        IMAGE_NAME=$IMAGE_NAME_STAGING;
      fi;
      if [ $BRANCH = "production" ] && [ $IS_PULL_REQUEST == "false" ]; then
        ENV=staging;
        IMAGE_NAME=$IMAGE_NAME_PRODUCTION;
      fi;
      if [ $ENV ]; then
        docker build -t $GCR_REPO/$IMAGE_NAME:$BUILD_NUMBER .;
        docker push $GCR_REPO/$IMAGE_NAME:$BUILD_NUMBER;
      fi;
integrations:
  hub:
    - integrationName: gcp_localistico
      type: gcloudkey
```

**Comment by rageshkrishna** [comment] 2018-10-04 11:05
@oriolbcn This certainly looks like the same issue with `rvm` wiping out our bash traps.

@ric03uec Can you take a look at this? I know we've tried to workaround this rvm bug at our end but it looks like we may have missed something.

**Comment by ric03uec** [comment] 2018-10-09 21:33
@oriolbcn we're investigating this. as @rageshkrishna mentioned, this seems like the same bug that we've fixed earlier. We've been able to repro this with the help of yml you provided but haven't figured out the root cause yet. we'll keep you posted on the progress. thanks for your patience.

**Comment by oriolbcn** [comment] 2018-10-10 07:17
Great thanks for the update! Glad that you were able to reproduce it, hope you can fix it.

**Comment by ric03uec** [comment] 2018-10-10 19:19
@oriolbcn we've fixed the issue and this will be available in the next few days in `v6.10.1` release

**Comment by oriolbcn** [comment] 2018-10-10 21:32
@ric03uec great news 😄  Please update the issue once the new version is released and I will try it. Thanks!

**Comment by ric03uec** [comment] 2018-10-12 19:11
@oriolbcn this is now deployed. You should be able to upgrade to the new runtime version.

**Comment by oriolbcn** [comment] 2018-10-15 06:00
@ric03uec I am not able to see the new runtime version. I also tried logging out and in again without luck.

This is what I see:

![image](https://user-images.githubusercontent.com/3403704/46932487-4b0e7580-d050-11e8-8a63-c8f37246b1d1.png)

**Comment by rageshkrishna** [comment] 2018-10-15 06:12
@oriolbcn Sorry about the confusion. There is no new runtime version for the v6.10.1 release. You should be able to pick v6.9.4 like you tried before and get it to work now. Can you give it a shot and let us know how it goes?

**Comment by oriolbcn** [comment] 2018-10-15 06:46
YAY! I confirm it works 🎉 Thank you very much!

**Comment by ric03uec** [comment] 2018-10-15 13:07
nothing to be done here, closing

**Closed as completed by ric03uec** 2018-10-15 13:07 UTC
