### ISSUE TITLE
Builds timing out and OAuth failing

### ISSUE THREAD

**Issue by rarkins** [Shippable/support#3090] opened 2016-10-30 02:55 UTC
I am getting build timeout errors, and when I try to view the Dashboard I get an OAuth error from GitHub:

![image](https://cloud.githubusercontent.com/assets/6311784/19834167/bc54173e-9e54-11e6-928b-111298a0f800.png)

**Comment by manishas** [comment] 2016-10-30 03:00
We just finished our scheduled maintenance window and your build timeouts are probably caused by that. We're looking into the GitHub reauth issue.

**Comment by rarkins** [comment] 2016-10-30 03:04
Maybe you broke something during that window?

![image](https://cloud.githubusercontent.com/assets/6311784/19834196/f9905616-9e55-11e6-9a39-2ec9282d6706.png)

**Comment by rarkins** [comment] 2016-10-30 03:06
i.e. even after you click "Authorize Application", it cycles through the OAuth dance a number of times before silently failing and returning to the same prompt again.

**Comment by rarkins** [comment] 2016-10-30 03:09
While checking if it works in Chrome Incognito (it doesn't) I also notice it asking for increased privileges:

![image](https://cloud.githubusercontent.com/assets/6311784/19834214/aa0ee6d8-9e56-11e6-91ec-eb9125670c2f.png)

**Comment by naveensky** [comment] 2016-10-30 03:19
Why do we need increased permissions ? Can I read through any release notes to understand ?

![image](https://cloud.githubusercontent.com/assets/806681/19834254/c0a3f1fa-9e7d-11e6-8ab2-8213e27b037d.png)

**Comment by manishas** [comment] 2016-10-30 03:25
We are looking into this. We're not really asking for increased permissions since these should already be authorized when you enable private repos. 

More info coming up as we look deeper into what's causing this.

**Comment by magicalbanana** [comment] 2016-10-30 03:31
I hope it gets fixed soon.

**Comment by rarkins** [comment] 2016-10-30 03:32
I care less about the permissions and more that now I can't log in at all

**Comment by manishas** [comment] 2016-10-30 05:40
@rarkins is this still happening? can you log in now?

**Comment by rarkins** [comment] 2016-10-30 06:44
@manishas yes, I can now access the Dashboard. However it seems to be running slow to me and I had to refresh a few times due to errors. Console log below:
![image](https://cloud.githubusercontent.com/assets/6311784/19834914/b1a8b20c-9e74-11e6-96d5-8d831d81898a.png)

**Comment by magicalbanana** [comment] 2016-10-30 16:20
Yeah, I can confirm the actual shippable.com site is also slow.

**Comment by manishas** [comment] 2016-10-30 16:39
We're working on this today. We've identified a couple of fixes so will update this thread soon

**Comment by manishas** [comment] 2016-10-31 08:59
We are still seeing intermittent issues with signing into the Shippable UI. We are looking into this.

Builds are running as expected.

**Comment by kqdtran** [comment] 2016-11-01 17:35
No builds are starting for our project -- they are queued but nothing seems to happen. The builds were working fine till last Friday and we haven't made any change to shippable.yml in a while.

**Comment by manishas** [comment] 2016-11-14 19:48
This should no longer be happening. Closing this issue.

**Closed by manishas** 2016-11-14 19:48 UTC
Labels: bug-CQD, in progress
