### ISSUE TITLE
Billing *2

### ISSUE THREAD

**Issue by sebcreme** [Shippable/support#4448] opened 2018-07-09 14:39 UTC
### Description of your issue:
Hello, we have changed sku today to have ubuntu 16, but when saving we had an error.

And now when we check our billing we can see 2 bills for the same monthe of 25 and 24,19 euros ?
Can you, please, correct the error.

Thanks

**Comment by trriplejay** [comment] 2018-07-09 19:35
Hi @sebcreme, we're looking into this.

**Comment by rageshkrishna** [comment] 2018-07-10 07:27
Hi @sebcreme. It looks like what happened here is that an upgrade was first processed to include both u14 and u16 nodes (hence the prorated $24.19 charge), and it was immediately brought back down to just u16 nodes. This seems to have happened in error.

I have confirmed with the payment provider that the additional payment of $24.19 was reversed immediately and your subscription currently has a $24.19 credit, which will automatically be adjusted against your next invoice.

I hope this clarifies things. Please reach out to me at ragesh@shippable.com if you have any more specific queries about this.

**Comment by manishas** [comment] 2018-07-13 00:04
Closing this since it's been answered.

**Closed as completed by manishas** 2018-07-13 00:04 UTC
