### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by GiffinR** [Shippable/support#2975] opened 2016-09-19 19:30 UTC
We're seeing a build failure:

https://app.shippable.com/runs/57e036214d8c410f0091d8e4/1/console

 bundle install --gemfile=$SHIPPABLE_GEMFILE $SHIPPABLE_BUNDLER_ARGS 0s  
/root/2bb61d6f-74a0-45bb-88da-83069aa822f0.sh: line 58: bundle: command not found

**Comment by manishas** [comment] 2016-09-19 20:36
I don't see anything wrong and I tried running the same command with another repo and it seemed to work. Can you share your shippable.yml?

**Comment by GiffinR** [comment] 2016-09-19 20:41
Sure – I’m just getting started:

language: ruby
rvm:
  - 2.0.0
script:
  - rspec


Rob Giffin____
Avalution Consulting
216-832-0515
www.linkedin.com/in/robgiffin
Check out my calendar to set up a meeting – 30 Minute Meeting Link<https://calendly.com/rob-giffin/30min> & 1 Hour Meeting Link<https://calendly.com/rob-giffin/60min>.

**Comment by manishas** [comment] 2016-09-19 20:46
I am not sure if you're looking at the right set of docs. Here are some helpful links:

http://docs.shippable.com/ci/shippableyml/
http://docs.shippable.com/ci/languages/ruby/

Can you try the following yml:

```
language: ruby
rvm:
  - 2.0.0
build:
  ci:
    - rspec
```

**Comment by GiffinR** [comment] 2016-09-19 21:16
Ok – new shippable file:

language: ruby
rvm:
  - 2.2.0
  - 2.0.0
build:
  ci:
    - bundle install
    - rake db:setup
    - bundle exec rake test

Both version fail at bundle install:
bundle install0s
/root/43f6aeae-cf3b-4026-a38e-57bb05c24c8e.sh: line 58: bundle: command not found

https://app.shippable.com/runs/57e053d2f423810f0025b3cb/2/console


Rob Giffin____
Avalution Consulting
216-832-0515
www.linkedin.com/in/robgiffin
Check out my calendar to set up a meeting – 30 Minute Meeting Link<https://calendly.com/rob-giffin/30min> & 1 Hour Meeting Link<https://calendly.com/rob-giffin/60min>.

**Comment by manishas** [comment] 2016-09-19 23:35
This is pretty strange. I'll ask someone to take a deeper look into this...

**Comment by stephanielingwood** [comment] 2016-09-20 21:33
Hi, @GiffinR. We just spent a while trying to reproduce this error, with no luck. Here's what we know so far: 

- In your build, bundler is installed and working correctly in the `setup_ruby` section; you can see the output of the `bundle --version` command. 
- The only other commands executed between that `bundle --version` and the failing `bundle install` are those in the `git_sync` step: some git commands (clone, reset, config), a `cd` and a few `mkdirs`.
- We suspect there may be something in your repo that is causing this. Do you have anything in your repo that may somehow be overriding the `bundle` command, and/or that would change your PATH? 

Also, would you mind sharing your Gemfile with us? While it's probably not the culprit, we'd like to rule it out.

Thanks in advance.

**Comment by stephanielingwood** [comment] 2016-09-20 23:44
Okay, scratch that. Looks like the gemset specified by your `.ruby-gemset` (or `.rvmrc`) doesn't have bundler installed. Here's what we're seeing:

- When we init rvm in the `setup_ruby` step, rvm is using this: `/usr/local/rvm/gems/ruby-2.0.0-p643`
- Then, the repo is cloned, and the gemset is switched because of the `.ruby-gemset` (or `.rvmrc`).
- Now the build is using a gemset where bundler doesn't exist, giving that `bundle: command not found` error.

You have a couple of options to get around this:
- In your `ci` step, add `rvm use $SHIPPABLE_RUBY` before your bundle install. This will override the gemset specified in your `.ruby-gemset` with the gemset containing bundler.
- Install bundler in your `ci` step (this will let you use your existing gemset).

Hope this helps. Let us know if you have any other questions.

**Comment by GiffinR** [comment] 2016-09-20 23:54
Awesome – thanks!


Rob Giffin____
Avalution Consulting
216-832-0515
www.linkedin.com/in/robgiffin
Check out my calendar to set up a meeting – 30 Minute Meeting Link<https://calendly.com/rob-giffin/30min> & 1 Hour Meeting Link<https://calendly.com/rob-giffin/60min>.

**Comment by manishas** [comment] 2016-09-21 00:06
closing this issue. @GiffinR let us know if it doesn't work for you and we will reopen the issue.

**Closed by manishas** 2016-09-21 00:06 UTC
Labels: in progress, question
