### ISSUE TITLE
error 90704 when trying to enable repository

### ISSUE THREAD

**Issue by provthomas** [Shippable/support#4676] opened 2018-12-11 01:19 UTC
I get this error when I try to enable a repo at `https://app.shippable.com/subs/github/providenceinnovation/enable`:

```
deleteResourceById failed for id: 90704 returned error deleteVersionByResourceId for resourceId:90704 returned error: versions.destroy failed for resourceId: 90704 returned error: update or delete on table "versions" violates foreign key constraint "jobs_versionId_fkey" on table "jobs"
```

The repo's URL on github is: https://github.com/providenceinnovation/insurance-card-capture-web-ui

**Comment by a-murphy** [comment] 2018-12-11 01:51
Another repository with the same name had already been enabled and was causing a conflict.  Since it appears that the previous repository has most likely been deleted on the source provider (in which case no one will be able to access the older project on Shippable), I've removed the resources causing the conflict.  You should be able to enable the new project now.  Let us know if you run in to any more problems.

**Comment by rageshkrishna** [comment] 2019-01-25 05:33
The root cause is going to be fixed in https://github.com/Shippable/support/issues/4697. Please follow that issue for updates. I'm going to close this now.

**Closed as completed by rageshkrishna** 2019-01-25 05:33 UTC
