### ISSUE TITLE
Again projects missing

### ISSUE THREAD

**Issue by bbrala** [Shippable/support#3812] opened 2017-09-05 14:29 UTC
Last friday a colleage had loads of missing projects. And right not a colleage had missing projects.

His bitbucket name welfring, missing project: https://app.shippable.com/bitbucket/swisnl/nkl/runs/730/1/console

See 
https://github.com/Shippable/support/issues/3760
https://github.com/Shippable/support/issues/3711
https://github.com/Shippable/support/issues/3361

**Comment by a-murphy** [comment] 2017-09-05 17:19
Our logs show that welfring was rate limited by Bitbucket.  It's possible that this was caused by clicking sync many more times than typical within an hour or by other calls to Bitbucket's API made by that account.  I would suggest clicking sync once more now that it has been over an hour.

**Comment by bbrala** [comment] 2017-09-05 18:30
Hmm, could it be because a large amount of projects are run through his
name or something? He might be refreshing a good lot because he is on the
appliction a lot, but perhaps it is something about projects running
through his account? I know you can assign a user in project settings.

Perhaps I should change that setting to a dedicated shopper user on our
account? I do know we have one.

Op 5 sep. 2017 19:19 schreef "a-murphy" <notifications@github.com>:

**Comment by a-murphy** [comment] 2017-09-05 20:05
If his account was selected to run a lot of webhook builds in an a hour, it would contribute to a rate limit.  However, each build only makes a few calls so it is unlikely to be the only cause.  And refreshing Shippable does not make any calls to Bitbucket unless the account was due to be synchronized.  Previous rate limit causes (for other subscriptions) have been identified as accounts with many projects (well over 100, and we also make fewer calls per project now), clicking "sync" repeatedly in a short span of time, and accounts that were interacting directly with the source provider's API as part of a script the user was running frequently.

Setting a specific user on the project settings pages is an option.  If that user is rate limited, the selected account will automatically change to another user with access.  Setting an account to use may help find the cause if this is a frequent problem.  (If a user is still rate limited and the selected users for the projects haven't changed, then it's probably not related to running webhook builds.  And if the selected accounts keep changing, then it's more likely related.)

**Comment by manishas** [comment] 2017-10-13 18:59
This should be fixed now... let us know if you continue to run into problems.

**Closed by manishas** 2017-10-13 18:59 UTC
Labels: question
