### ISSUE TITLE
CI project gone, cannot enable again

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#4665] opened 2018-11-29 13:05 UTC
One of our CI projects is suddenly gone and we are unable to enable it again:

```
deleteResourceById failed for id: 82869 returned error deleteVersionByResourceId for resourceId:82869 returned error: versions.destroy failed for resourceId: 82869 returned error: update or delete on table "versions" violates foreign key constraint "jobs_versionId_fkey" on table "jobs"
```

Before it was deactivated the CI project had the ID `5af2d405d4612c0600baa5a4`.

Can you have a look at this?

**Comment by trriplejay** [comment] 2018-11-29 16:17
we're investigating

**Comment by trriplejay** [comment] 2018-11-29 17:17
@mbrodala your project should be visible again. You may need to reset the project keys from the settings page for webhooks to be available again. There was an issue where a duplicate of the project was synced, but the duplicate has now been removed. We're investigating what might have caused this.

**Comment by mbrodala** [comment] 2018-11-30 08:29
Thanks, after resetting the keys in the Shippable CI project builds are now working again. Please let me know once you find the cause of this issue.

**Comment by manishas** [comment] 2019-03-06 21:33
Closing since this is not being worked on actively. The root cause wasn't traceable and it doesn't seem to have happened again

**Closed as completed by manishas** 2019-03-06 21:33 UTC
