### ISSUE TITLE
Support to mark build as "UNSTABLE" in low coverage

### ISSUE THREAD

**Issue by tomiito** [Shippable/support#198] opened 2014-06-09 03:14 UTC
We should be able to put some marks, for classes, methods, lines and branches for coverage in the yml to be able to mark the build as unstable like the jenkins cobertura plugin does

**Comment by manishas** [comment] 2015-01-06 19:06
Closing as duplicate of #174

All requests related to code coverage will be tracked there.

**Closed by manishas** 2015-01-06 19:06 UTC
Labels: duplicate, feature request, triaged
