### ISSUE TITLE
No email notification received for --last_committer

### ISSUE THREAD

**Issue by mattclay** [Shippable/support#2743] opened 2016-06-24 06:29 UTC
Build https://app.shippable.com/runs/576ccd5345eaa40e001ef9a0 failed and I expected to receive an email regarding the failure, but did not. I did, however, receive the Slack and IRC notifications.

The commit was merged from a PR using GitHub's squash and merge feature and it shows in the build as "Builder: GitHub Web Flow". Would this have any effect on the --last_committer email notification setting?

**Comment by spsiddarthan** [comment] 2016-06-24 08:05
@mattclay, Whenever you commit on GitHub using the web UI, this is the committer information we are getting of late from github. 

```
 {
		"login" : "web-flow",
		"displayName" : "GitHub Web Flow",
		"email" : "noreply@github.com",
		"avatarUrl" : "https://avatars.githubusercontent.com/u/19864447?v=3"
}
```

We are waiting for feedback from Github on to see if this a bug from their side.

**Comment by spsiddarthan** [comment] 2016-06-28 05:53
@mattclay, GitHub has confirmed that they recently started setting the committer for web-based Git operations as GitHub <noreply@github.com> and this is the intended behavior from their side. 

You will still be able to get the notifications for non-web based commits. We are figuring out the options for the web based github commits and will keep you posted as we make progress on this.

**Comment by mattclay** [comment] 2016-06-28 20:46
There's no rush on fixing this. We've decided to stick to IRC and Slack notifications instead of email.

**Comment by avinci** [comment] 2017-02-28 11:02
i think this is fixed on our side. Please let us know if otherwise.

**Closed by avinci** 2017-02-28 11:02 UTC
Labels: investigate
