### ISSUE TITLE
Problem picking up encrypted env vars in pull request

### ISSUE THREAD

**Issue by swhite-finovertech** [Shippable/support#3220] opened 2016-12-08 15:17 UTC
Pull request builds off a particular git master branch are not picking up env vars set as a global secure, and hence failing.

The failed build off PR branch:

https://app.shippable.com/runs/5848c53b4d42fa0f00b56102/1/console

The passing build off the master branch:

https://app.shippable.com/runs/5849750fc42d210f009d7f1c/1/console

The shippable.yml was identical between the two builds, with env section:

```env:
    global:
        # AWS CLI CONFIG
        - secure: **********************************************************
        - AWS_DEFAULT_REGION=us-east-1
        - aws_access_key_id=************************
```

(I star'ed out the aws_access_key_id and secure for this issue report)

The secure encodes the `aws_secret_access_key`, needed during the gradle build. I verified that the successful build has a correct value for the `aws_secret_access_key`, but the failing build has no value for `aws_secret_access_key`.

I suspect the problem is that the PR builds off https://app.shippable.com/projects/58221145c47dbb0f00f85545/status/ are not picking up the secure settings set for the project. I am having no issue with PR builds off other projects.

Any ideas? I got around the problem by just merging the pull request branch into the master branch, and that built successfully, but going forward, that's a poor solution.

**Comment by rageshkrishna** [comment] 2016-12-08 16:20
We don't decrypt secure envs for PR builds on public repositories for security reasons. This is because PRs can be opened on public repos by _anyone_ and they can potentially do anything they please with your secure variables.

You will not see this happen on private repos because we assume that collaborators are trusted.

**Comment by manishas** [comment] 2016-12-15 20:26
Closing this since it is by design.

**Closed by manishas** 2016-12-15 20:26 UTC
