### ISSUE TITLE
Very slow job node provisioning

### ISSUE THREAD

**Issue by rarkins** [Shippable/support#3028] opened 2016-10-07 17:49 UTC
### Description of your issue:

Example: all three of these in screenshot below were still on "Provisioning job node". It took a minimum 5 minutes for any builds to get a job node right now.

![image](https://cloud.githubusercontent.com/assets/6311784/19200018/1b7aca4a-8cc7-11e6-861d-72d34c52556c.png)

**Comment by rarkins** [comment] 2016-10-07 17:50
Example slow build: https://app.shippable.com/runs/57f7ddaa865a090e00b729a1/1/console

![image](https://cloud.githubusercontent.com/assets/6311784/19200065/4e28bb0a-8cc7-11e6-8741-170cd354f0df.png)

**Comment by rarkins** [comment] 2016-10-07 17:53
The first two proceeded but this third one seems stuck:
![image](https://cloud.githubusercontent.com/assets/6311784/19200145/c4c23cf0-8cc7-11e6-81ce-34e37cedb208.png)

**Comment by rarkins** [comment] 2016-10-07 18:06
This last one (3702) came up. It took 15+ minutes:
![image](https://cloud.githubusercontent.com/assets/6311784/19200478/82c38c6c-8cc9-11e6-903d-c555a7512523.png)

**Comment by santtu** [comment] 2016-10-10 13:29
We just got jobs that seem to be not getting build node at all. This one has been stuck in provisioning for 30 minutes.

![image](https://cloud.githubusercontent.com/assets/650612/19237626/968165fa-8f06-11e6-89ad-45bb7279251b.png)

**Comment by santtu** [comment] 2016-10-10 17:34
That eventually got a node, but it took so long (over an hour) that the build eventually timed out at 2 hours.

**Comment by rarkins** [comment] 2016-10-10 19:27
I'm also having job nodes simply time out during provisioning again

**Comment by trriplejay** [comment] 2016-10-10 20:18
This morning around 6am we had an issue with our provisioning service that may have caused some nodes to experience a large delay in being provisioned. That issue should be resolved now.

As far as generally slow provisioning, we're always looking for ways to improve that time, but for the most part we are at the mercy of ec2.  Most provisioning seems to happen within a 3-5 minute range, but occasionally users have experienced longer times than this. One option, if you consider these delays to be unacceptable, is to [attach your own build nodes](http://docs.shippable.com/ci/advancedOptions/byon/).

**Comment by manishas** [comment] 2016-10-19 18:35
is this still a problem?

**Comment by herriojr** [comment] 2016-11-08 23:31
Yes. I get this regularly similar to santtu. It took over an hour for one run the other day. Today in in the middle of a similar case. I just cancelled it and started it back up and has already been 7 minutes.

**Comment by Tapppi** [comment] 2016-11-17 10:04
@manishas Similar problems right now. Night time builds get a node immediately and complete fast, daytime we can't practically even build anything as nodes take >20min to provision. This is pretty much a blocker, as >50% of CI time is spent on provisioning nodes.. Seems pretty unacceptable for a service we pay for. Didn't get a node in 22 mins and after cancel/rebuild it has been stuck 16 mins again.

**Comment by kanthchandra** [comment] 2016-11-17 10:10
@Tapppi Can you please provide me your subscriptionId for which the node is not provisioned?

**Comment by Tapppi** [comment] 2016-11-17 12:50
@kanthchandra It eventually got a node after ~30 minutes. subId 5808c5f2a708080e00ad7d86. Will probably see another delay right now, as another dev pushed a commit that should start a CI run.

**Comment by Tapppi** [comment] 2016-11-23 09:20
@kanthchandra @manishas Now we are getting timeouts too... So 2 hours and no node provisioned. https://app.shippable.com/runs/583532887ae6830f00c4267d/1/console

**Comment by Tapppi** [comment] 2016-12-01 15:54
Can someone update this issue, we have another 27 minute node provision going on at the moment.. https://app.shippable.com/runs/58404167e2ab4d0f0058ac55/1/console

**Comment by roni-frantchi** [comment] 2016-12-03 15:56
We're looking to sign up to shippable, just got the same issue on trial...
Been stuck on `Provisioning a node for subscriptionId` forever.

**Comment by Tapppi** [comment] 2016-12-22 17:36
@manishas @kanthchandra We are frequently getting build timeouts and very slow node provisioning, right now we have been waiting >3 hours for one build to get a node, including a restart after a timeout! I have provided you with all the information you asked. Please update the status of this issue, this has come up in team meetings as a reason to move to another CI provider multiple times now..

**Comment by rageshkrishna** [comment] 2016-12-23 03:41
@Tapppi Apologies for the silence on this issue. This problem was particularly difficult to track down, primarily because it was not reproducible in a deterministic way.

The good news is that we do have a couple of solid leads now on why this might be happening and we're working on fixing these problems. You should start noticing some improvements to this in the next couple of weeks.

**Comment by kanthchandra** [comment] 2017-01-21 14:37
@manishas This has also been fixed in the latest release. If for some reason the job gets stuck without a node being provisioned, we reprovision the nodes. Ideally a node should come up in 3 minutes and should start processing your jobs. In case the node doesn't come up even after 10 minutes, we delete that node and reprovision another one.

 @rarkins Please let us know if you run into this in future.

**Closed by kanthchandra** 2017-01-21 14:37 UTC
Labels: in progress
