### ISSUE TITLE
xvfb-run: error: Xvfb failed to start

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#2848] opened 2016-08-02 15:29 UTC
I am seeing the following error in [my build](https://app.shippable.com/runs/57a0baa95685720c00669b3c/1/console):

```
export DISPLAY=:99.0
xvfb-run --server-args="-ac" bin/codecept run acceptance
xvfb-run: error: Xvfb failed to start
```

What am I missing here?

**Comment by manishas** [comment] 2016-08-03 23:59
@a-murphy can you look into this?

**Comment by a-murphy** [comment] 2016-08-04 02:17
I couldn't find any clues in the build logs, or reproduce any similar errors.  The `export DISPLAY=:99.0` line doesn't appear anywhere in the build logs, but removing it from the sample Selenium project didn't lead to any errors.  Neither did moving the `xvfb-run` command into a script.

Adding `-e /dev/stdout` to the `xvfb-run` command will log more, which would hopefully include the reason it failed.  (For example, `xvfb-run -e /dev/stdout --server-args="-ac" bin/codecept run acceptance`.)

**Comment by mbrodala** [comment] 2016-08-04 07:24
@a-murphy Yes, our CI commands are pulled at build time but you can see them in the build log (dark grey are executed commands.) The export line was there but I didn't log it.

I'll try your suggestion ASAP.

**Comment by manishas** [comment] 2016-08-30 19:13
@mbrodala I am closing this issue assuming that it is now working as expected. Let us know if you're still having issues and we'll reopen. Thanks!

**Closed by manishas** 2016-08-30 19:13 UTC
Labels: investigate, question

**Comment by mbrodala** [comment] 2016-08-31 07:06
I haven't tried again yet since I prefer PhantomJS currently. I'll get back to you if I hit its limitations. ;-)
