### ISSUE TITLE
Not recognized new organization for GitHub account

### ISSUE THREAD

**Issue by stekycz** [Shippable/support#1609] opened 2015-06-26 14:55 UTC
Hi,

I have been added to new GitHub organization and I would like to run test using Shippable. However I did not found new organization in CI list.

Well, ok, It maybe needs force syncing in settings. However it did not help.

Then I have had to revoke all access token for Shippable on GitHub and authorize myself again. There was the organization a have new in my profile however I still do not see it in my CI list.

Did I do something wrong?

Thanks!

**Comment by manishas** [comment] 2015-06-26 17:17
@stekycz what organization were you added to?

Do you see builds from repos in that org in your recent builds list on the dashboard?

**Comment by stekycz** [comment] 2015-06-28 14:14
It is already there however I did not see anything because the organization was created recently before I wanted to add repos to Shippable.

**Comment by lekhab** [comment] 2015-07-02 01:06
@stekycz: what is the name of the organization, pls? Are you still facing issues with this?

**Comment by stekycz** [comment] 2015-07-02 08:12
@lekhab Hi, it is working already, there was probably some delay for synchronization. However it would be nice that I could manually force the update of my organizations and repositories.

**Comment by lekhab** [comment] 2015-07-13 17:35
@stekycz: closing since the issue is resolved. The "Force Sync" option under Account settings does force the update of a new organization - I was able to test this works.  (http://docs.shippable.com/account_settings/#account-information).

**Closed by lekhab** 2015-07-13 17:35 UTC
Labels: question, triaged
