### ISSUE TITLE
Adding assembly line for new github repo is creating 5 deploy keys, enabling CI creates a 6th key 

### ISSUE THREAD

**Issue by prov-thinrichs** [Shippable/support#4306] opened 2018-05-01 18:03 UTC
### Description of your issue:
When we tie a github repo into shippable by adding an assembly line we get 5 deployment keys added to the github repo.

We are doing this on the Enable project page: Subscriptions / github / providenceinnovation /Enable

Here are some example key names we are seeing 
shippable-70924
shippable-70934
shippable-70935

I expect the second token is a primary key to a table.

When we then enable CI in the same UI, we then get a sixth key added to the repo:
shippable-production

You would think this 6th key would be the only one created / needed.

Please contact me directly for any shippable account level information if you need it

**Comment by prov-thinrichs** [comment] 2018-05-01 18:06
As a note, shippable seems to only be using the first key that is created.  In this example, shippable-70924

**Comment by a-murphy** [comment] 2018-05-01 18:11
Each of those keys is for a different resource; the numbers are the resource IDs if you want to identify which resource.  The first one is for the syncRepo, which will be used when the rSync job runs.  The next two are both gitRepo resources and those keys will be used to clone the repository when those gitRepo resources are inputs to a job in your Assembly Line.  And the `shippable-production` key is to clone the repository in a CI job.  Keys are created for each resource that references the repository (syncRepo, gitRepo, or ciRepo) and deleted when those resource are deleted.

**Comment by prov-thinrichs** [comment] 2018-05-01 18:15
Ah!  Thank you.  Mystery solved.  If there were named with names that signified what they are for, like shippable-syncRepo or shippable-gitRepo , etc that would be nice.

Or if you could just have one key and share it for all the use cases, that would also be nice.

**Comment by manishas** [comment] 2018-05-03 02:42
We'll definitely look into improving this in the future. Closing this issue since it's not a bug.

**Closed as completed by manishas** 2018-05-03 02:42 UTC
