### ISSUE TITLE
Marked all commits as Skiped for three month

### ISSUE THREAD

**Issue by picaro** [Shippable/support#3190] opened 2016-11-24 11:37 UTC
Hello!  I just check, that my builds were skipped from august

https://app.shippable.com/projects/5801084ba3d7a61800a84fbf/status/history

expected, that at least sometimes I will be able to use it.

**Comment by picaro** [comment] 2016-11-24 11:44
tried to delete/restore. same

**Comment by stephanielingwood** [comment] 2016-11-28 19:09
The bug fix for this will be in our next release. In the meantime, we have fixed your subscription in our database, and you should be able to run builds now. 

I'm going to close this issue, as it is a duplicate of https://github.com/Shippable/support/issues/3138. Feel free to track our progress on the issue there.

**Closed by stephanielingwood** 2016-11-28 19:09 UTC
