### ISSUE TITLE
`cache:true` seems to have no effect

### ISSUE THREAD

**Issue by jeffkole** [Shippable/support#1125] opened 2015-03-04 17:38 UTC
We have cache set to true in our shippable.yml file, but each build always starts by installing all dependencies.  Recently that step alone has started taking ~10 minutes.  That puts quite the damper on an otherwise fast process.

What do I need to change to get caching to work correctly?

**Comment by manishas** [comment] 2015-03-05 04:58
@jeffkole are you builds faster today? We've made some changes and also added capacity so you should see some improvement.

Our caching is per host, so sometimes it takes a few builds to see the benefits.

**Comment by jeffkole** [comment] 2015-03-05 16:00
We have had the cache flag set to true since we started using Shippable a few weeks ago.  The build times vary widely from 2 minutes up to the timeout at 2 hours.  If I pulled down the log of builds, I could give you some better stats on the times, but the variation is alarming, when the build is roughly the same and dominated by the `npm install` that occurs for each.

I did notice this morning this setting on the Shippable website:
![shippable___truly_fastest_ci_in_the_cloud](https://cloud.githubusercontent.com/assets/286588/6508421/874cb484-c30d-11e4-8fdd-ed7bf8ee47f8.png)
I am not pulling a custom Docker image – in fact, I am not specifying an image at all.  Is this why caching is not happening?

**Comment by manishas** [comment] 2015-03-05 22:43
Sorry that is confusing. The project settings were added for the Docker build support, so the text there is trying to differentiate between starting with a Dockerfile vs with a prebuilt image from Docker Hub. It is not relevant to your scenario... we will improve the wording and make it clear that it's for docker users.

We will take a look at why your builds times are so different. It is somewhat dependent on the load on our service, but shouldn't vary that much. We've also added some build hosts recently so I'm hoping you don't see the big variations any more.

**Comment by manishas** [comment] 2015-03-05 22:45
good news is your build seem much faster since yesterday, which is when we added the hosts :)

**Comment by jeffkole** [comment] 2015-03-05 23:36
Is it correct then that minion caching only works if I use my own Docker
image?  Will caching work if I specify an image from Shippable, like
`build_image: shippable/minv2`?

**Comment by manishas** [comment] 2015-03-06 01:28
No, minion caching works in all cases except if you're starting with a Dockerfile and using docker build with shippable.

**Comment by jeffkole** [comment] 2015-03-06 02:04
So it does appear that the container is cached, but none of the
dependencies for my project are cached so my `npm install` command
downloads all modules every time.  Is there a way I can prevent that so
that the modules that haven't changed are not downloaded again?

**Comment by manishas** [comment] 2015-03-06 02:08
I'll open up an internal issue to track this and we will take a look to figure out why the cached dependencies are not preventing re-download.

**Comment by jeffkole** [comment] 2015-03-06 15:56
Thank you.  Feel free to contact me directly (ie, not through Github
issues) for more details of my configuration or process.

**Comment by manishas** [comment] 2015-03-23 20:54
@jeffkole I tracked this down and this might be due to a limitation of our caching implementation. Let me try to explain...

We cache the container the first time a build with cache=true comes in, and all subsequent builds simply use this cache without adding stuff each time. If you make changes to your install section or add something to package.json, you will need to do a commit with [reset_minion] in your commit message in order to delete current cache and cache again so that the latest changes are picked up.

This is because we run all builds inside docker containers. When a build comes in with cache=true, docker adds a layer to the base image with the cached stuff and we commit this as <container>:latest
The next time a build runs, Docker again adds a layer to the image, however, we do not commit this back since it adds to the number of layers. Docker has a limit of 127 layers, so simply adding layers will cause builds to fail at some point.

Hope this helps... let me know if you want more clarity. You should try using the [reset_minion] in your commit message and caching will kick in again and you'll see faster build times.

**Comment by manishas** [comment] 2015-04-10 22:05
closing this issue since caching is working as designed. we will make some improvements to this in the next few weeks.

**Closed by manishas** 2015-04-10 22:05 UTC
Labels: question, resolved
