### ISSUE TITLE
Cannot kick off manual build from bitbucket

### ISSUE THREAD

**Issue by sethamclean** [Shippable/support#1971] opened 2015-10-26 14:13 UTC
Starting a manual build from bit bucket returns the following error:

```json
{"id":1004,"message":"Error normalizing sha data for project: <project sha>","methodName":"caller:547290ff1877271400f303fb|common|bitbucket|getShaData|_checkManualBranch"} 
```

**Comment by avinci** [comment] 2015-10-26 14:43
@kanthchandra @ric03uec we have started to surface all the internal build related issues, which is a good thing so folks know what is going on. 

The issue is, the message does not mean much now. I know what the issue is but the user doesn't...We need 2 things
* Help @sethamclean figure out whats actually wrong. (or it could be a bug on our side)
* Can we document all the error messages due to builds into `docs` page and explain what the possible causes and corrections the can take.

**Comment by kanthchandra** [comment] 2015-10-26 15:19
Hi @sethamclean , we are suspecting that the branch that you are trying to build is having `/` and Bitbucket is not parsing that `/` character properly and as a result when we are trying to get the sha data, we are getting an error from Bitbucket. We have filed a bug with bitbucket but we haven't heard back from them https://bitbucket.org/site/master/issues/9969/get-commit-revision-api-does-not-accept. Can you please confirm if this is the case?

If this is not the case can you please post the project id so that we can investigate this further?

**Comment by sethamclean** [comment] 2015-10-26 17:19
@kanthchandra This is indeed the case. We use git-flow for our workflow and have many branches with leading "feature/". Strangely we have been able to build such branches in the past. Maybe this is a recent bitbucket change.

**Comment by avinci** [comment] 2015-10-26 18:44
@sethamclean seems like this is a problem with BB for that route. I am going to try and escalate, would help if you comment on it also.

**Comment by sethamclean** [comment] 2015-10-26 20:24
@avinci I have added my comment to this issue. Thanks for filing this.

**Comment by manishas** [comment] 2016-03-07 23:46
This is not a Shippable bug. I have tagged it with 'docs' so we can update our FAQs and then close this.

**Comment by manishas** [comment] 2016-03-14 17:57
This has been added to the FAQ - http://docs.shippable.com/ci_faq/#i-cannot-start-a-manual-build-for-my-bitbucket-project-why-is-it-not-working

**Closed by manishas** 2016-03-14 17:57 UTC
Labels: technical issue, update content
