### ISSUE TITLE
golang code coverage problems

### ISSUE THREAD

**Issue by 9len** [Shippable/support#2411] opened 2016-03-18 19:15 UTC
I am trying to get code coverage to work for our golang project. we have a bunch of packages we build, so I make coverage reports for each. 

Here's a sample build:
https://app.shippable.com/runs/56ec4faa977f060d00f3b32a

I've tried with two different golang coverage converters, `gocover-cobertura` and `gocov`. In this build I've used both, putting results in `./shippable/codecoverage/$PACKAGE/a/coverage.xml` or `./shippable/codecoverage/$PACKAGE/b/coverage.xml`, respectively. I can see that the files are getting picked up, but I get these errors if I look at the `report` output:

```
time="2016-03-18T19:01:02Z" level=error msg="No valid coverage parser : /root/src/github.com/turbinelabs/tbn/shippable/codecoverage/agent/apiflags/b/coverage.xml" 
time="2016-03-18T19:01:02Z" level=error msg="No valid coverage parser : /root/src/github.com/turbinelabs/tbn/shippable/codecoverage/agent/sdagent/b/coverage.xml" 
time="2016-03-18T19:01:02Z" level=error msg="No valid coverage parser : /root/src/github.com/turbinelabs/tbn/shippable/codecoverage/agent/sdagentctl/commands/b/coverage.xml" 
time="2016-03-18T19:01:02Z" level=error msg="No valid coverage parser : /root/src/github.com/turbinelabs/tbn/shippable/codecoverage/agent/sdagentctl/flags/b/coverage.xml" 
time="2016-03-18T19:01:02Z" level=error msg="No valid coverage parser : /root/src/github.com/turbinelabs/tbn/shippable/codecoverage/agent/sdagentctl/helper/b/coverage.xml" 
time="2016-03-18T19:01:02Z" level=error msg="No valid coverage parser : /root/src/github.com/turbinelabs/tbn/shippable/codecoverage/api/b/coverage.xml" 
time="2016-03-18T19:01:02Z" level=error msg="No valid coverage parser : /root/src/github.com/turbinelabs/tbn/shippable/codecoverage/api/kvstore/b/coverage.xml" 
time="2016-03-18T19:01:02Z" level=error msg="No valid coverage parser : /root/src/github.com/turbinelabs/tbn/shippable/codecoverage/api/server/config/b/coverage.xml" 
time="2016-03-18T19:01:02Z" level=error msg="No valid coverage parser : /root/src/github.com/turbinelabs/tbn/shippable/codecoverage/api/server/handler/b/coverage.xml" 
time="2016-03-18T19:01:02Z" level=error msg="No valid coverage parser : /root/src/github.com/turbinelabs/tbn/shippable/codecoverage/api/server/handler/cluster/b/coverage.xml" 
time="2016-03-18T19:01:02Z" level=fatal msg="Unable to parse XML content, /root/src/github.com/turbinelabs/tbn/shippable/codecoverage/agent/apiflags/b/coverage.xml" 
```

any ideas? I've looked at the XML files and they seem reasonable.

**Comment by rageshkrishna** [comment] 2016-03-22 07:50
@9len Can you please share one of these report files with us? It looks like our parser is unable to identify the format of your reports. You can upload it here or email it to me at ragesh@shippable.com. Thanks!

**Comment by manishas** [comment] 2016-03-22 22:46
We are working on a fix for this.... it is being tested in beta so will be deployed soon.

**Comment by 9len** [comment] 2016-03-23 00:15
Awesome. Thanks for the quick responses and turnarounds.

**Comment by manishas** [comment] 2016-03-23 00:32
@9len we will need the report files to make sure we address this specific issue. Can you please send them to ragesh@shippable.com?

**Comment by 9len** [comment] 2016-03-23 00:45
Sent them this morning.

**Comment by manishas** [comment] 2016-03-24 23:36
@ric03uec can you confirm when everything is in prod and close this issue?

**Comment by manishas** [comment] 2016-03-25 01:51
This is confirmed to be in prod so closing the issue. 

@9len let us know if you run into any issues.

**Closed by manishas** 2016-03-25 01:51 UTC
Labels: beta verified, bug

**Comment by 9len** [comment] 2016-03-25 03:24
Coverage no longer produces an error, but it produces reports with all zeros.

https://app.shippable.com/runs/56f4ae5e2eca350d006e090a

(the logs of the running tests indicate non-zero coverage.)

**Comment by ric03uec** [comment] 2016-03-28 06:11
@9len looking at the coverage reports, all the statements for `class` in the xml show the following data

```
<class name="-" filename="<path to file>" line-rate="0" branch-rate="0" complexity="0">
```
We're using this to parse the coverage stats. for some reason all the files have the `line-rate` and `branch-rate` set to 0 because of which you're seeing reports with all zeros.
you can fix it by tweaking the reports generator to add this data.

**Comment by 9len** [comment] 2016-04-07 17:19
ok found a [patch to gocov-xml](github.com/marinbek/gocov-xml) that at least calculates line-rate, so I'm seeing reports. However, within a package, each line is missing the relevant class name. 

https://app.shippable.com/runs/57068ccd4abda90c00d19cdd

I've played around with truncating the package names to make them smaller, and changing the "-" value for static methods to something like "__package" but nothing causes the classnames to appear.

**Comment by 9len** [comment] 2016-04-07 22:13
I have tried a variety of different package and class name variants, including making them look exactly like java package/class names. In all cases, the package name appears to be used instead of the class name. should I file a new issue?
