### ISSUE TITLE
pull_job_image failure

### ISSUE THREAD

**Issue by JeremJR** [Shippable/support#4487] opened 2018-08-07 07:28 UTC
My job doesn't succeed to perform a `docker pull`
```
  shippable_retry sudo docker pull drydock/aarch64_u16all:v6.6.4
Error response from daemon: Get https://registry-1.docker.io/v2/drydock/aarch64_u16all/manifests/v6.6.4: unauthorized: incorrect username or password
retrying 1 of 3 times...
Error response from daemon: Get https://registry-1.docker.io/v2/drydock/aarch64_u16all/manifests/v6.6.4: unauthorized: incorrect username or password
retrying 2 of 3 times...
Error response from daemon: Get https://registry-1.docker.io/v2/drydock/aarch64_u16all/manifests/v6.6.4: unauthorized: incorrect username or password
retrying 3 of 3 times...

```
- Link to the build : failure https://app.shippable.com/github/JeremJR/docker_bonita/runs/5/1/console
- shippable.yml : https://github.com/JeremJR/docker_bonita/blob/master/shippable.yml

**Comment by rageshkrishna** [comment] 2018-08-07 11:32
Hi @JeremJR. Sorry about that... we've identified an issue that occasionally causes image pull to fail on these nodes. The problem has been corrected and you should be able to run your builds now.

We are rolling out a more permanent fix to the problem as we speak and I'll update this issue as soon as it's deployed.

**Comment by JeremJR** [comment] 2018-08-09 08:53
Thank you @rageshkrishna I've made a build successfully https://app.shippable.com/github/JeremJR/docker_bonita/runs/7/1/console

**Comment by rageshkrishna** [comment] 2018-08-14 07:45
@JeremJR Great! We have also deployed a comprehensive fix for the root cause. You should not see this happening again. Closing the issue now.

**Closed as completed by rageshkrishna** 2018-08-14 07:45 UTC
