### ISSUE TITLE
Build stuck on "Waiting" without logs

### ISSUE THREAD

**Issue by ghost** [Shippable/support#4631] opened 2018-10-29 12:56 UTC
Hi, 

My build has been stuck on "Waiting" for a long time. Cancelled and restarted after 20 minutes, but the new build is also stuck on waiting.

Account: chathura24x7
Private Repo: punchh/churnover

**Comment by ankul-shippable** [comment] 2018-10-29 13:10
@chathura24x7 Your new build is waiting for nodes to get free. It will be picked up once a node is free and no builds are waiting prior to this.

We will look into why cancelled build did not get processed. Thanks.

**Comment by rageshkrishna** [comment] 2018-11-02 07:33
@chathura24x7 We had an issue with our node provisioning service taking far longer than it should under certain workloads, causing builds to remain queued for an unusually long time. We deployed a few changes with our latest release on 30-Oct that should address this problem.

I'm going to close the issue as the root cause has been addressed, but feel free to reopen this issue if you don't think it's helping.

**Closed as completed by rageshkrishna** 2018-11-02 07:33 UTC
