### ISSUE TITLE
Build fails with no errors

### ISSUE THREAD

**Issue by swleighton** [Shippable/support#1972] opened 2015-10-27 08:00 UTC
Hi,

I'm new and currently trying to get my head around shippable. I'm trying to build a docker container using pre-ci and a custom image from my private docker hub (a modified version of the docker-build-nodejs (using alpine over Ubuntu)). The shippable yml is the same as that of the example and the logs indicate everything passes but the build fails. 

Could you point me in the direction of where I'm going wrong? 

my bitbucket username is swleighton and the branch is called dockerized

I also tired to attach the log file but need write persimmons. 

Thanks
Simon

**Comment by RonXS** [comment] 2015-10-28 10:24
I'm experiencing the same error, all checks are green, but the build keeps failing. 

I've even removed the "script" tag from the shippable yml file, and only did some basic action like spinning up a docker container and provision it with a Dockerfile.

Everything seems to work as expected, i can't figure out why it is failing.

**Comment by manishas** [comment] 2015-10-29 17:04
we're looking into this... one thing i noticed is that your settings are configured to push the image to docker hub but there is no 'hub push' step in the logs. The error probably happened after build image but we're not handling it correctly.

**Comment by manishas** [comment] 2015-10-29 21:59
@swleighton @RonXS can you please share your shippable.yml?

**Comment by RonXS** [comment] 2015-11-05 08:52
language: php

php:
  - 5.6

git:
  - submodules: false

build_image: ansible/ubuntu14.04-ansible

before_script:
  - ansible-playbook --limit local -i ansible/inventories/inventory.yml ansible/playbook.yml

script: bin/phpunit

notifications:
    email:
      recipients:
        - ronxs@live.nl
      on_success: change
      on_failure: always

**Comment by RonXS** [comment] 2015-11-05 08:59
![schermafbeelding 2015-11-05 om 09 53 33](https://cloud.githubusercontent.com/assets/440788/10963773/2307287c-83a3-11e5-94c8-60597425bf4f.png)

Build fails, but all checks are green. What i would expect:

Between the build_image and save_reports, i expect a "before_script" which runs my ansible, and then the script, which might fail on the unit tests.

This has been reported many times, and its been open for so long, we're expanding our company and my employer already contacted you to urge you to look into this fast.

We cant rely or implement this seriously now. I'm a shippable user since a loooong time, or atleast tried to use it but ran into multiple random errors. But now my hand gets forced to move back to jenkins or implement something myself. 

Please communicate with us, why is this bug in the system for months (first reported by a user on 17th of july if i recall well.)

I'm 100% an error occurs but you just do not expose it to the interface.

**Comment by rageshkrishna** [comment] 2015-11-05 09:55
@RonXS I completely understand your frustration. We are actively working on exposing more details about build failures. In your particular case, the issue is that the docker image you are building does not contain some of the dependencies we require to start running our python build runner. Although our script does try to install any missing dependencies, this also appears to be failing with your built image.

Here's the exact command we run:

````
$SUDO apt-get update && $SUDO apt-get install -y python-pip ssh git-core
````

This is currently failing on your image with:

````
E: Unable to locate package python-pip
````

After this, the rest of our build runner isn't equipped with all the dependencies it needs and the result is that the build container fails to start correctly. I can assure you that surfacing error messages from containers failing to start is exactly what we are working on right now and this will become more transparent in the next few days.

To get past your immediate issue, you will need to update your Dockerfile to allow the command above to succeed. After this point, the build will begin running.

Please let me know if you have any questions.

**Comment by RonXS** [comment] 2015-11-05 10:32
Ok thank you, i got this working by switching from a ubuntu 14.04 ansible image to a new ubuntu 15.10 image, installing ansible myself.

The problem is that in ubuntu 14.04, somehow the pip isnt there and i cant find a ppa that installs it.

**Comment by RonXS** [comment] 2015-11-06 21:11
Can you elaborate why this bug is now marked as resolved + closed

I' m not the opener of this specific bug and to truely close this bug, the actual issue "not disclosing the actual" error needs to be resolved. Is this fixed or was my workaround solution the reason that the bug is marked as done?

It would be nice (or maybe even vital) to see errors that occur by your own provisioning including installing of python-pip and such.

Thanks!

**Comment by avinci** [comment] 2015-11-09 17:45
my mistake.

**Comment by manishas** [comment] 2016-03-02 18:55
we have revamped the build system and this should not happen any more. closing this issue.

**Closed by manishas** 2016-03-02 18:55 UTC
Labels: bug, in progress
