### ISSUE TITLE
Completed builds disappearing from Summary tab

### ISSUE THREAD

**Issue by rarkins** [Shippable/support#2735] opened 2016-06-23 11:09 UTC
Screenshot of build in progress:
![image](https://cloud.githubusercontent.com/assets/6311784/16300858/6289501a-3942-11e6-9e16-37d6c96cd083.png)

Once build 411 is complete, it disappears off the Summary tab and can only be seen on the History tab. It doesn't show even if I enable the "Show all branches" checkbox.

**Comment by manishas** [comment] 2016-06-23 17:21
@a-murphy can you look at this?

**Comment by a-murphy** [comment] 2016-06-23 17:40
It doesn't look like `feature/shippable-aws` existed when the project was last synchronized.  It's not in the list of branches for the project, so it isn't shown on the status tab.  There's a green "sync" button on the settings tab that will update the list of branches.

**Comment by rarkins** [comment] 2016-06-23 17:53
Do you mean we need to manually keep synchronising the project every time there's a new branch? That doesn't seem sensible at all if so. We use git flow approach and majority of tests are of a "new" branch. Please reconsider this design of its somehow deliberate.

**Comment by a-murphy** [comment] 2016-06-23 17:58
The project should be automatically synchronized daily.  To immediately show branches created since the last synchronization currently requires clicking the sync button.

**Comment by rarkins** [comment] 2016-06-24 06:33
This still makes no sense. The builds/branches appear while they're in progress, then disappear once completed. And then they reappear again after the next sync, sometimes in the next 24 hours? 

@manishas please can this be recognised as a mistake or shortcoming in design, and not "resolved"?

**Comment by manishas** [comment] 2016-06-28 19:46
@rarkins I can label this a feature request and think through this a bit. The problem is that we cannot sync too often since this slows down the overall experience and makes it feel sluggish.  

However, your scenario is probably not unique so I'll chat to the team about what we can do and get back to you.

**Comment by rarkins** [comment] 2016-06-29 07:05
@manishas thanks for the info.

Can I check my understanding - the Summary tab is only intended to show current/existing branches on GitHub? So that's why any tested branch disappears from there as soon as the build is finished, if it didn't exist the last time you sync'd branches with GitHub?

If so, I can now understand better why/how this design came to be, but it's still highly undesirable. I would rather risk seeing "old" branches for up to a day than to "miss" actual branches. Not to mention that currently you *still* end up showing old branches anyway, for up to a day, so it's kind of the worst of both worlds as it is.

I would suggest change to design to be:

1. Summary tab shows one "card"/status per branch (as today)
2. Summary tab shows branches in order of most recently built (as today?)
3. As new branches are built, they are added to this list. i.e. they don't "disappear" from the top never to be seen again, they are added to the Branches section
4. Every x hours, you sync with GitHub and trim any branches that have disappeared
5. Supplement the above by listening to the GitHub [DeleteEvent](https://developer.github.com/v3/activity/events/types/#deleteevent) and most of the time you can then remain "perfectly" in sync too. Any time you get out of sync (e.g. missed notification) you would still be cleaning up every X hours as per today. There's also a CreateEvent but you may not need that

**Comment by avinci** [comment] 2017-02-28 03:27
This has been fixed in the recent release where we sync with the branches on a regular cadence which should resolve this problem.

**Closed by avinci** 2017-02-28 03:27 UTC
Labels: feature request, spec
