### ISSUE TITLE
Updating Branches to be Displayed

### ISSUE THREAD

**Issue by herriojr** [Shippable/support#3290] opened 2017-01-17 22:30 UTC
I keep updating this to show my develop branch and remove my master branch, and somehow it keeps reverting back on its own to only show the master branch.  This seems to be done after I do a build for that particular repository.

**Comment by stephanielingwood** [comment] 2017-01-18 00:11
Hi @herriojr,

Sorry to hear you're seeing this. I just tried and was unable to reproduce the problem - would you mind sharing a screenshot of the page where you're still seeing the master branch? If you'd rather not share it here, you can email it to stephanie at shippable dot com. Thanks.

**Comment by stephanielingwood** [comment] 2017-01-19 19:36
Thanks for letting us know about this. We found the bug - it looks like our project sync flow is accidentally resetting the branches to be displayed. I'm going to close this issue, as it's a duplicate of https://github.com/Shippable/support/issues/3301; we'll post in that issue's comments when we have the fix deployed.

**Closed by stephanielingwood** 2017-01-19 19:36 UTC
