### ISSUE TITLE
Support for volume mounts between two containers

### ISSUE THREAD

**Issue by abhijitkini** [Shippable/support#2840] opened 2016-07-28 22:03 UTC
I have an Ubuntu 14.04 container that is calling make. And as a part of my make I run multiple docker run commands. 
My problem is that I cannot get them to honor my volume mounts. I want to share pieces of source code between my two containers.

Is this possible in shippable environment?

**Comment by a-murphy** [comment] 2016-07-29 01:27
I'm assuming that you're trying to create a volume mount from the build container to another container started in the `ci` step of the build.

Any volume mounts are created on the host machine, not in the Shippable build container.  So, when you specify a volume mount for a container, it's being created between the host machine and the new container.  In order to get files from the build container into another container through volume mounts, you can first add volume mounts to the build container in the [`pre_ci_boot`](http://docs.shippable.com/ci_configure/#setting-your-build-image) section of your shippable.yml.  For example, adding ```"-v $SHIPPABLE_BUILD_DIR:$SHIPPABLE_BUILD_DIR"``` in the `pre_ci_boot` options will mount the build directory.  Other directories outside of the build directory may also be chosen.  Then it's possible to mount those volumes in the new containers started in `ci`.

Creating these volume mounts allows files to be shared from the build container to the host machine and the new containers.  However, you do have to be reasonably careful because it is possible for files to be carried over between consecutive builds on the same node this way, causing files from your earlier builds to appear in the later ones if you reuse directories and don't remove the files.  (Nodes are not shared between subscriptions, so it's only your own builds that would be affected.)

**Comment by manishas** [comment] 2016-08-01 23:27
The customer confirmed that this worked, so closing this issue.

**Closed by manishas** 2016-08-01 23:27 UTC
Labels: question
