### ISSUE TITLE
Postgresql in shippable default image

### ISSUE THREAD

**Issue by cratz** [Shippable/support#2304] opened 2016-03-01 16:55 UTC
Postgresql server is not running in the new shippable default image even I specified it as an addon.
Add the following line to your shippable.yml before you try to access (create) the database: 
(start only a specific version. I wanna have 9.3)

```
ci:
  - fancy things
  - "sudo /etc/init.d/postgresql start 9.3"
  - %create database%
  - %run migrations%
  - more fancy things
```

**Comment by manishas** [comment] 2016-03-01 17:48
Can you please share a build link?

We will look into why the addons isn't working. In the meantime, if you want to continue using the old default image, you can do the following in your yml:

```
pre_ci_boot:
     image_name: shippable/minv2
    image_tag: latest
    pull: true
```
This will pull the old default image minv2 for your builds.

**Comment by cratz** [comment] 2016-03-02 08:32
@manishas 
e.g. https://app.shippable.com/runs/56d59ea4797c670c00f6fe71
With my workaround (starting pg server by "hand") it works with the new default image. 
I just created this issue to help other users who have the same problem.

Thank you anyway!

**Comment by rageshkrishna** [comment] 2016-03-02 12:32
I think I see the problem here... specifying postgres as an addon alone does not work, but if you configure and addon and _also_ list it under services, it will start the version you asked for. This should definitely work without having to add both tags to the YML.

We'll fix this soon.

**Comment by cratz** [comment] 2016-03-02 13:30
@rageshkrishna 
Thanks, but I tried it after I read your comment in #2316 
And adding postgres to services will not start the pg  server ;(
Here is the build:
https://app.shippable.com/runs/56d6ce8487a3710b00471568

I did everything described in the [documentation](http://docs.shippable.com/ci_configure/?utm_campaign=Shippable+4+Release#postgresql)
But the only way to have a running pg-server was the one I described in the initial issue description.

**Comment by rageshkrishna** [comment] 2016-03-02 13:34
OK, we'll take a deeper look at this and get back to you soon.

**Comment by rageshkrishna** [comment] 2016-03-03 12:32
@cratz I think our documentation needs to be fixed. Here's a minimal YML that works for me:

````
language: node_js

node_js:
  - "0.10"
  
services:
  - postgres

build:
  pre_ci_boot:
    image_name: shippable/minv2
    image_tag: latest
    pull: false
  ci:
    - echo "Hello, World!"
````

If it still doesn't work, please share your complete YML file. You can email me at ragesh@shippable.com if you'd rather not paste it here. Thanks!

**Comment by cratz** [comment] 2016-03-03 15:50
@rageshkrishna 
Thanks.
I tried it but still not working [here is the build](https://app.shippable.com/runs/56d85890f4bf7e0c0004416e) `could not connect to server: Connection refused`

The important parts of my shippable.yml
```yaml
language: ruby
addons:
  #postgresql: "9.3"
  firefox: "42.0"
service:
  - postgres
build:
  ci: 
    - command which creates database and where the error happens 
```
I can't see any database operation in you example may be you should add something like 
`- psql -c 'create database myapp_test;' -U postgres` to the `ci` section because if I would not run a database operation it would not fail.

Btw. will it be possible to specify a PG version?

**Comment by manishas** [comment] 2016-03-10 17:53
@cratz is this still a  problem?

**Comment by rageshkrishna** [comment] 2016-03-14 03:32
@cratz Sorry for not getting back to you sooner. I think the problem is that you need to call the tag `services` and not `service`, like this:

````
services:
  - postgres
````

To answer your second question, we have removed the ability to specify an older postgres version in the YML file. Our latest drydock image contains v9.4. If you really need older versions, you will need to continue to use shippable/minv2 as your image, or use a custom docker image of your own with the specific versions you need.

Please let me know if you have any more questions around this.

**Comment by manishas** [comment] 2016-03-15 23:37
I am closing this issue since this should work now. Please let us know if you need anything else.

**Closed by manishas** 2016-03-15 23:37 UTC
Labels: bug, resolved

**Comment by cratz** [comment] 2016-03-21 10:12
@rageshkrishna @manishas 
Thanks and sorry for my late answer. I will change our setup accordingly!

**Comment by cratz** [comment] 2016-03-21 14:15
@manishas @rageshkrishna 
I fixed the typo in the shippable.yml and it looks like it is working but I can't check it finally since the latest latest drydock image is not working at all for us. For more details on this see #2313.
