### ISSUE TITLE
nodejs 0.12.0 is building from source ~ 20min build time

### ISSUE THREAD

**Issue by thecaddy** [Shippable/support#1093] opened 2015-02-26 07:08 UTC
Is there any way to install from the nvm binary and/or a shippable container with the latest version of stable node?

**Comment by manishas** [comment] 2015-02-27 21:22
we're investigating this..

**Comment by manishas** [comment] 2015-03-06 17:38
@CADBOT do you have an update on this issue?

**Comment by Vilsepi** [comment] 2015-03-25 13:57
+1 need proper node 0.12 support

**Comment by RobbinHabermehl** [comment] 2015-03-27 16:10
I can confirm this issue; after updating to Node.js version 0.12.0 my build time went from 2 to 3 minutes to about 15.

**Comment by manishas** [comment] 2015-03-27 16:26
We've added node 0.12 to our node specific images. You can use these images by adding the following to your yml -

build_image: shippableimages/ubuntu1204_nodejs 

Check out http://docs.shippable.com/en/latest/custom_images.html#node-js

Please note that these images do not come preinstalled with tools and services so you'll need to install those in before_install section of the yml. If you also turn on caching, these will be available on your cached image from the next run onwards.

**Comment by howarddierking** [comment] 2015-04-17 12:04
using the language specific build agent works fine, but would be great if it were added to the default minion.

**Comment by cloudkite** [comment] 2015-04-21 03:02
+1 please add to default minion

**Comment by matiassingers** [comment] 2015-05-25 08:34
Seems like it just fails because of this:

```sh
mv: cannot move `/home/shippable/.nvm/bin/node-v0.12.4-linux-x64' to `/home/shippable/.nvm/versions/v0.12.4': No such file or directory
Binary download failed, trying source.
```

**Comment by nadavsinai** [comment] 2015-05-31 21:35
+1

**Comment by sungwoncho** [comment] 2015-06-18 00:06
Seeing the same issue as the one pointed out by @matiassingers

**Comment by bastianwegge** [comment] 2015-07-24 18:33
+1

**Comment by posita** [comment] 2015-07-24 18:35
See also #1712, which may be a dup of this, but has additional constraints not addressed by @manishas's [workaround](https://github.com/Shippable/support/issues/1093#issuecomment-86995933).

**Comment by manishas** [comment] 2016-03-01 01:17
We have new default minions in our [drydock repo](https://hub.docker.com/u/drydock/) which have node 0.12 installed.

You will need to upgrade to the new yml format in order to have a drydock image pulled by default.

**Comment by manishas** [comment] 2016-03-02 05:28
closing this one since it is resolved.

**Closed by manishas** 2016-03-02 05:28 UTC
Labels: question, resolved
