### ISSUE TITLE
Web UI is sluggish

### ISSUE THREAD

**Issue by roman-gliffy** [Shippable/support#2730] opened 2016-06-22 16:22 UTC
### Description of your issue:
Web UI is sluggish, to say the least. 
Have to waits 10-15 seconds for pages updates.

**Comment by abhijitkini** [comment] 2016-06-23 00:00
The sluggishness was due to the result of this issue - https://github.com/Shippable/support/issues/2728. 
Closing as the issue is resolved. Let us know if you continue to see slowness in the WebUI.

**Closed by abhijitkini** 2016-06-23 00:00 UTC
Labels: bug, investigate
