### ISSUE TITLE
Dashboard not showing all branches found in history tab

### ISSUE THREAD

**Issue by santtu** [Shippable/support#2786] opened 2016-07-07 08:58 UTC
We've run into a situation where the project status page's *dashboard* tab is not showing all branches that have been built. The built branches can be found in the *history* tab.

So far I have found that going to Settings and doing a manual repository synchronization helps with the problem. It seems that the list of branches to show in the dashboard is based on the *sync* results, but if new branches are created and pushed *after* previous sync these *will not show up* in the dashboard page.

However the pushed branches will appear in the "processing and queued builds" section. But after being built they *will not* show up in the "run status" portion.

Below I pushed a new branch `testing-shippable-dashboard`. 

![image](https://cloud.githubusercontent.com/assets/650612/16647929/4534c2a8-443a-11e6-834a-f5cec4e517bb.png)

This is the situation after that build completed where the previous completed build is not shown:

![image](https://cloud.githubusercontent.com/assets/650612/16647864/f330afc6-4439-11e6-83d7-4deacf5fb4de.png)

but is shown in the history tab:

![image](https://cloud.githubusercontent.com/assets/650612/16647901/1f874300-443a-11e6-8255-6f3cc3fb4691.png)

This is quite confusing.

**Comment by abhijitkini** [comment] 2016-07-07 17:04
@santtu The projects should be synced automatically daily. However, to see branches created immediately, since the last synchronization you'll have to manually sync. 

We understand this is confusing and are looking at options to address this. 
Closing this request as a duplicate of https://github.com/Shippable/support/issues/2735

**Closed by abhijitkini** 2016-07-07 17:04 UTC
Labels: duplicate, feature request
