### ISSUE TITLE
Can't access to our CI

### ISSUE THREAD

**Issue by TimotheeVille** [Shippable/support#4381] opened 2018-06-08 07:50 UTC
Hi guys,
Me and my team encounter some problem since yesterday. After upgrading our plan, just some of us can access to the CI (Github Integration). Others have 404 errors and does not have subscriptions anymore.
Thank you,
Hiptest team.

**Comment by mbrodala** [comment] 2018-06-08 07:55
This is the same as my #4380

**Comment by manishas** [comment] 2018-06-08 07:59
@rageshkrishna can we look into this asap?

**Comment by severinedarlot** [comment] 2018-06-08 08:02
Same problem today

**Comment by rageshkrishna** [comment] 2018-06-08 08:11
This was caused by an issue in our sync service that cropped up while we were upgrading the service today. The problem has been fixed now.

Please visit your "Account Profile" page and sync your account. All access will be restored as soon as you sync.

**Comment by TimotheeVille** [comment] 2018-06-08 08:27
Great, it works!
Thank you for your quick answer

**Closed as completed** 2018-06-08 08:27 UTC
