### ISSUE TITLE
PR is being deployed even with "$IS_PULL_REQUEST" == false

### ISSUE THREAD

**Issue by joshuaohana** [Shippable/support#4690] opened 2018-12-29 15:34 UTC
For certain branches, I do not want PRs to cause a deployment to AWS. As such, I have the below

```
build:
  ci:
    - if [ "$BRANCH" == "develop" ] ; then env=dev npm run build; fi
    - if [ "$BRANCH" == "qa" ] && [ "$IS_PULL_REQUEST" == false ] ; then env=qa npm run build; fi
    - if [ "$BRANCH" == "master" ] && [ "$IS_PULL_REQUEST" == false ] ; then env=prod npm run build; fi
```

My expectation is that this would cause builds and deployments for PRs only into develop, and would ignore PRs into qa or master. That's not happening, and instead PRs trigger builds and deployments on all 3 environments.

The integration yml is
```
integrations:
  deploy:
    - integrationName: "myapp.api-deploy"
      type: aws
      target: eb_paas
      platform: "Node.js"
      application_name:  myapp.api
      env_name: myapp-api-dev
      region: us-east-1    
      branches:
        only:
          - develop
    - integrationName: "myapp.api-deploy"
      type: aws
      target: eb_paas
      platform: "Node.js"
      application_name:  myapp.api
      env_name: myapp-api-qa
      region: us-east-1    
      branches:
        only:
          - qa
    - integrationName: "myapp.api-deploy"
      type: aws
      target: eb_paas
      platform: "Node.js"
      application_name:  myapp.api
      env_name: myapp-api-prod
      region: us-east-1
      steps:
        - IN: myapp.api-deploy
          switch: off
      branches:
        only:
          - master
```

How can I make it to not trigger/build on PRs?

**Comment by DeanHutchison** [comment] 2019-01-02 12:48
@joshuaohana I had a [problem](https://github.com/Shippable/support/issues/4679) which sounds slightly similar to some of what you seem to be experiencing and I eventually found that my issue was caused by an error in my configuration of my repo. I had set `buildOnPullRequest: true` on my gitRepo resource which was causing the repo to build twice one that was the original PR and another build which was just a build on master.

**Comment by a-murphy** [comment] 2019-01-02 19:55
A deploy integration in the `integrations` section of the CI shippable.yml to deploy to Elastic Beanstalk will deploy both pull requests and commits in private repositories, and commits (but not pull requests) in public repositories.  This cannot currently be configured.

Since you want to deploy some, but not all, pull requests, the best solution at this time is not to use `type: aws` integrations in your CI YML.  One option is to add the AWS integrations as `hub` integrations to authenticate with Amazon ECR similarly to the [documentation for pulling a custom image](http://docs.shippable.com/ci/custom-docker-image/#pulling-a-private-image) without actually using a custom image and then issue the commands to deploy to Amazon Elastic Beanstalk yourself in the `ci` section.

**Comment by rageshkrishna** [comment] 2019-02-07 04:13
@joshuaohana Do you still need any help with configuring this?

**Comment by joshuaohana** [comment] 2019-02-07 15:13
Yes I haven't resolved the issue, but I also haven't had much time yet to try the above suggestions. Hopefully our next sprint will have some breathing room for this item and a few others.

**Comment by manishas** [comment] 2019-03-06 21:34
Closing this issue since there are no action items on our side. Please let us know if the suggested solutions don't work.

**Closed as completed by manishas** 2019-03-06 21:34 UTC
