### ISSUE TITLE
`nvm install 0.12` takes 15 minutes

### ISSUE THREAD

**Issue by pkaminski** [Shippable/support#1042] opened 2015-02-09 22:52 UTC
My `shippable.yml` contains:
```
build_environment: ubuntu1204
language: node_js
node_js:
  - "0.12"
```

The build takes 20 minutes, with ~15 minutes spent in state `test_ve`.  I'm guessing you have a cache of common Node versions somewhere, and 0.12 isn't in it.  Could you add it please?  Thanks.

**Comment by angelathewebdev** [comment] 2015-03-11 02:57
+1 for the support, build takes an extremely long time for me as well

**Comment by sguimont** [comment] 2015-03-13 14:40
+1, got the same issue. The build takes too long.  Please fix the issue.
I use the cache option without any effect.

**Comment by shawn9273** [comment] 2015-03-22 23:03
+1, same issue.

**Comment by brocas-dev** [comment] 2015-03-26 05:00
+1

**Comment by nathanboktae** [comment] 2015-03-27 22:19
This is a dupe of #1093 which has a workaround.

**Comment by manishas** [comment] 2015-07-02 16:54
We've added node 0.12 to our node specific images. You can use these images by adding the following to your yml -

build_image: shippableimages/ubuntu1204_nodejs

Check out http://docs.shippable.com/languages/#nodejs

Please note that these images do not come preinstalled with tools and services so you'll need to install those in before_install section of the yml. If you also turn on caching, these will be available on your cached image during subsequent builds.

**Comment by manishas** [comment] 2015-07-02 16:54
Closing.

**Closed by manishas** 2015-07-02 16:54 UTC
Labels: feature request, triaged
