### ISSUE TITLE
npm error install Couldn't read dependencies

### ISSUE THREAD

**Issue by agarcian** [Shippable/support#2021] opened 2015-11-11 03:36 UTC
I am new to Shippable and I am trying to configure a repo that I created following a tutorial.  however, I am getting this error.   Can you please help?

```
npm ERR! install Couldn't read dependencies
npm ERR! Error: Invalid name: "@agarcian/number-formatter"
npm ERR!     at ensureValidName (/home/shippable/.nvm/v0.10.25/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:297:15)
npm ERR!     at Object.module.exports.fixNameField (/home/shippable/.nvm/v0.10.25/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:201:5)
npm ERR!     at /home/shippable/.nvm/v0.10.25/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:29:38
npm ERR!     at Array.forEach (native)
npm ERR!     at normalize (/home/shippable/.nvm/v0.10.25/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:28:15)
npm ERR!     at final (/home/shippable/.nvm/v0.10.25/lib/node_modules/npm/node_modules/read-package-json/read-json.js:328:33)
npm ERR!     at then (/home/shippable/.nvm/v0.10.25/lib/node_modules/npm/node_modules/read-package-json/read-json.js:126:33)
npm ERR!     at /home/shippable/.nvm/v0.10.25/lib/node_modules/npm/node_modules/read-package-json/read-json.js:317:40
npm ERR!     at fs.js:266:14
npm ERR!     at /home/shippable/.nvm/v0.10.25/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:103:5
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     

npm ERR! System Linux 3.13.0-57-generic
npm ERR! command "/home/shippable/.nvm/v0.10.25/bin/node" "/home/shippable/.nvm/v0.10.25/bin/npm" "install"
npm ERR! cwd /home/shippable/workspace/src/github.com/agarcian/number-formatter
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.24
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/shippable/workspace/src/github.com/agarcian/number-formatter/npm-debug.log
npm ERR! not ok code 0
```

**Comment by ric03uec** [comment] 2015-11-11 04:59
@agarcian can you specify the build id that's failing. it seems like one of the packages in `package.json` might be failing but we'll get a better idea from the build console.

**Comment by agarcian** [comment] 2015-11-11 06:03
All bbuilds are failing.  The latest one was 5642b68053e5e00e0093b20d  build 11.

**Comment by ric03uec** [comment] 2015-11-11 16:50
the issue is in the `name` field of `package.json` file. although the official documentation for this field (https://docs.npmjs.com/files/package.json#name) does not mention any restriction on whether the name should start with `@` character, it seems that the `npm install` command is failing because of it.
i changed the `name` to `number-formatter` and the install step passed. 
can you try this and let me know if it works for you. thanks

**Comment by manishas** [comment] 2015-11-13 00:54
Closing this issue. @agarcian please let us know if the suggestion above does not fix your issue.

**Closed by manishas** 2015-11-13 00:54 UTC
Labels: bug, in progress
