### ISSUE TITLE
after_push trigger after pushing a docker image 

### ISSUE THREAD

**Issue by rvdwijngaard** [Shippable/support#1594] opened 2015-06-23 13:24 UTC
Is there already an after_push trigger which is fired after pushing an image to the docker repo?  this would make the integration with our CI / CD pipeline so much better.

**Comment by manishas** [comment] 2015-06-23 15:44
as of today, no. we have this feedback from multiple people, so this is definitely coming up soon.

**Comment by pmoust** [comment] 2015-07-01 13:20
Would love to see this implemented.

**Comment by avinci** [comment] 2015-07-01 13:34
I have a question for the folks on this thread. 
Internally we are using web hooks to trigger workflows and we are planning to expose that as external triggers. Would that work for you guys?  The reason for web hooks instead of tags is that i believe tags in YML are very primitive and do not give us a lot of execution control, especially from a central vantage point.
for e.g
The issue is with matrix builds. Since they execute in a parallel fashion, each job is unaware of other jobs within the same build trigger. Docker push can occur only if all the jobs finish and hence we have to do this externally. Hence we are planning to move out more of the logic away from the YML and centralize at a build level. i.e. either we need two YML, one for the job i.e. instal scripts, scripts etc and 1 for the over all build script. 

This does cause some annoyance for folks who have a single job in a build and don't care about matrix...As a result, some of the build related stuff we want to push to UI as it doesn't change much and the job related stuff, we keep it in YML.

Any thoughts?

**Comment by pmoust** [comment] 2015-07-01 13:57
@avinci webhooks would cover our case, essentially this is what we would use the `after_push:` tag for, to ping a deployment service that it can chew the newly pushed docker container. We could've used a Webhook on Dockerhub, but the issue is that Dockehub payload contains no info on tags, so we have no clue "what" triggered the webhook. Our solution is to grab the Dockerhub payload that contains the sha1 of the layer that was pushed, and then list tags, find the sha1, and check against your API to figure out it came from you guys, (and not from freaky devops or dev that pushed in the docker repo).

The benefit of yml vs webhook is that`after_push` lies within the scope of the CI container and has the benefit of invoking other tools apart from a plain curl postback. Even if it's just a curl, in `after_push` one could craft the payload that is being sent to what he needs it to be, or call more than one service. (i.e. Trigger a deployment, Notify on Slack, trigger a push to a private registry and what not).

Then again, if what you call "external webhooks" has some modularity or has some basic integrations, it should be fine for 95%+ of the cases.

**Comment by rvdwijngaard** [comment] 2015-07-02 09:03
@avinci clear explanation, I understand the complexity. We are not using matrix builds until now. I want to deploy an image once has been published to docker repo. I agree with @pmoust  about the dockerhub payload. Since we are on aws we create an sns topic which initiates the deployment for a project. We are using EC2 Container Services to deploy containers on aws. We are now sending the deploy message too early, by using the after_success tag. This is far from ideal.

A webhook would be an improvement but it will make the situation more complicated (as described by @pmoust) Being able to use the yml will give you more control over the security. Our dedicated hosts have an IAM so we can use the aws api directly. 

I would prefer the yml option.

**Comment by pmoust** [comment] 2015-07-02 09:50
Since @rvdwijngaard brought it up, @avinci please reconsider your descision to kill support for dedicated hosts. IAM roles greatly simplify the security implications of a CI/CD in AWS.

**Comment by manishas** [comment] 2015-07-02 23:52
@pmoust we're already reconsidering :)

Closing the original request as a dup of #824 since i'm consolidating all requests around docker pushes, tags, etc in that issue.

**Closed by manishas** 2015-07-02 23:52 UTC
Labels: feature request, triaged
