### ISSUE TITLE
How to use same environment variables in multiple jobs?

### ISSUE THREAD

**Issue by jplimpens** [Shippable/support#4233] opened 2018-03-28 19:16 UTC
Hi,

I have defined several environment variables in the shippable yml which I like to use in multiple jobs.
The env's are defined as
`
env:
    global:
        - name=value
`

These envs are available in the ci part of the yml, but not in the jobs. Using some bash and shipctl I could copy a file to the next job (mis)using state (if I understand the documentation correctly), but it would require to have the previous job as IN. This implies copying the file from each job to the next one in line, even when some jobs don't need them.

Is there a better way to have these env's available, only in the jobs which require these?

**Comment by a-murphy** [comment] 2018-03-28 20:27
Environment variables in non-CI jobs are often specified in [params](http://docs.shippable.com/platform/workflow/resource/params/) resources.  The same params resource can be used as an input to multiple jobs if you have more than one job that uses the same environment variables.  A params resource can also be used as an input to a runCI job in your `shippable.yml`, if you would prefer to use the same resource for that as well.

**Comment by jplimpens** [comment] 2018-03-29 11:52
Well, unfortunately I tried that before and just tried it again. But that fails for most of the params resources. Most variables I use contain special characters like . | / = 
Using `env: global:  - name=value` these special characters (even when encrypted) are contained between ". Works fine.

When using params it shows `An error occurred while trying to export an environment variable` in the Setup step. And some piece of a string followed by the message it is not a valid identifier.

Even surrounding the value of the key-value pair with and additional ' doesn't work.
As an example:
`
KEY='"abs.ert.xdf=sedf|dfhjf_hjh=dfdf|dfdf=sdfjdskjfdksdfj=|dfd=dfd://dfdsf/dfds/dfs/|wer=ssdd3324|"'
`
would go in the to encrypt field and result into 'secure: something' which I include into the versionTemplate like:
`
versionTemplate:
   params:
        secure: something
`
So regarding the original question, I can see how params can be a better solution for values without special characters. But not in this case it seems.. or am I doing something wrong here?

**Comment by trriplejay** [comment] 2018-03-29 17:53
@jplimpens did you try both secure and insecure for the params resource? key/value pair integration is a perfectly fine workaround. We have a known issue in parsing the `=` that is likely the cause of these errors you're seeing.  We're tracking this internally, so I can update this issue once that fix is released.

**Comment by manishas** [comment] 2018-05-18 18:05
This will be fixed in the next release.

**Comment by manishas** [comment] 2018-05-30 00:40
We have fixed the issue with parsing secure vars. Closing this issue.

**Closed by manishas** 2018-05-30 00:40 UTC
Labels: bug, execute
