### ISSUE TITLE
My build fails after the "pulling image from hub" step, with no error message or indication as to why

### ISSUE THREAD

**Issue by asgeo1** [Shippable/support#1749] opened 2015-08-03 06:08 UTC
Today, I've had nothing but issues.  Earlier it was getting stuck on the "Waiting for logs..." message - which I have no idea what that means. Quite an unhelpful message.

Now, it's started failing instead:

https://app.shippable.com/builds/55bf027bd0aba10b0007f8df

![image](https://cloud.githubusercontent.com/assets/702212/9034467/46941810-3a13-11e5-8b21-a8e269e2b15d.png)

But there is no indication as to why it failed.

Obviously it's something at your end?

What's going on with the service?  It's all over the place today.

**Comment by pmoust** [comment] 2015-08-03 08:02
We are experiencing the same.

**Comment by GriwMF** [comment] 2015-08-03 11:25
Same for me

**Comment by simensen** [comment] 2015-08-03 12:29
I've been having this problem since at least last night.

**Comment by aris-b** [comment] 2015-08-03 13:59
Same problem..

**Comment by tomfotherby** [comment] 2015-08-03 14:05
Having this fixed would make me happy.

**Comment by manishas** [comment] 2015-08-03 14:50
We'll look into this asap.

**Comment by rageshkrishna** [comment] 2015-08-03 14:57
Folks, we're very sorry about this issue. Late last night we ran in to a resource issue on some of the build hosts and decided to provision new hosts.

Some of the changes that happened towards the end of last week required a git repository to be manually cloned on the hosts while provisioning new hosts. This step was not performed on the new hosts that were provisioned last night. Because of this, the build containers were not able to launch. Unfortunately, we were unable to figure this out quickly enough.

We're fixing this now and your builds will start running shortly.

**Comment by pmoust** [comment] 2015-08-03 14:59
Thanks @manishas @rageshkrishna .

(P.S. embrace the awesomeness of packer.io for pre-baked immutable VMs ;))

**Comment by pmoust** [comment] 2015-08-03 15:28
Can confirm our minions work fine atm.

**Comment by lekhab** [comment] 2015-08-05 17:10
closing since the issue is resolved.

**Closed by lekhab** 2015-08-05 17:10 UTC
Labels: bug, resolved
