### ISSUE TITLE
API: /projects returns [] and status code 200 with empty apiToken

### ISSUE THREAD

**Issue by pquentin** [Shippable/support#2447] opened 2016-03-29 07:44 UTC
We recently had a failure in the way we store our Shippable API Token in Kubernetes: it became empty. I would expect this to return a 4xx error and a message (just as it's done with other errors). But I received an empty list instead. Is it possible to change this behavior?

```
$ http -v "https://api.shippable.com/projects" "Authorization: apiToken "
GET /projects HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Authorization:  apiToken
Connection: keep-alive
Host: api.shippable.com
User-Agent: HTTPie/0.9.3



HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Accept,Content-Type,Authorization,Cookie
Access-Control-Allow-Methods: GET,PUT,POST,DELETE
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 2
Content-Type: application/json; charset=utf-8
Date: Tue, 29 Mar 2016 07:40:39 GMT
ETag: "223132457"
X-Powered-By: Express

[]
```

Thank your for Shippable

**Comment by avinci** [comment] 2016-03-29 13:47
Which route is this? If its a generic search route, then it will always give you an empty [] since its a collection. If you are calling a `route/:id` it should return a 404.

If the token itself is invalid and the route is public i.e. incase of runs and jobs as public projects also need to be addressed, we default the invalid token as a public call.

**Comment by pquentin** [comment] 2016-03-29 13:57
I don't think the route matters much here. If `apiToken` is not empty I do get a 401 as expected:

```
$ http -v "https://api.shippable.com/projects" "Authorization: apiToken foo"
GET /projects HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Authorization:  apiToken foo
Connection: keep-alive
Host: api.shippable.com
User-Agent: HTTPie/0.9.3



HTTP/1.1 401 Unauthorized
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Accept,Content-Type,Authorization,Cookie
Access-Control-Allow-Methods: GET,PUT,POST,DELETE
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 138
Content-Type: application/json; charset=utf-8
Date: Tue, 29 Mar 2016 13:56:29 GMT
ETag: "-1855353536"
X-Powered-By: Express

{
    "id": 2000,
    "logType": "warn",
    "message": "invalid apiToken",
    "methodName": "common|validateCaller|route:/projects|_getAccountIdByMachineToken"
}```

Feel free to close as won't fix.

**Comment by avinci** [comment] 2016-03-29 14:44
yeah this is by design. Projects is a public route and hence the behavior. Closing it as its by design.

**Closed by avinci** 2016-03-29 14:44 UTC
Labels: investigate, won't fix

**Comment by pquentin** [comment] 2016-03-29 17:10
(Just to be clear, I was just saying the sending an empty token should not have the same behavior as not sending one at all. I do understand that /projects is a public route.)
